oSocial: Smarty_Internal_Data Class Reference
Smarty_Internal_Data Class Reference
Public Member Functions
assign ($tpl_var, $value=null, $nocache=false)
assignGlobal ($varname, $value=null, $nocache=false)
assignByRef ($tpl_var, &$value, $nocache=false)
append ($tpl_var, $value=null, $merge=false, $nocache=false)
appendByRef ($tpl_var, &$value, $merge=false)
getTemplateVars ($varname=null, $_ptr=null, $search_parents=true)
clearAssign ($tpl_var)
clearAllAssign ()
configLoad ($config_file, $sections=null)
getVariable ($variable, $_ptr=null, $search_parents=true, $error_enable=true)
getConfigVariable ($variable, $error_enable=true)
getStreamVariable ($variable)
getConfigVars ($varname=null, $search_parents=true)
clearConfig ($varname=null)
Data Fields
$template_class = 'Smarty_Internal_Template'
$tpl_vars = array()
$parent = null
$config_vars = array()
Detailed Description
Definition at line 18 of file smarty_internal_data.php.
Member Function Documentation
append ($tpl_var, $value = null, $merge = false, $nocache = false)
appends values to template variables
Parameters
array | string $tpl_var the template variable name(s)
mixed $value the value to append
boolean $merge flag if array elements shall be merged
boolean $nocache if true any output of this variable will be not cached
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 116 of file smarty_internal_data.php.
References getVariable().
 {
if (is_array($tpl_var)) {
// $tpl_var is an array, ignore $value
foreach ($tpl_var as $_key => $_val) {
if ($_key != '') {
if (!isset($this->tpl_vars[$_key])) {
 $tpl_var_inst = $this->getVariable($_key,
                null, true, false);
if ($tpl_var_inst instanceof Undefined_Smarty_Variable)
                {
 $this->tpl_vars[$_key] = new Smarty_variable(null,
                $nocache);
 } else {
 $this->tpl_vars[$_key] = clone $tpl_var_inst;
 }
 }
if (!(is_array($this->tpl_vars[$_key]->value) ||
                $this->tpl_vars[$_key]->value instanceof ArrayAccess))
                {
 settype($this->tpl_vars[$_key]->value, 'array');
 }
if ($merge && is_array($_val)) {
foreach ($_val as $_mkey => $_mval) {
 $this->tpl_vars[$_key]->value[$_mkey] = $_mval;
 }
 } else {
 $this->tpl_vars[$_key]->value[] = $_val;
 }
 }
 }
 } else {
if ($tpl_var != '' && isset($value)) {
if (!isset($this->tpl_vars[$tpl_var])) {
 $tpl_var_inst = $this->getVariable($tpl_var,
                null, true, false);
if ($tpl_var_inst instanceof Undefined_Smarty_Variable)
                {
 $this->tpl_vars[$tpl_var] = new Smarty_variable(null,
                $nocache);
 } else {
 $this->tpl_vars[$tpl_var] = clone $tpl_var_inst;
 }
 }
if (!(is_array($this->tpl_vars[$tpl_var]->value) ||
                $this->tpl_vars[$tpl_var]->value instanceof ArrayAccess)) {
 settype($this->tpl_vars[$tpl_var]->value, 'array');
 }
if ($merge && is_array($value)) {
foreach ($value as $_mkey => $_mval) {
 $this->tpl_vars[$tpl_var]->value[$_mkey] = $_mval;
 }
 } else {
 $this->tpl_vars[$tpl_var]->value[] = $value;
 }
 }
 }
return $this;
 }
appendByRef ($tpl_var, & $value, $merge = false)
appends values to template variables by reference
Parameters
string $tpl_var the template variable name
mixed &$value the referenced value to append
boolean $merge flag if array elements shall be merged
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 176 of file smarty_internal_data.php.
Referenced by SmartyBC\append_by_ref().
 {
if ($tpl_var != '' && isset($value)) {
if (!isset($this->tpl_vars[$tpl_var])) {
 $this->tpl_vars[$tpl_var] = new Smarty_variable();
 }
if (!is_array($this->tpl_vars[$tpl_var]->value)) {
 settype($this->tpl_vars[$tpl_var]->value, 'array');
 }
if ($merge && is_array($value)) {
foreach ($value as $_key => $_val) {
 $this->tpl_vars[$tpl_var]->value[$_key] = & $value[$_key];
 }
 } else {
 $this->tpl_vars[$tpl_var]->value[] = & $value;
 }
 }
return $this;
 }
assign ($tpl_var, $value = null, $nocache = false)
assigns a Smarty variable
Parameters
array | string $tpl_var the template variable name(s)
mixed $value the value to assign
boolean $nocache if true any output of this variable will be not cached
boolean $scope the scope the variable will have (local,parent or root)
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 55 of file smarty_internal_data.php.
 {
if (is_array($tpl_var)) {
foreach ($tpl_var as $_key => $_val) {
if ($_key != '') {
 $this->tpl_vars[$_key] = new Smarty_variable($_val,
                $nocache);
 }
 }
 } else {
if ($tpl_var != '') {
 $this->tpl_vars[$tpl_var] = new Smarty_variable($value,
                $nocache);
 }
 }
return $this;
 }
assignByRef ($tpl_var, & $value, $nocache = false)
assigns values to template variables by reference
Parameters
string $tpl_var the template variable name
mixed $ &$value the referenced value to assign
boolean $nocache if true any output of this variable will be not cached
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 97 of file smarty_internal_data.php.
Referenced by SmartyBC\assign_by_ref().
 {
if ($tpl_var != '') {
 $this->tpl_vars[$tpl_var] = new Smarty_variable(null,
                $nocache);
 $this->tpl_vars[$tpl_var]->value = & $value;
 }
return $this;
 }
assignGlobal ($varname, $value = null, $nocache = false)
assigns a global Smarty variable
Parameters
string $varname the global variable name
mixed $value the value to assign
boolean $nocache if true any output of this variable will be not cached
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 80 of file smarty_internal_data.php.
References Smarty\$global_tpl_vars.
Referenced by Smarty\__construct().
 {
if ($varname != '') {
Smarty::$global_tpl_vars[$varname]
                = new Smarty_variable($value, $nocache);
 }
return $this;
 }
clearAllAssign ()
clear all the assigned template variables.
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 266 of file smarty_internal_data.php.
Referenced by SmartyBC\clear_all_assign().
 {
 $this->tpl_vars = array();
return $this;
 }
clearAssign ($tpl_var)
clear the given assigned template variable.
Parameters
string | array $tpl_var the template variable(s) to clear
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 249 of file smarty_internal_data.php.
Referenced by SmartyBC\clear_assign().
 {
if (is_array($tpl_var)) {
foreach ($tpl_var as $curr_var) {
 unset($this->tpl_vars[$curr_var]);
 }
 } else {
 unset($this->tpl_vars[$tpl_var]);
 }
return $this;
 }
clearConfig ($varname = null)
Deassigns a single or all config variables
Parameters
string $varname variable name or null
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 410 of file smarty_internal_data.php.
Referenced by SmartyBC\clear_config().
 {
if (isset($varname)) {
 unset($this->config_vars[$varname]);
 } else {
 $this->config_vars = array();
 }
return $this;
 }
configLoad ($config_file, $sections = null)
load a config file, optionally load just selected sections
Parameters
string $config_file filename
mixed $sections array of section names, single section or null
Returns
Smarty_Internal_Data current Smarty_Internal_Data (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 279 of file smarty_internal_data.php.
 {
// load Config class
 $config = new Smarty_Internal_Config($config_file,
                $this->smarty, $this);
 $config->loadConfigVars($sections);
return $this;
 }
getConfigVariable ($variable, $error_enable = true)
gets a config variable
Parameters
string $variable the name of the config variable
Returns
mixed the value of the config variable
Definition at line 329 of file smarty_internal_data.php.
 {
 $_ptr = $this;
while ($_ptr !== null) {
if (isset($_ptr->config_vars[$variable])) {
// found it, return it
return $_ptr->config_vars[$variable];
 }
// not found, try at parent
 $_ptr = $_ptr->parent;
 }
if ($this->smarty->error_unassigned &&
                $error_enable) {
// force a notice
 $x = $$variable;
 }
return null;
 }
getConfigVars ($varname = null, $search_parents = true)
Returns a single or all config variables
Parameters
string $varname variable name or null
Returns
string variable value or or array of variables
Definition at line 378 of file smarty_internal_data.php.
Referenced by SmartyBC\get_config_vars().
 {
 $_ptr = $this;
 $var_array = array();
while ($_ptr !== null) {
if (isset($varname)) {
if (isset($_ptr->config_vars[$varname])) {
return $_ptr->config_vars[$varname];
 }
 } else {
 $var_array = array_merge($_ptr->config_vars, $var_array);
 }
// not found, try at parent
if ($search_parents) {
 $_ptr = $_ptr->parent;
 } else {
 $_ptr = null;
 }
 }
if (isset($varname)) {
return '';
 } else {
return $var_array;
 }
 }
getStreamVariable ($variable)
gets a stream variable
Parameters
string $variable the stream of the variable
Returns
mixed the value of the stream variable
Definition at line 353 of file smarty_internal_data.php.
 {
 $_result = '';
 $fp = fopen($variable, 'r+');
if ($fp) {
while (!feof($fp) && ($current_line = fgets($fp))
                !== false) {
 $_result .= $current_line;
 }
 fclose($fp);
return $_result;
 }
if ($this->smarty->error_unassigned) {
throw new SmartyException('Undefined stream variable "' . $variable . '"');
 } else {
return null;
 }
 }
getTemplateVars ($varname = null, $_ptr = null, $search_parents = true)
Returns a single or all template variables
Parameters
string $varname variable name or null
string $_ptr optional pointer to data object
boolean $search_parents include parent templates?
Returns
string variable value or or array of variables
Definition at line 205 of file smarty_internal_data.php.
References Smarty\$global_tpl_vars, and getVariable().
Referenced by SmartyBC\get_template_vars(), and Smarty_Internal_Resource_PHP\renderUncompiled().
 {
if (isset($varname)) {
 $_var = $this->getVariable($varname,
                $_ptr, $search_parents, false);
if (is_object($_var)) {
return $_var->value;
 } else {
return null;
 }
 } else {
 $_result = array();
if ($_ptr === null) {
 $_ptr = $this;
 }
while ($_ptr !== null) {
foreach ($_ptr->tpl_vars AS $key => $var) {
if (!array_key_exists($key, $_result)) {
 $_result[$key] = $var->value;
 }
 }
// not found, try at parent
if ($search_parents) {
 $_ptr = $_ptr->parent;
 } else {
 $_ptr = null;
 }
 }
if ($search_parents && isset(Smarty::$global_tpl_vars))
                {
foreach (Smarty::$global_tpl_vars
                AS $key => $var) {
if (!array_key_exists($key, $_result)) {
 $_result[$key] = $var->value;
 }
 }
 }
return $_result;
 }
 }
getVariable ($variable, $_ptr = null, $search_parents = true, $error_enable = true)
gets the object of a Smarty variable
Parameters
string $variable the name of the Smarty variable
object $_ptr optional pointer to data object
boolean $search_parents search also in parent data
Returns
object the object of the variable
Definition at line 295 of file smarty_internal_data.php.
References Smarty\$global_tpl_vars.
Referenced by append(), and getTemplateVars().
 {
if ($_ptr === null) {
 $_ptr = $this;
 }
while ($_ptr !== null) {
if (isset($_ptr->tpl_vars[$variable])) {
// found it, return it
return $_ptr->tpl_vars[$variable];
 }
// not found, try at parent
if ($search_parents) {
 $_ptr = $_ptr->parent;
 } else {
 $_ptr = null;
 }
 }
if (isset(Smarty::$global_tpl_vars[$variable]))
                {
// found it, return it
return Smarty::$global_tpl_vars[$variable];
 }
if ($this->smarty->error_unassigned &&
                $error_enable) {
// force a notice
 $x = $$variable;
 }
return new Undefined_Smarty_Variable;
 }
Field Documentation
$config_vars = array()
Definition at line 44 of file smarty_internal_data.php.
Referenced by Smarty_Internal_TemplateBase\fetch(), Smarty_Internal_Debug\get_debug_vars(), Smarty_Internal_Template\getSubTemplate(), and Smarty_Internal_Template\setupInlineSubTemplate().
$parent = null
Definition at line 38 of file smarty_internal_data.php.
Referenced by Smarty_Internal_TemplateBase\createData(), Smarty\createTemplate(), Smarty_Internal_TemplateBase\display(), Smarty_Internal_TemplateBase\fetch(), Smarty_Internal_Debug\get_debug_vars(), and Smarty_Internal_TemplateBase\isCached().
$template_class = 'Smarty_Internal_Template'
Definition at line 26 of file smarty_internal_data.php.
Referenced by Smarty_Internal_TemplateBase\fetch().
$tpl_vars = array()
Definition at line 32 of file smarty_internal_data.php.
Referenced by Smarty_Internal_TemplateBase\fetch(), Smarty_Internal_Debug\get_debug_vars(), Smarty_Internal_Template\getSubTemplate(), and Smarty_Internal_Template\setupInlineSubTemplate().
The documentation for this class was generated from the following file:
smarty_internal_data.php