oSocial: Smarty_Internal_Configfilelexer Class Reference
Smarty_Internal_Configfilelexer Class Reference
Public Member Functions
__construct ($data, $smarty)
yylex ()
yypushstate ($state)
yypopstate ()
yybegin ($state)
yylex1 ()
yy_r1_1 ($yy_subpatterns)
yy_r1_2 ($yy_subpatterns)
yy_r1_3 ($yy_subpatterns)
yy_r1_4 ($yy_subpatterns)
yy_r1_5 ($yy_subpatterns)
yy_r1_6 ($yy_subpatterns)
yy_r1_7 ($yy_subpatterns)
yy_r1_8 ($yy_subpatterns)
yylex2 ()
yy_r2_1 ($yy_subpatterns)
yy_r2_2 ($yy_subpatterns)
yy_r2_3 ($yy_subpatterns)
yy_r2_4 ($yy_subpatterns)
yy_r2_5 ($yy_subpatterns)
yy_r2_6 ($yy_subpatterns)
yy_r2_7 ($yy_subpatterns)
yy_r2_8 ($yy_subpatterns)
yy_r2_9 ($yy_subpatterns)
yylex3 ()
yy_r3_1 ($yy_subpatterns)
yylex4 ()
yy_r4_1 ($yy_subpatterns)
yy_r4_2 ($yy_subpatterns)
yy_r4_3 ($yy_subpatterns)
yylex5 ()
yy_r5_1 ($yy_subpatterns)
yy_r5_2 ($yy_subpatterns)
yylex6 ()
yy_r6_1 ($yy_subpatterns)
yy_r6_2 ($yy_subpatterns)
Static Public Member Functions
static & instance ($new_instance=null)
Data Fields
$data
$counter
$token
$value
$node
$line
$smarty_token_names
const START = 1
const VALUE = 2
const NAKED_STRING_VALUE = 3
const COMMENT = 4
const SECTION = 5
const TRIPPLE = 6
Private Attributes
$state = 1
$_yy_state = 1
$_yy_stack = array()
Detailed Description
Smarty Internal Plugin Configfilelexer
Definition at line 13 of file smarty_internal_configfilelexer.php.
Constructor & Destructor Documentation
__construct ($data, $smarty)
Definition at line 27 of file smarty_internal_configfilelexer.php.
References $data.
 {
// set instance object
 self::instance($this);
 $this->data = $data
                . "\n"; //now all lines are \n-terminated
 $this->counter = 0;
 $this->line = 1;
 $this->smarty = $smarty;
 $this->mbstring_overload = ini_get('mbstring.func_overload')
                & 2;
 }
Member Function Documentation
static& instance ($new_instance = null) static
Definition at line 38 of file smarty_internal_configfilelexer.php.
Referenced by Smarty_Internal_Config_File_Compiler\trigger_config_file_error().
 {
static $instance = null;
if (isset($new_instance) &&
                is_object($new_instance))
 $instance = $new_instance;
return $instance;
 }
yy_r1_1 ($yy_subpatterns)
Definition at line 139 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_COMMENTSTART, and yypushstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_COMMENTSTART;
 $this->yypushstate(self::COMMENT);
 }
yy_r1_2 ($yy_subpatterns)
Definition at line 146 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_OPENB, and yypushstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_OPENB;
 $this->yypushstate(self::SECTION);
 }
yy_r1_3 ($yy_subpatterns)
Definition at line 153 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_CLOSEB.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_CLOSEB;
 }
yy_r1_4 ($yy_subpatterns)
Definition at line 159 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_EQUAL, and yypushstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_EQUAL;
 $this->yypushstate(self::VALUE);
 }
yy_r1_5 ($yy_subpatterns)
Definition at line 166 of file smarty_internal_configfilelexer.php.
 {
return false;
 }
yy_r1_6 ($yy_subpatterns)
Definition at line 172 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NEWLINE.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NEWLINE;
 }
yy_r1_7 ($yy_subpatterns)
Definition at line 178 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_ID.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_ID;
 }
yy_r1_8 ($yy_subpatterns)
Definition at line 184 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_OTHER.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_OTHER;
 }
yy_r2_1 ($yy_subpatterns)
Definition at line 259 of file smarty_internal_configfilelexer.php.
 {
return false;
 }
yy_r2_2 ($yy_subpatterns)
Definition at line 265 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_FLOAT, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_FLOAT;
 $this->yypopstate();
 }
yy_r2_3 ($yy_subpatterns)
Definition at line 272 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_INT, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_INT;
 $this->yypopstate();
 }
yy_r2_4 ($yy_subpatterns)
Definition at line 279 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_TRIPPLE_QUOTES, and yypushstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_TRIPPLE_QUOTES;
 $this->yypushstate(self::TRIPPLE);
 }
yy_r2_5 ($yy_subpatterns)
Definition at line 286 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_SINGLE_QUOTED_STRING, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_SINGLE_QUOTED_STRING;
 $this->yypopstate();
 }
yy_r2_6 ($yy_subpatterns)
Definition at line 293 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_DOUBLE_QUOTED_STRING, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_DOUBLE_QUOTED_STRING;
 $this->yypopstate();
 }
yy_r2_7 ($yy_subpatterns)
Definition at line 300 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_BOOL, yypopstate(), and yypushstate().
 {
if (!$this->smarty->config_booleanize ||
                !in_array(strtolower($this->value), Array("true", "false", "on", "off",
                "yes", "no")))
                {
 $this->yypopstate();
 $this->yypushstate(self::NAKED_STRING_VALUE);
return true; //reprocess in new state
 } else {
 $this->token = Smarty_Internal_Configfileparser::TPC_BOOL;
 $this->yypopstate();
 }
 }
yy_r2_8 ($yy_subpatterns)
Definition at line 313 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NAKED_STRING, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NAKED_STRING;
 $this->yypopstate();
 }
yy_r2_9 ($yy_subpatterns)
Definition at line 320 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NAKED_STRING, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NAKED_STRING;
 $this->value = "";
 $this->yypopstate();
 }
yy_r3_1 ($yy_subpatterns)
Definition at line 389 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NAKED_STRING, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NAKED_STRING;
 $this->yypopstate();
 }
yy_r4_1 ($yy_subpatterns)
Definition at line 459 of file smarty_internal_configfilelexer.php.
 {
return false;
 }
yy_r4_2 ($yy_subpatterns)
Definition at line 465 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NAKED_STRING.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NAKED_STRING;
 }
yy_r4_3 ($yy_subpatterns)
Definition at line 471 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_NEWLINE, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_NEWLINE;
 $this->yypopstate();
 }
yy_r5_1 ($yy_subpatterns)
Definition at line 540 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_DOT.
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_DOT;
 }
yy_r5_2 ($yy_subpatterns)
Definition at line 546 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_SECTION, and yypopstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_SECTION;
 $this->yypopstate();
 }
yy_r6_1 ($yy_subpatterns)
Definition at line 615 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_TRIPPLE_QUOTES_END, yypopstate(), and yypushstate().
 {
 $this->token = Smarty_Internal_Configfileparser::TPC_TRIPPLE_QUOTES_END;
 $this->yypopstate();
 $this->yypushstate(self::START);
 }
yy_r6_2 ($yy_subpatterns)
Definition at line 623 of file smarty_internal_configfilelexer.php.
References Smarty_Internal_Configfileparser\TPC_TRIPPLE_TEXT.
 {
if ($this->mbstring_overload) {
 $to = mb_strlen($this->data, 'latin1');
 } else {
 $to = strlen($this->data);
 }
 preg_match("/\"\"\"[ \t\r]*[\n#;]/", $this->data,
                $match, PREG_OFFSET_CAPTURE, $this->counter);
if (isset($match[0][1])) {
 $to = $match[0][1];
 } else {
 $this->compiler->trigger_template_error("missing or misspelled literal closing tag");
 }
if ($this->mbstring_overload) {
 $this->value = mb_substr($this->data, $this->counter, $to - $this->counter,
                'latin1');
 } else {
 $this->value = substr($this->data, $this->counter, $to - $this->counter);
 }
 $this->token = Smarty_Internal_Configfileparser::TPC_TRIPPLE_TEXT;
 }
yybegin ($state)
Definition at line 66 of file smarty_internal_configfilelexer.php.
References $state.
 {
 $this->_yy_state = $state;
 }
yylex ()
Definition at line 50 of file smarty_internal_configfilelexer.php.
Referenced by yylex1(), yylex2(), yylex3(), yylex4(), yylex5(), and yylex6().
 {
return $this->{'yylex'
                . $this->_yy_state}();
 }
yylex1 ()
Definition at line 72 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 0,
 4 => 0,
 5 => 0,
 6 => 0,
 7 => 0,
 8 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(#|;)|\G(\\[)|\G(\\])|\G(=)|\G([ \t\r]+)|\G(\n)|\G([0-9]*[a-zA-Z_]\\w*)|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state START');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r1_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex2 ()
Definition at line 191 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 0,
 4 => 0,
 5 => 0,
 6 => 0,
 7 => 0,
 8 => 0,
 9 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G([ \t\r]+)|\G(\\d+\\.\\d+(?=[ \t\r]*[\n#;]))|\G(\\d+(?=[ \t\r]*[\n#;]))|\G(\"\"\")|\G('[^'\\\\]*(?:\\\\.[^'\\\\]*)*'(?=[ \t\r]*[\n#;]))|\G(\"[^\"\\\\]*(?:\\\\.[^\"\\\\]*)*\"(?=[ \t\r]*[\n#;]))|\G([a-zA-Z]+(?=[ \t\r]*[\n#;]))|\G([^\n]+?(?=[ \t\r]*\n))|\G(\n)/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state VALUE');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r2_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex3 ()
Definition at line 329 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G([^\n]+?(?=[ \t\r]*\n))/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state NAKED_STRING_VALUE');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r3_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex4 ()
Definition at line 397 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G([ \t\r]+)|\G([^\n]+?(?=[ \t\r]*\n))|\G(\n)/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state COMMENT');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r4_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex5 ()
Definition at line 479 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(\\.)|\G(.*?(?=[\.=[\]\r\n]))/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state SECTION');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r5_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex6 ()
Definition at line 554 of file smarty_internal_configfilelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(\"\"\"(?=[ \t\r]*[\n#;]))|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state TRIPPLE');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r6_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yypopstate ()
Definition at line 61 of file smarty_internal_configfilelexer.php.
Referenced by yy_r2_2(), yy_r2_3(), yy_r2_5(), yy_r2_6(), yy_r2_7(), yy_r2_8(), yy_r2_9(), yy_r3_1(), yy_r4_3(), yy_r5_2(), and yy_r6_1().
 {
 $this->_yy_state = array_pop($this->_yy_stack);
 }
yypushstate ($state)
Definition at line 55 of file smarty_internal_configfilelexer.php.
References $state.
Referenced by yy_r1_1(), yy_r1_2(), yy_r1_4(), yy_r2_4(), yy_r2_7(), and yy_r6_1().
 {
 array_push($this->_yy_stack, $this->_yy_state);
 $this->_yy_state = $state;
 }
Field Documentation
$_yy_stack = array() private
Definition at line 48 of file smarty_internal_configfilelexer.php.
$_yy_state = 1 private
Definition at line 47 of file smarty_internal_configfilelexer.php.
$counter
Definition at line 17 of file smarty_internal_configfilelexer.php.
$data
Definition at line 16 of file smarty_internal_configfilelexer.php.
Referenced by __construct().
$line
Definition at line 21 of file smarty_internal_configfilelexer.php.
$node
Definition at line 20 of file smarty_internal_configfilelexer.php.
$smarty_token_names
Initial value:
= array(
 )
Definition at line 23 of file smarty_internal_configfilelexer.php.
$state = 1 private
Definition at line 22 of file smarty_internal_configfilelexer.php.
Referenced by yybegin(), and yypushstate().
$token
Definition at line 18 of file smarty_internal_configfilelexer.php.
$value
Definition at line 19 of file smarty_internal_configfilelexer.php.
const COMMENT = 4
Definition at line 457 of file smarty_internal_configfilelexer.php.
const NAKED_STRING_VALUE = 3
Definition at line 387 of file smarty_internal_configfilelexer.php.
const SECTION = 5
Definition at line 538 of file smarty_internal_configfilelexer.php.
const START = 1
Definition at line 137 of file smarty_internal_configfilelexer.php.
const TRIPPLE = 6
Definition at line 613 of file smarty_internal_configfilelexer.php.
const VALUE = 2
Definition at line 257 of file smarty_internal_configfilelexer.php.
The documentation for this class was generated from the following file:
smarty_internal_configfilelexer.php