oSocial: varGetter Class Reference
varGetter Class Reference
Public Member Functions
__construct ()
getSiteLang ()
formatGendersForSelect ()
getUserID ()
getUserAccessLevel ()
Private Member Functions
getGenders ()
validateLoginState ()
Private Attributes
$db = null
$core = null
$error = null
$siteLang = null
Detailed Description
Definition at line 10 of file class.varGetter.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 34 of file class.varGetter.php.
References $dbInstance, database\getInstance(), and getSiteLang().
 {
if (is_null($this->db)) {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 }
if (is_null($this->core)) {
 $this->core = new coreFunctions();
 }
if (is_null($this->error)) {
 $this->error = new errorHandler();
 }
 $this->siteLang = $this->getSiteLang();
 }
Member Function Documentation
formatGendersForSelect ()
Formázza a nemeket a regisztrációs űrlap részére
Returns
bool|string
Definition at line 96 of file class.varGetter.php.
References $siteLang, and getGenders().
 {
 $data = $this->getGenders();
if (!is_bool($data) OR !is_null($data)) {
 $nameKey = 'name_' . $this->siteLang;
 $r = null;
foreach ($data as $row) {
 $r[] = $row['id'] . '||' . $row[$nameKey];
 }
 $r = implode('|;|', $r);
return $r;
 } else {
return false;
 }
 }
getGenders () private
Lekérdezi és tömbként visszaadja a nemeket
Tömb ha jó|null ha nincs|false ha valami nem jött össze
Returns
array|bool|null
Definition at line 64 of file class.varGetter.php.
References $siteLang.
Referenced by formatGendersForSelect().
 {
 $colName = 'name_' . $this->siteLang;
 $query = "SELECT `id`, `$colName` FROM _gender";
if ($result = $this->db->query($query)) {
 $r = null;
while ($row = $result->fetch()) {
 $r[] = $row;
 }
return $r;
 } else {
 $this->error->queryError();
return false;
 }
 }
getSiteLang ()
Definition at line 52 of file class.varGetter.php.
References $_SESSION.
Referenced by __construct().
 {
return $this->core->cleanVar($_SESSION['lang']);
 }
getUserAccessLevel ()
Aktuális felhasználó hozzáférési szintjének beszerzése
Returns
bool|int
Definition at line 179 of file class.varGetter.php.
References $_SESSION, $user, and validateLoginState().
 {
if ($this->validateLoginState())
                {
$user = $_SESSION['user'];
 $pass = $_SESSION['pass'];
 $query = "SELECT user_details.userLevel AS level FROM user_base LEFT JOIN user_details ON user_details.uid=user_base.id WHERE `userName`='$user' AND `userPass`='$pass' AND userActive='1'";
if ($result = $this->db->query($query)) {
if ($result->rowCount() == 1) {
 $uid = $result->fetch();
return $uid['level'];
 } else {
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 } else {
return false;
 }
 }
getUserID ()
Aktuális felhasználó azonosítójának beszerzése
Returns
bool|int
Definition at line 149 of file class.varGetter.php.
References $_SESSION, $user, and validateLoginState().
 {
if ($this->validateLoginState())
                {
$user = $_SESSION['user'];
 $pass = $_SESSION['pass'];
 $query = "SELECT user_base.id AS id FROM user_base LEFT JOIN user_details ON user_details.uid=user_base.id WHERE `userName`='$user' AND `userPass`='$pass' AND userActive='1'";
if ($result = $this->db->query($query)) {
if ($result->rowCount() == 1) {
 $uid = $result->fetch();
return $uid['id'];
 } else {
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 } else {
return false;
 }
 }
validateLoginState () private
A $_SESSION-ben található felhasználó adatok hitelesítése, ha van mit hitelesíteni
Returns
bool
Definition at line 120 of file class.varGetter.php.
References $_SESSION, and $user.
Referenced by getUserAccessLevel(), and getUserID().
 {
if (isset($_SESSION['logged']) AND is_bool($_SESSION['logged'])) {
$user = $_SESSION['user'];
 $pass = $_SESSION['pass'];
 $query = "SELECT user_base.id AS id FROM user_base LEFT JOIN user_details ON user_details.uid=user_base.id WHERE `userName`='$user' AND `userPass`='$pass' AND userActive='1'";
if ($result = $this->db->query($query)) {
if ($result->rowCount() == 1) {
return true;
 } else {
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 } else {
return false;
 }
 }
Field Documentation
$core = null private
Definition at line 24 of file class.varGetter.php.
$db = null private
Definition at line 17 of file class.varGetter.php.
$error = null private
Definition at line 26 of file class.varGetter.php.
$siteLang = null private
Szükséges osztályok betöltése
Definition at line 32 of file class.varGetter.php.
Referenced by formatGendersForSelect(), and getGenders().
The documentation for this class was generated from the following file:
class.varGetter.php