oSocial: overseer Class Reference
overseer Class Reference
Public Member Functions
__construct ()
setSiteLang ($lang= 'hu')
invoke ()
Private Member Functions
initSmarty ()
setSmartyGlobalElements ()
doLogin ()
displayDefaultContent ()
switchLang ()
control ()
Private Attributes
$auth = null
$error = null
$smarty = null
$core = null
$docRoot = null
$menu = null
$form = null
$var = null
$admin = null
$userProfile = null
$friends = null
$connector = null
$home = null
$messages = null
Detailed Description
Kontroller osztály
Ez fűz össze mindent ami még nincs összefűzve
Definition at line 15 of file control.overseer.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 32 of file control.overseer.php.
References $_SESSION, initSmarty(), setSiteLang(), and setSmartyGlobalElements().
 {
//Környezet beállításai
 ini_set("default_charset", "utf-8");
 date_default_timezone_set('Europe/Budapest');
 $this->docRoot = $_SERVER["DOCUMENT_ROOT"]
                . '/';
//szükséges osztályok
 $this->error = new errorHandler();
 $this->core = new coreFunctions();
if (isset($_SESSION['lang'])) {
 $this->setSiteLang($this->core->cleanVar($_SESSION['lang']));
 } else {
 $this->setSiteLang();
 }
 $this->auth = new auth();
 $this->menu = new menuHandler();
 $this->form = new form();
 $this->admin = new adminPanel();
 $this->userProfile = new userProfile();
 $this->friends = new offerFriend();
 $this->connector = new socialConnector();
 $this->home = new homeStream();
 $this->var = new varGetter();
 $this->messages = new messenger();
// A Smarty legyen mindig az utolsó
 $this->smarty = new Smarty();
 $this->initSmarty();
 $this->setSmartyGlobalElements();
 }
Member Function Documentation
control () private
Definition at line 171 of file control.overseer.php.
References $messages, auth\checkLoginSource(), auth\destroyEverything(), displayDefaultContent(), doLogin(), invoke(), userProfile\renderCurrentUserProfile(), and userProfile\renderUserProfile().
Referenced by doLogin(), and switchLang().
 {
//var_dump($this->auth->checkLoginSource());
if ($this->auth->checkLoginSource()) {
 $this->smarty->assign('sideMenu', $this->menu->renderMainMenu());
$messages
                = $this->home->renderWaitingMessage();
if (!isset($_GET['mode']))
                {
$messages
                .= $this->home->getGlobalMessages();
 }
 $this->smarty->assign('messages', $messages);
if (isset($_GET['mode']))
                {
 $mode = $this->core->cleanVar($_GET['mode']);
// TODO: jobb megoldást találni, mert így elég nehéz bővíteni a nyelvek számát
// 1 variáció lehet egy $url[$langVar][$mode] tömbös változat
// még 1 variáció lehet adatbázis támogatásával működő osztály is...
if ($mode == 'logout' OR $mode == 'kijelentkezes')
                {
 $this->auth->destroyEverything();
 $this->invoke();
 } elseif ($mode == 'admin') {
if (isset($_GET['var1']))
                {
switch ($_GET['var1']) {
case 'activate':
 $activate = true;
break;
case 'ban':
 $activate = false;
break;
default:
 $activate = null;
break;
 }
 $this->admin->processUser($activate, $_GET['var2']);
 }
 $this->smarty->assign('content', $this->admin->renderRegistrantsToProcess());
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'profilom' OR $mode ==
                'myprofile') {
 $this->smarty->assign('content', $this->userProfile->renderCurrentUserProfile());
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'profil' OR $mode == 'profile') {
// Szükséges lehet megvizsgálni, hogy a $_GET['var1'] létezik -e
 $uid = $this->core->cleanVar($_GET['var1']);
 $this->smarty->assign('content', $this->userProfile->renderUserProfile($uid));
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'kapcsolataim' OR $mode ==
                'connections') {
 $this->smarty->assign('content', $this->friends->renderFriendList());
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'connect' OR $mode == 'block' OR $mode == 'want') {
//jobban is ki lehetne dolgozni, több feltétel szűréssel a biztosabb működésért
if ($mode == 'connect')
                {
 $this->connector->setRelationTo($_GET['var1'], 1);
 } elseif ($mode == 'block') {
 $this->connector->setRelationTo($_GET['var1'], -1);
 } else {
 $this->connector->setRelationTo($_GET['var1'], 0);
 }
 $this->smarty->assign('content', $this->friends->renderFriendList());
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'users' OR $mode == 'felhasznalok') {
 $this->smarty->assign('content', $this->friends->renderUserList());
 $this->smarty->display('pageDefault.tpl');
 } elseif ($mode == 'uzeneteim' OR $mode ==
                'messages') {
if (isset($_POST['submit-email']))
                {
 $this->messages->processMessage();
 }
 $this->smarty->assign('content', $this->messages->renderMessages());
 $this->smarty->display('pageDefault.tpl');
 } else {
 }
 } else {
 $this->displayDefaultContent();
 }
 } else {
if (isset($_GET['mode']))
                {
 $mode = $this->core->cleanVar($_GET['mode']);
// TODO: jobb megoldást találni, mert így elég nehéz bővíteni a nyelvek számát
if ($mode == 'logout' OR $mode == 'kijelentkezes')
                {
 $this->smarty->display('logout.tpl');
 } else {
 }
 } else {
 $this->doLogin();
 }
 }
 }
displayDefaultContent () private
Alapértelmezett tartalom megjelenítése
Definition at line 156 of file control.overseer.php.
Referenced by control().
 {
 $this->smarty->display('pageDefault.tpl');
 }
doLogin () private
A nyitólapi regsiztráció és bejelentkezés kelelése
Definition at line 131 of file control.overseer.php.
References control(), auth\doLogin(), auth\doRegister(), invoke(), auth\loginForm(), and auth\registerForm().
Referenced by control().
 {
if (isset($_POST['submit-login']))
                {
 $this->auth->doLogin();
 $this->invoke();
 } elseif (isset($_POST['submit-register'])) {
if ($this->auth->doRegister()) {
 $this->smarty->display('regThankYou.tpl');
 } else {
 $this->control();
 }
 } else {
 $this->smarty->assign('loginForm',
                $this->auth->loginForm());
 $this->smarty->assign('registerForm',
                $this->auth->registerForm());
 $this->smarty->display('pageIndex.tpl');
 }
 }
initSmarty () private
Smart alap konfigurációja
Definition at line 98 of file control.overseer.php.
Referenced by __construct().
 {
 $this->smarty->setTemplateDir($this->core->cleanPath($this->docRoot .
                '/templates'));
 $this->smarty->setCompileDir($this->core->cleanPath($this->docRoot . '/smarty/templates_c'));
 $this->smarty->setConfigDir($this->core->cleanPath($this->docRoot . '/smarty/config'));
 $this->smarty->setCacheDir($this->core->cleanPath($this->docRoot . '/cache/smarty'));
 }
invoke ()
Definition at line 289 of file control.overseer.php.
References switchLang().
Referenced by control(), and doLogin().
 {
 $this->switchLang();
 }
setSiteLang ($lang = 'hu')
Az oldal nyelvének beállítása
Parameters
string $lang
Definition at line 78 of file control.overseer.php.
References $_SESSION.
Referenced by __construct(), and switchLang().
 {
// Set conditions for gettext
 putenv("LANG=$lang");
 setlocale(LC_ALL, $lang);
 $domain = 'site';
 bindtextdomain($domain, $this->core->cleanPath($this->docRoot . '/locale'));
 textdomain($domain);
$_SESSION['lang'] = $this->core->cleanVar($lang);
 }
setSmartyGlobalElements () private
Smarty elemek alapértelmezése, amire szükséges lehet
Definition at line 110 of file control.overseer.php.
Referenced by __construct().
 {
//general elements
 $this->smarty->assign('siteLang', $this->var->getSiteLang());
 $this->smarty->assign('siteTitle',
                gettext('oSocial'));
 $this->smarty->assign('pageMetaDesc',
                gettext('FALLBACK_META_DESC'));
 $this->smarty->assign('pageMetaTags',
                gettext('FALLBACK_META_TAGS'));
 $this->smarty->assign('sideMenu', null);
 $this->smarty->assign('quickSearch',
                gettext('QUICKSEARCH'));
 $this->smarty->assign('placeForAds',
                gettext("TITLE_PLACE_FOR_ADS"));
 $this->smarty->assign('emailPlace',
                gettext('PLACEHOLDER_EMAIL'));
 $this->smarty->assign('userMenuName',
                gettext('TITLE_USER_MENU'));
 $this->smarty->assign('messages', null);
 $this->smarty->assign('content', null);
//$this->smarty->assign('',gettext(''));
 }
switchLang () private
Definition at line 161 of file control.overseer.php.
References control(), and setSiteLang().
Referenced by invoke().
 {
// TODO: a nyelvváltás "lag"-ját meg kell oldani!
if (isset($_GET['setlang']))
                {
 $this->setSiteLang($_GET['setlang']);
 header('Location: ' . $_SERVER['HTTP_REFERER']);
 }
 $this->control();
 }
Field Documentation
$admin = null private
Definition at line 25 of file control.overseer.php.
$auth = null private
Definition at line 17 of file control.overseer.php.
$connector = null private
Definition at line 28 of file control.overseer.php.
$core = null private
Definition at line 20 of file control.overseer.php.
$docRoot = null private
Definition at line 21 of file control.overseer.php.
$error = null private
Definition at line 18 of file control.overseer.php.
$form = null private
Definition at line 23 of file control.overseer.php.
$friends = null private
Definition at line 27 of file control.overseer.php.
$home = null private
Definition at line 29 of file control.overseer.php.
$menu = null private
Definition at line 22 of file control.overseer.php.
$messages = null private
Definition at line 30 of file control.overseer.php.
Referenced by control().
$smarty = null private
Definition at line 19 of file control.overseer.php.
$userProfile = null private
Definition at line 26 of file control.overseer.php.
$var = null private
Definition at line 24 of file control.overseer.php.
The documentation for this class was generated from the following file:
control.overseer.php