oSocial: Smarty_Resource Class Reference
Smarty_Resource Class Reference
Public Member Functions
getContent (Smarty_Template_Source $source)
populate (Smarty_Template_Source $source, Smarty_Internal_Template $_template=null)
populateTimestamp (Smarty_Template_Source $source)
populateCompiledFilepath (Smarty_Template_Compiled $compiled, Smarty_Internal_Template $_template)
Static Public Member Functions
static load (Smarty $smarty, $type)
static getUniqueTemplateName ($smarty, $template_resource)
static source (Smarty_Internal_Template $_template=null, Smarty $smarty=null, $template_resource=null)
static config (Smarty_Internal_Config $_config)
Data Fields
$compiler_class = 'Smarty_Internal_SmartyTemplateCompiler'
$template_lexer_class = 'Smarty_Internal_Templatelexer'
$template_parser_class = 'Smarty_Internal_Templateparser'
Static Public Attributes
static $sources = array()
static $compileds = array()
static $resources = array()
Protected Member Functions
buildUniqueResourceName (Smarty $smarty, $resource_name)
normalizePath ($_path, $ds=true)
buildFilepath (Smarty_Template_Source $source, Smarty_Internal_Template $_template=null)
fileExists (Smarty_Template_Source $source, $file)
getBasename (Smarty_Template_Source $source)
Static Protected Member Functions
static parseResourceName ($resource_name, $default_resource, &$name, &$type)
Static Protected Attributes
static $sysplugins
Detailed Description
Definition at line 18 of file smarty_resource.php.
Member Function Documentation
buildFilepath (Smarty_Template_Source $source, Smarty_Internal_Template $_template = null) protected
build template filepath by traversing the template_dir array
Parameters
Smarty_Template_Source $source source object
Smarty_Internal_Template $_template template object
Returns
string fully qualified filepath
Exceptions
SmartyException if default template handler is registered but not callable
Definition at line 202 of file smarty_resource.php.
References fileExists(), Smarty_Internal_Get_Include_Path\getIncludePath(), and normalizePath().
Referenced by Smarty_Internal_Resource_File\populate(), and Smarty_Internal_Resource_PHP\populate().
 {
 $file = $source->name;
if ($source instanceof Smarty_Config_Source)
                {
 $_directories = $source->smarty->getConfigDir();
 $_default_handler = $source->smarty->default_config_handler_func;
 } else {
 $_directories = $source->smarty->getTemplateDir();
 $_default_handler = $source->smarty->default_template_handler_func;
 }
// go relative to a given template?
 $_file_is_dotted = $file[0] == '.' &&
                ($file[1] == '.' || $file[1] == '/'
                || $file[1] == "\\");
if ($_template && $_template->parent
                instanceof Smarty_Internal_Template
                && $_file_is_dotted) {
if ($_template->parent->source->type != 'file' && $_template->parent->source->type !=
                'extends' && !$_template->parent->allow_relative_path)
                {
throw new SmartyException("Template '{$file}' cannot be relative to template of resource type '{$_template->parent->source->type}'");
 }
 $file = dirname($_template->parent->source->filepath) . DS . $file;
 $_file_exact_match = true;
if (!preg_match('/^([\/\\\\]|[a-zA-Z]:[\/\\\\])/',
                $file)) {
// the path gained from the parent template is relative to the current working directory
// as expansions (like include_path) have already been done
 $file = getcwd() . DS . $file;
 }
 }
// resolve relative path
if (!preg_match('/^([\/\\\\]|[a-zA-Z]:[\/\\\\])/',
                $file)) {
// don't we all just love windows?
 $_path = str_replace('\\', '/', $file);
 $_path = DS . trim($file, '/');
 $_was_relative = true;
 } else {
// don't we all just love windows?
 $_path = str_replace('\\', '/', $file);
 }
 $_path = $this->normalizePath($_path,
                false);
if (DS != '/') {
// don't we all just love windows?
 $_path = str_replace('/', '\\', $_path);
 }
// revert to relative
if (isset($_was_relative)) {
 $_path = substr($_path, 1);
 }
// this is only required for directories
 $file = rtrim($_path, '/\\');
// files relative to a template only get one shot
if (isset($_file_exact_match)) {
return $this->fileExists($source,
                $file) ? $file : false;
 }
// template_dir index?
if (preg_match('#^\[(?P<key>[^\]]+)\](?P<file>.+)$#',
                $file, $match)) {
 $_directory = null;
// try string indexes
if (isset($_directories[$match['key']])) {
 $_directory = $_directories[$match['key']];
 } else if
                (is_numeric($match['key'])) {
// try numeric index
 $match['key'] = (int)$match['key'];
if (isset($_directories[$match['key']])) {
 $_directory = $_directories[$match['key']];
 } else {
// try at location index
 $keys = array_keys($_directories);
 $_directory = $_directories[$keys[$match['key']]];
 }
 }
if ($_directory) {
 $_file = substr($file, strpos($file, ']') + 1);
 $_filepath = $_directory . $_file;
if ($this->fileExists($source,
                $_filepath)) {
return $_filepath;
 }
 }
 }
 $_stream_resolve_include_path = function_exists('stream_resolve_include_path');
// relative file name?
if (!preg_match('/^([\/\\\\]|[a-zA-Z]:[\/\\\\])/',
                $file)) {
foreach ($_directories as $_directory) {
 $_filepath = $_directory . $file;
if ($this->fileExists($source,
                $_filepath)) {
return $this->normalizePath($_filepath);
 }
if ($source->smarty->use_include_path &&
                !preg_match('/^([\/\\\\]|[a-zA-Z]:[\/\\\\])/', $_directory))
                {
// try PHP include_path
if ($_stream_resolve_include_path) {
 $_filepath = stream_resolve_include_path($_filepath);
 } else {
 $_filepath = Smarty_Internal_Get_Include_Path::getIncludePath($_filepath);
 }
if ($_filepath !== false) {
if ($this->fileExists($source,
                $_filepath)) {
return $this->normalizePath($_filepath);
 }
 }
 }
 }
 }
// try absolute filepath
if ($this->fileExists($source,
                $file)) {
return $file;
 }
// no tpl file found
if ($_default_handler) {
if (!is_callable($_default_handler)) {
if ($source instanceof Smarty_Config_Source) {
throw new SmartyException("Default config handler not callable");
 } else {
throw new SmartyException("Default template handler not callable");
 }
 }
 $_return = call_user_func_array($_default_handler,
 array($source->type, $source->name, &$_content, &$_timestamp, $source->smarty));
if (is_string($_return)) {
 $source->timestamp = @filemtime($_return);
 $source->exists = !!$source->timestamp;
return $_return;
 } elseif ($_return === true) {
 $source->content = $_content;
 $source->timestamp = $_timestamp;
 $source->exists = true;
return $_filepath;
 }
 }
// give up
return false;
 }
buildUniqueResourceName (Smarty $smarty, $resource_name) protected
modify resource_name according to resource handlers specifications
Parameters
Smarty $smarty Smarty instance
string $resource_name resource_name to make unique
Returns
string unique resource name
Definition at line 103 of file smarty_resource.php.
 {
return get_class($this) . '#'
                . $smarty->joined_template_dir . '#' . $resource_name;
 }
static config (Smarty_Internal_Config $_config) static
initialize Config Source Object for given resource
Parameters
Smarty_Internal_Config $_config config object
Returns
Smarty_Config_Source Source Object
Definition at line 543 of file smarty_resource.php.
References load().
Referenced by Smarty_Internal_Config\__get().
 {
static $_incompatible_resources = array('eval' => true, 'string' => true, 'extends' => true, 'php' => true);
 $config_resource = $_config->config_resource;
 $smarty = $_config->smarty;
// parse resource_name
 self::parseResourceName($config_resource, $smarty->default_config_type, $name,
                $type);
// make sure configs are not loaded via anything smarty can't handle
if (isset($_incompatible_resources[$type])) {
throw new SmartyException
                ("Unable to use resource '{$type}' for config");
 }
// load resource handler, identify unique resource name
 $resource = Smarty_Resource::load($smarty,
                $type);
 $unique_resource_name = $resource->buildUniqueResourceName($smarty, $name);
// check runtime cache
 $_cache_key = 'config|' .
                $unique_resource_name;
if (isset(self::$sources[$_cache_key])) {
return self::$sources[$_cache_key];
 }
// create source
 $source = new Smarty_Config_Source($resource,
                $smarty, $config_resource, $type, $name, $unique_resource_name);
 $resource->populate($source, null);
// runtime cache
 self::$sources[$_cache_key] = $source;
return $source;
 }
fileExists (Smarty_Template_Source $source, $file) protected
test is file exists and save timestamp
Parameters
Smarty_Template_Source $source source object
string $file file name
Returns
bool true if file exists
Definition at line 348 of file smarty_resource.php.
Referenced by buildFilepath().
 {
 $source->timestamp = @filemtime($file);
return $source->exists = !!$source->timestamp;
 }
getBasename (Smarty_Template_Source $source) protected
Determine basename for compiled filename
Parameters
Smarty_Template_Source $source source object
Returns
string resource's basename
Definition at line 361 of file smarty_resource.php.
Referenced by populateCompiledFilepath().
 {
return null;
 }
getContent (Smarty_Template_Source $source) abstract
Load template's source into current template object
{
static getUniqueTemplateName ($smarty, $template_resource) static
modify resource_name according to resource handlers specifications
Parameters
Smarty $smarty Smarty instance
string $resource_name resource_name to make unique
Returns
string unique resource name modify template_resource according to resource handlers specifications
Parameters
string $smarty Smarty instance
string $template_resource template_resource to extracate resource handler and name of
Returns
string unique resource name
Definition at line 489 of file smarty_resource.php.
References load().
Referenced by Smarty\createTemplate(), and Smarty_Internal_Template\getSubTemplate().
 {
 self::parseResourceName($template_resource, $smarty->default_resource_type, $name,
                $type);
// TODO: optimize for Smarty's internal resource types
 $resource = Smarty_Resource::load($smarty,
                $type);
return $resource->buildUniqueResourceName($smarty,
                $name);
 }
static load (Smarty $smarty, $type) static
Load Resource Handler
Parameters
Smarty $smarty smarty object
string $type name of the resource
Returns
Smarty_Resource Resource Handler
Definition at line 373 of file smarty_resource.php.
References Smarty\loadPlugin(), and Smarty_Internal_TemplateBase\registerResource().
Referenced by config(), getUniqueTemplateName(), and source().
 {
// try smarty's cache
if (isset($smarty->_resource_handlers[$type])) {
return $smarty->_resource_handlers[$type];
 }
// try registered resource
if (isset($smarty->registered_resources[$type])) {
if ($smarty->registered_resources[$type] instanceof Smarty_Resource) {
 $smarty->_resource_handlers[$type] = $smarty->registered_resources[$type];
// note registered to smarty is not kept unique!
return $smarty->_resource_handlers[$type];
 }
if (!isset(self::$resources['registered']))
                {
 self::$resources['registered'] = new Smarty_Internal_Resource_Registered();
 }
if (!isset($smarty->_resource_handlers[$type])) {
 $smarty->_resource_handlers[$type] = self::$resources['registered'];
 }
return $smarty->_resource_handlers[$type];
 }
// try sysplugins dir
if (isset(self::$sysplugins[$type])) {
if (!isset(self::$resources[$type])) {
 $_resource_class = 'Smarty_Internal_Resource_'
                . ucfirst($type);
 self::$resources[$type] = new $_resource_class();
 }
return $smarty->_resource_handlers[$type] =
                self::$resources[$type];
 }
// try plugins dir
 $_resource_class = 'Smarty_Resource_' .
                ucfirst($type);
if ($smarty->loadPlugin($_resource_class))
                {
if (isset(self::$resources[$type])) {
return $smarty->_resource_handlers[$type] =
                self::$resources[$type];
 }
if (class_exists($_resource_class, false))
                {
 self::$resources[$type] = new $_resource_class();
return $smarty->_resource_handlers[$type] =
                self::$resources[$type];
 } else {
 $smarty->registerResource($type,
                array(
"smarty_resource_{$type}_source",
"smarty_resource_{$type}_timestamp",
"smarty_resource_{$type}_secure",
"smarty_resource_{$type}_trusted"
 ));
// give it another try, now that the resource is registered properly
return self::load($smarty, $type);
 }
 }
// try streams
 $_known_stream = stream_get_wrappers();
if (in_array($type, $_known_stream)) {
// is known stream
if (is_object($smarty->security_policy)) {
 $smarty->security_policy->isTrustedStream($type);
 }
if (!isset(self::$resources['stream']))
                {
 self::$resources['stream'] = new Smarty_Internal_Resource_Stream();
 }
return $smarty->_resource_handlers[$type] =
                self::$resources['stream'];
 }
// TODO: try default_(template|config)_handler
// give up
throw new SmartyException("Unkown resource type '{$type}'");
 }
normalizePath ($_path, $ds = true) protected
Normalize Paths "foo/../bar" to "bar"
Parameters
string $_path path to normalize
boolean $ds respect windows directory separator
Returns
string normalized path
Definition at line 156 of file smarty_resource.php.
Referenced by buildFilepath().
 {
if ($ds) {
// don't we all just love windows?
 $_path = str_replace('\\', '/', $_path);
 }
 $offset = 0;
// resolve simples
 $_path = preg_replace('#(/\./(\./)*)|/{2,}#',
                '/', $_path);
// resolve parents
while (true) {
 $_parent = strpos($_path, '/../', $offset);
if (!$_parent) {
break;
 } else if
                ($_path[$_parent - 1] === '.') {
 $offset = $_parent + 3;
continue;
 }
 $_pos = strrpos($_path, '/', $_parent -
                strlen($_path) - 1);
if ($_pos === false) {
// don't we all just love windows?
 $_pos = $_parent;
 }
 $_path = substr_replace($_path, '', $_pos,
                $_parent + 3 - $_pos);
 }
if ($ds && DS != '/')
                {
// don't we all just love windows?
 $_path = str_replace('/', '\\', $_path);
 }
return $_path;
 }
static parseResourceName ($resource_name, $default_resource, & $name, & $type) static protected
extract resource_type and resource_name from template_resource and config_resource
Note
"C:/foo.tpl" was forced to file resource up till Smarty 3.1.3 (including).
Parameters
string $resource_name template_resource or config_resource to parse
string $default_resource the default resource_type defined in $smarty
string &$name the parsed resource name
string &$type the parsed resource type
Returns
void
Definition at line 459 of file smarty_resource.php.
 {
 $parts = explode(':', $resource_name, 2);
if (!isset($parts[1]) || !isset($parts[0][1])) {
// no resource given, use default
// or single character before the colon is not a resource type, but part of the filepath
 $type = $default_resource;
 $name = $resource_name;
 } else {
 $type = $parts[0];
 $name = $parts[1];
 }
 }
populate (Smarty_Template_Source $source, Smarty_Internal_Template $_template = null) abstract
populate Source Object with meta data from Resource
Parameters
Smarty_Template_Source $source source object
Smarty_Internal_Template $_template template object
populateCompiledFilepath (Smarty_Template_Compiled $compiled, Smarty_Internal_Template $_template)
populate Compiled Object with compiled filepath
Parameters
Smarty_Template_Compiled $compiled compiled object
Smarty_Internal_Template $_template template object
Definition at line 114 of file smarty_resource.php.
References getBasename().
 {
 $_compile_id = isset($_template->compile_id) ? preg_replace('![^\w\|]+!', '_',
                $_template->compile_id) : null;
 $_filepath = $compiled->source->uid;
// if use_sub_dirs, break file into directories
if ($_template->smarty->use_sub_dirs) {
 $_filepath = substr($_filepath, 0, 2) . DS
 . substr($_filepath, 2, 2) . DS
 . substr($_filepath, 4, 2) . DS
 . $_filepath;
 }
 $_compile_dir_sep = $_template->smarty->use_sub_dirs ? DS : '^';
if (isset($_compile_id)) {
 $_filepath = $_compile_id . $_compile_dir_sep . $_filepath;
 }
// caching token
if ($_template->caching) {
 $_cache = '.cache';
 } else {
 $_cache = '';
 }
 $_compile_dir = $_template->smarty->getCompileDir();
// set basename if not specified
 $_basename = $this->getBasename($compiled->source);
if ($_basename === null) {
 $_basename = basename(preg_replace('![^\w\/]+!', '_',
                $compiled->source->name));
 }
// separate (optional) basename by dot
if ($_basename) {
 $_basename = '.' . $_basename;
 }
 $compiled->filepath = $_compile_dir . $_filepath . '.'
                . $compiled->source->type . $_basename . $_cache . '.php';
 }
populateTimestamp (Smarty_Template_Source $source)
populate Source Object with timestamp and exists from Resource
Parameters
Smarty_Template_Source $source source object
Definition at line 90 of file smarty_resource.php.
 {
// intentionally left blank
 }
static source (Smarty_Internal_Template $_template = null, Smarty $smarty = null, $template_resource = null) static
initialize Source Object for given resource
Either [$_template] or [$smarty, $template_resource] must be specified
Parameters
Smarty_Internal_Template $_template template object
Smarty $smarty smarty object
string $template_resource resource identifier
Returns
Smarty_Template_Source Source Object
Definition at line 507 of file smarty_resource.php.
References load().
Referenced by Smarty_Internal_Resource_Extends\populate().
 {
if ($_template) {
 $smarty = $_template->smarty;
 $template_resource = $_template->template_resource;
 }
// parse resource_name, load resource handler, identify unique resource name
 self::parseResourceName($template_resource, $smarty->default_resource_type, $name,
                $type);
 $resource = Smarty_Resource::load($smarty,
                $type);
 $unique_resource_name = $resource->buildUniqueResourceName($smarty, $name);
// check runtime cache
 $_cache_key = 'template|' .
                $unique_resource_name;
if ($smarty->compile_id) {
 $_cache_key .= '|' . $smarty->compile_id;
 }
if (isset(self::$sources[$_cache_key])) {
return self::$sources[$_cache_key];
 }
// create source
 $source = new Smarty_Template_Source($resource,
                $smarty, $template_resource, $type, $name, $unique_resource_name);
 $resource->populate($source, $_template);
// runtime cache
 self::$sources[$_cache_key] = $source;
return $source;
 }
Field Documentation
$compileds = array() static
Definition at line 29 of file smarty_resource.php.
Referenced by Smarty_Internal_Utility\clearCompiledTemplate(), and Smarty_Template_Source\getCompiled().
$compiler_class = 'Smarty_Internal_SmartyTemplateCompiler'
Definition at line 52 of file smarty_resource.php.
$resources = array() static
Definition at line 34 of file smarty_resource.php.
$sources = array() static
Definition at line 24 of file smarty_resource.php.
Referenced by Smarty_Internal_Utility\clearCompiledTemplate(), and Smarty_Internal_Resource_Extends\populate().
$sysplugins static protected
Initial value:
= array(
'file' => true,
'string' => true,
'extends' => true,
'stream' => true,
'eval' => true,
'php' => true
 )
Definition at line 39 of file smarty_resource.php.
$template_lexer_class = 'Smarty_Internal_Templatelexer'
Definition at line 58 of file smarty_resource.php.
$template_parser_class = 'Smarty_Internal_Templateparser'
Definition at line 64 of file smarty_resource.php.
The documentation for this class was generated from the following file:
smarty_resource.php