oSocial: Smarty_Internal_TemplateBase Class Reference
Smarty_Internal_TemplateBase Class Reference
Public Member Functions
fetch ($template=null, $cache_id=null, $compile_id=null, $parent=null, $display=false, $merge_tpl_vars=true, $no_output_filter=false)
display ($template=null, $cache_id=null, $compile_id=null, $parent=null)
isCached ($template=null, $cache_id=null, $compile_id=null, $parent=null)
createData ($parent=null)
registerPlugin ($type, $tag, $callback, $cacheable=true, $cache_attr=null)
unregisterPlugin ($type, $tag)
registerResource ($type, $callback)
unregisterResource ($type)
registerCacheResource ($type, Smarty_CacheResource $callback)
unregisterCacheResource ($type)
registerObject ($object_name, $object_impl, $allowed=array(), $smarty_args=true, $block_methods=array())
getRegisteredObject ($name)
unregisterObject ($name)
registerClass ($class_name, $class_impl)
registerDefaultPluginHandler ($callback)
registerDefaultTemplateHandler ($callback)
registerDefaultConfigHandler ($callback)
registerFilter ($type, $callback)
unregisterFilter ($type, $callback)
_get_filter_name ($function_name)
loadFilter ($type, $name)
unloadFilter ($type, $name)
__call ($name, $args)
Public Member Functions inherited from Smarty_Internal_Data
assign ($tpl_var, $value=null, $nocache=false)
assignGlobal ($varname, $value=null, $nocache=false)
assignByRef ($tpl_var, &$value, $nocache=false)
append ($tpl_var, $value=null, $merge=false, $nocache=false)
appendByRef ($tpl_var, &$value, $merge=false)
getTemplateVars ($varname=null, $_ptr=null, $search_parents=true)
clearAssign ($tpl_var)
clearAllAssign ()
configLoad ($config_file, $sections=null)
getVariable ($variable, $_ptr=null, $search_parents=true, $error_enable=true)
getConfigVariable ($variable, $error_enable=true)
getStreamVariable ($variable)
getConfigVars ($varname=null, $search_parents=true)
clearConfig ($varname=null)
Private Member Functions
replaceCamelcase ($match)
Additional Inherited Members
Data Fields inherited from Smarty_Internal_Data
$template_class = 'Smarty_Internal_Template'
$tpl_vars = array()
$parent = null
$config_vars = array()
Detailed Description
Definition at line 18 of file smarty_internal_templatebase.php.
Member Function Documentation
__call ($name, $args)
Handle unknown class methods
Parameters
string $name unknown method-name
array $args argument array
Definition at line 759 of file smarty_internal_templatebase.php.
 {
static $_prefixes = array('set'
                => true, 'get' => true);
static $_resolved_property_name = array();
static $_resolved_property_source = array();
// method of Smarty object?
if (method_exists($this->smarty, $name)) {
return call_user_func_array(array($this->smarty,
                $name), $args);
 }
// see if this is a set/get for a property
 $first3 = strtolower(substr($name, 0, 3));
if (isset($_prefixes[$first3]) && isset($name[3])
                && $name[3] !== '_') {
if (isset($_resolved_property_name[$name])) {
 $property_name = $_resolved_property_name[$name];
 } else {
// try to keep case correct for future PHP 6.0 case-sensitive class methods
// lcfirst() not available < PHP 5.3.0, so improvise
 $property_name = strtolower(substr($name, 3, 1)) . substr($name, 4);
// convert camel case to underscored name
 $property_name = preg_replace_callback('/([A-Z])/', array($this, 'replaceCamelcase'),
                $property_name);
 $_resolved_property_name[$name] = $property_name;
 }
if (isset($_resolved_property_source[$property_name])) {
 $_is_this = $_resolved_property_source[$property_name];
 } else {
 $_is_this = null;
if (property_exists($this, $property_name)) {
 $_is_this = true;
 } else if
                (property_exists($this->smarty, $property_name)) {
 $_is_this = false;
 }
 $_resolved_property_source[$property_name] = $_is_this;
 }
if ($_is_this) {
if ($first3 == 'get')
return $this->$property_name;
else
return $this->$property_name = $args[0];
 } else if ($_is_this
                === false) {
if ($first3 == 'get')
return $this->smarty->$property_name;
else
return $this->smarty->$property_name = $args[0];
 } else {
throw new SmartyException("property '$property_name' does not exist.");
return false;
 }
 }
if ($name == 'Smarty') {
throw new SmartyException("PHP5 requires you to call __construct() instead of Smarty()");
 }
// must be unknown
throw new SmartyException("Call of unknown method '$name'.");
 }
_get_filter_name ($function_name)
Return internal filter name
Parameters
callback $function_name
Returns
string internal filter name
Definition at line 691 of file smarty_internal_templatebase.php.
Referenced by registerFilter(), and unregisterFilter().
 {
if (is_array($function_name)) {
 $_class_name = (is_object($function_name[0]) ?
 get_class($function_name[0]) : $function_name[0]);
return $_class_name . '_'
                . $function_name[1];
 } else {
return $function_name;
 }
 }
createData ($parent = null)
creates a data object
Parameters
object $parent next higher level of Smarty variables
Returns
Smarty_Data data object
Definition at line 412 of file smarty_internal_templatebase.php.
References Smarty_Internal_Data\$parent.
 {
return new Smarty_Data($parent, $this);
 }
display ($template = null, $cache_id = null, $compile_id = null, $parent = null)
displays a Smarty template
Parameters
string $template the resource handle of the template file or template object
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
object $parent next higher level of Smarty variables
Definition at line 376 of file smarty_internal_templatebase.php.
References Smarty_Internal_Data\$parent, and fetch().
 {
// display template
 $this->fetch($template,
                $cache_id, $compile_id, $parent,
                true);
 }
fetch ($template = null, $cache_id = null, $compile_id = null, $parent = null, $display = false, $merge_tpl_vars = true, $no_output_filter = false)
fetches a rendered Smarty template
Parameters
string $template the resource handle of the template file or template object
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
object $parent next higher level of Smarty variables
bool $display true: display, false: fetch
bool $merge_tpl_vars if true parent template variables merged in to local scope
bool $no_output_filter if true do not run output filter
Returns
string rendered template output
Definition at line 33 of file smarty_internal_templatebase.php.
References Smarty_Internal_Data\$config_vars, Smarty\$global_tpl_vars, Smarty_Internal_Data\$parent, Smarty_Internal_Data\$template_class, Smarty_Internal_Data\$tpl_vars, Smarty\CACHING_LIFETIME_CURRENT, Smarty\CACHING_LIFETIME_SAVED, Smarty_Internal_Debug\display_debug(), Smarty_Internal_Debug\end_cache(), Smarty_Internal_Debug\end_compile(), Smarty_Internal_Debug\end_render(), Smarty_Internal_Filter_Handler\runFilter(), Smarty_Internal_Debug\start_cache(), Smarty_Internal_Debug\start_compile(), and Smarty_Internal_Debug\start_render().
Referenced by display().
 {
if ($template === null && $this instanceof $this->template_class)
    {
 $template = $this;
 }
if (!empty($cache_id) && is_object($cache_id)) {
$parent =
    $cache_id;
 $cache_id = null;
 }
if ($parent
    === null && ($this instanceof Smarty || is_string($template)))
    {
$parent = $this;
 }
// create template object if necessary
 $_template = ($template instanceof $this->template_class)
 ? $template
 : $this->smarty->createTemplate($template, $cache_id, $compile_id, $parent,
    false);
// if called by Smarty object make sure we use current caching status
if ($this instanceof Smarty) {
 $_template->caching = $this->caching;
 }
// merge all variable scopes into template
if ($merge_tpl_vars) {
// save local variables
 $save_tpl_vars = $_template->tpl_vars;
 $save_config_vars = $_template->config_vars;
 $ptr_array = array($_template);
 $ptr = $_template;
while (isset($ptr->parent)) {
 $ptr_array[] = $ptr = $ptr->parent;
 }
 $ptr_array = array_reverse($ptr_array);
 $parent_ptr = reset($ptr_array);
$tpl_vars =
    $parent_ptr->tpl_vars;
$config_vars
    = $parent_ptr->config_vars;
while ($parent_ptr = next($ptr_array)) {
if (!empty($parent_ptr->tpl_vars)) {
$tpl_vars =
    array_merge($tpl_vars,
    $parent_ptr->tpl_vars);
 }
if (!empty($parent_ptr->config_vars)) {
$config_vars
    = array_merge($config_vars,
    $parent_ptr->config_vars);
 }
 }
if (!empty(Smarty::$global_tpl_vars))
    {
$tpl_vars =
    array_merge(Smarty::$global_tpl_vars,
    $tpl_vars);
 }
 $_template->tpl_vars = $tpl_vars;
 $_template->config_vars = $config_vars;
 }
// dummy local smarty variable
if (!isset($_template->tpl_vars['smarty']))
    {
 $_template->tpl_vars['smarty'] = new
    Smarty_Variable;
 }
if (isset($this->smarty->error_reporting)) {
 $_smarty_old_error_level = error_reporting($this->smarty->error_reporting);
 }
// check URL debugging control
if (!$this->smarty->debugging && $this->smarty->debugging_ctrl
    == 'URL') {
if (isset($_SERVER['QUERY_STRING'])) {
 $_query_string = $_SERVER['QUERY_STRING'];
 } else {
 $_query_string = '';
 }
if (false !== strpos($_query_string,
    $this->smarty->smarty_debug_id)) {
if (false !== strpos($_query_string,
    $this->smarty->smarty_debug_id . '=on')) {
// enable debugging for this browser session
 setcookie('SMARTY_DEBUG', true);
 $this->smarty->debugging = true;
 } elseif (false !== strpos($_query_string, $this->smarty->smarty_debug_id
    . '=off')) {
// disable debugging for this browser session
 setcookie('SMARTY_DEBUG', false);
 $this->smarty->debugging = false;
 } else {
// enable debugging for this page
 $this->smarty->debugging = true;
 }
 } else {
if (isset($_COOKIE['SMARTY_DEBUG'])) {
 $this->smarty->debugging = true;
 }
 }
 }
// must reset merge template date
 $_template->smarty->merged_templates_func = array();
// get rendered template
// disable caching for evaluated code
if ($_template->source->recompiled) {
 $_template->caching = false;
 }
// checks if template exists
if (!$_template->source->exists) {
if ($_template->parent instanceof Smarty_Internal_Template)
    {
 $parent_resource = " in '{$_template->parent->template_resource}'";
 } else {
 $parent_resource = '';
 }
throw new SmartyException("Unable to load template {$_template->source->type} '{$_template->source->name}'{$parent_resource}");
 }
// read from cache or render
if (!($_template->caching == Smarty::CACHING_LIFETIME_CURRENT
    || $_template->caching == Smarty::CACHING_LIFETIME_SAVED)
    || !$_template->cached->valid) {
// render template (not loaded and not in cache)
if (!$_template->source->uncompiled) {
 $_smarty_tpl = $_template;
if ($_template->source->recompiled) {
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_compile($_template);
 }
 $code = $_template->compiler->compileTemplate($_template);
if ($this->smarty->debugging) {
Smarty_Internal_Debug::end_compile($_template);
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_render($_template);
 }
try {
 ob_start();
 eval("?>" . $code);
 unset($code);
 } catch (Exception
    $e) {
 ob_get_clean();
throw $e;
 }
 } else {
if (!$_template->compiled->exists || ($_template->smarty->force_compile
    && !$_template->compiled->isCompiled)) {
 $_template->compileTemplateSource();
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_render($_template);
 }
if (!$_template->compiled->loaded) {
 include($_template->compiled->filepath);
if ($_template->mustCompile) {
// recompile and load again
 $_template->compileTemplateSource();
 include($_template->compiled->filepath);
 }
 $_template->compiled->loaded = true;
 } else {
 $_template->decodeProperties($_template->compiled->_properties, false);
 }
try {
 ob_start();
if (empty($_template->properties['unifunc'])
    || !is_callable($_template->properties['unifunc'])) {
throw new SmartyException("Invalid compiled template for '{$_template->template_resource}'");
 }
 array_unshift($_template->_capture_stack, array());
//
// render compiled template
//
 $_template->properties['unifunc']($_template);
// any unclosed {capture} tags ?
if (isset($_template->_capture_stack[0][0])) {
 $_template->capture_error();
 }
 array_shift($_template->_capture_stack);
 } catch (Exception
    $e) {
 ob_get_clean();
throw $e;
 }
 }
 } else {
if ($_template->source->uncompiled) {
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_render($_template);
 }
try {
 ob_start();
 $_template->source->renderUncompiled($_template);
 } catch (Exception
    $e) {
 ob_get_clean();
throw $e;
 }
 } else {
throw new SmartyException("Resource '$_template->source->type' must have 'renderUncompiled' method");
 }
 }
 $_output = ob_get_clean();
if (!$_template->source->recompiled &&
    empty($_template->properties['file_dependency'][$_template->source->uid]))
    {
 $_template->properties['file_dependency'][$_template->source->uid]
    = array($_template->source->filepath, $_template->source->timestamp, $_template->source->type);
 }
if ($_template->parent instanceof Smarty_Internal_Template)
    {
 $_template->parent->properties['file_dependency'] =
    array_merge($_template->parent->properties['file_dependency'],
    $_template->properties['file_dependency']);
foreach ($_template->required_plugins as $code => $tmp1) {
foreach ($tmp1 as $name => $tmp) {
foreach ($tmp as $type => $data) {
 $_template->parent->required_plugins[$code][$name][$type] = $data;
 }
 }
 }
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::end_render($_template);
 }
// write to cache when nessecary
if (!$_template->source->recompiled && ($_template->caching
    == Smarty::CACHING_LIFETIME_SAVED ||
    $_template->caching == Smarty::CACHING_LIFETIME_CURRENT))
    {
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_cache($_template);
 }
 $_template->properties['has_nocache_code'] = false;
// get text between non-cached items
 $cache_split = preg_split("!/\*%%SmartyNocache:{$_template->properties['nocache_hash']}%%\*\/(.+?)/\*/%%SmartyNocache:{$_template->properties['nocache_hash']}%%\*/!s",
    $_output);
// get non-cached items
 preg_match_all("!/\*%%SmartyNocache:{$_template->properties['nocache_hash']}%%\*\/(.+?)/\*/%%SmartyNocache:{$_template->properties['nocache_hash']}%%\*/!s",
    $_output, $cache_parts);
 $output = '';
// loop over items, stitch back together
foreach ($cache_split as $curr_idx => $curr_split) {
// escape PHP tags in template content
 $output .= preg_replace('/(<%|%>|<\?php|<\?|\?>)/', '<?php echo \'$1\'; ?>',
    $curr_split);
if (isset($cache_parts[0][$curr_idx])) {
 $_template->properties['has_nocache_code'] = true;
// remove nocache tags from cache output
 $output .= preg_replace("!/\*/?%%SmartyNocache:{$_template->properties['nocache_hash']}%%\*/!",
    '', $cache_parts[0][$curr_idx]);
 }
 }
if (!$no_output_filter && !$_template->has_nocache_code
    && (isset($this->smarty->autoload_filters['output']) ||
    isset($this->smarty->registered_filters['output']))) {
 $output = Smarty_Internal_Filter_Handler::runFilter('output', $output, $_template);
 }
// rendering (must be done before writing cache file because of {function} nocache handling)
 $_smarty_tpl = $_template;
try {
 ob_start();
 eval("?>" . $output);
 $_output = ob_get_clean();
 } catch (Exception
    $e) {
 ob_get_clean();
throw $e;
 }
// write cache file content
 $_template->writeCachedContent($output);
if ($this->smarty->debugging) {
Smarty_Internal_Debug::end_cache($_template);
 }
 } else {
// var_dump('renderTemplate', $_template->has_nocache_code, $_template->template_resource, $_template->properties['nocache_hash'], $_template->parent->properties['nocache_hash'], $_output);
if (!empty($_template->properties['nocache_hash'])
    && !empty($_template->parent->properties['nocache_hash']))
    {
// replace nocache_hash
 $_output = str_replace("{$_template->properties['nocache_hash']}",
    $_template->parent->properties['nocache_hash'], $_output);
 $_template->parent->has_nocache_code = $_template->parent->has_nocache_code ||
    $_template->has_nocache_code;
 }
 }
 } else {
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_cache($_template);
 }
try {
 ob_start();
 array_unshift($_template->_capture_stack, array());
//
// render cached template
//
 $_template->properties['unifunc']($_template);
// any unclosed {capture} tags ?
if (isset($_template->_capture_stack[0][0])) {
 $_template->capture_error();
 }
 array_shift($_template->_capture_stack);
 $_output = ob_get_clean();
 } catch (Exception
    $e) {
 ob_get_clean();
throw $e;
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::end_cache($_template);
 }
 }
if ((!$this->caching || $_template->has_nocache_code ||
    $_template->source->recompiled) && !$no_output_filter && (isset($this->smarty->autoload_filters['output']) || isset($this->smarty->registered_filters['output']))) {
 $_output = Smarty_Internal_Filter_Handler::runFilter('output', $_output, $_template);
 }
if (isset($this->error_reporting)) {
 error_reporting($_smarty_old_error_level);
 }
// display or fetch
if ($display) {
if ($this->caching && $this->cache_modified_check) {
 $_isCached = $_template->isCached() && !$_template->has_nocache_code;
 $_last_modified_date = @substr($_SERVER['HTTP_IF_MODIFIED_SINCE'], 0, strpos($_SERVER['HTTP_IF_MODIFIED_SINCE'],
    'GMT') + 3);
if ($_isCached && $_template->cached->timestamp <=
    strtotime($_last_modified_date)) {
switch (PHP_SAPI) {
case 'cgi': // php-cgi < 5.3
case 'cgi-fcgi': // php-cgi >= 5.3
case 'fpm-fcgi': // php-fpm >= 5.3.3
 header('Status: 304 Not Modified');
break;
case 'cli':
if (/* ^phpunit */
 !empty($_SERVER['SMARTY_PHPUNIT_DISABLE_HEADERS']) /* phpunit$ */
 ) {
 $_SERVER['SMARTY_PHPUNIT_HEADERS'][] = '304 Not Modified';
 }
break;
default:
 header($_SERVER['SERVER_PROTOCOL'] . ' 304 Not Modified');
break;
 }
 } else {
switch (PHP_SAPI) {
case 'cli':
if (/* ^phpunit */
 !empty($_SERVER['SMARTY_PHPUNIT_DISABLE_HEADERS']) /* phpunit$ */
 ) {
 $_SERVER['SMARTY_PHPUNIT_HEADERS'][] = 'Last-Modified: ' . gmdate('D, d M Y H:i:s',
    $_template->cached->timestamp) . ' GMT';
 }
break;
default:
 header('Last-Modified: ' . gmdate('D, d M Y H:i:s', $_template->cached->timestamp) . ' GMT');
break;
 }
 echo $_output;
 }
 } else {
 echo $_output;
 }
// debug output
if ($this->smarty->debugging) {
Smarty_Internal_Debug::display_debug($this);
 }
if ($merge_tpl_vars) {
// restore local variables
 $_template->tpl_vars = $save_tpl_vars;
 $_template->config_vars = $save_config_vars;
 }
return;
 } else {
if ($merge_tpl_vars) {
// restore local variables
 $_template->tpl_vars = $save_tpl_vars;
 $_template->config_vars = $save_config_vars;
 }
// return fetched content
return $_output;
 }
 }
getRegisteredObject ($name)
return a reference to a registered object
Parameters
string $name object name
Returns
object
Exceptions
SmartyException if no such object is found
Definition at line 556 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\get_registered_object().
 {
if (!isset($this->smarty->registered_objects[$name]))
                {
throw new SmartyException("'$name' is not a registered object");
 }
if (!is_object($this->smarty->registered_objects[$name][0]))
                {
throw new SmartyException("registered '$name' is not an object");
 }
return $this->smarty->registered_objects[$name][0];
 }
isCached ($template = null, $cache_id = null, $compile_id = null, $parent = null)
test if cache is valid
Parameters
string | object $template the resource handle of the template file or template object
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
object $parent next higher level of Smarty variables
Returns
boolean cache status
Definition at line 391 of file smarty_internal_templatebase.php.
References Smarty_Internal_Data\$parent.
Referenced by SmartyBC\is_cached().
 {
if ($template === null && $this instanceof $this->template_class)
                {
return $this->cached->valid;
 }
if (!($template instanceof $this->template_class)) {
if ($parent
                === null) {
$parent
                = $this;
 }
 $template = $this->smarty->createTemplate($template, $cache_id, $compile_id, $parent, false);
 }
// return cache status of template
return $template->cached->valid;
 }
loadFilter ($type, $name)
load a filter of specified type and name
Parameters
string $type filter type
string $name filter name
Exceptions
SmartyException if filter could not be loaded
Definition at line 709 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\load_filter().
 {
 $_plugin = "smarty_{$type}filter_{$name}";
 $_filter_name = $_plugin;
if ($this->smarty->loadPlugin($_plugin)) {
if (class_exists($_plugin, false)) {
 $_plugin = array($_plugin, 'execute');
 }
if (is_callable($_plugin)) {
 $this->smarty->registered_filters[$type][$_filter_name] = $_plugin;
return true;
 }
 }
throw new SmartyException("{$type}filter \"{$name}\" not callable");
 }
registerCacheResource ($type, Smarty_CacheResource $callback)
Registers a cache resource to cache a template's output
Parameters
string $type name of cache resource type
Smarty_CacheResource $callback instance of Smarty_CacheResource to handle output caching
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 492 of file smarty_internal_templatebase.php.
 {
 $this->smarty->registered_cache_resources[$type] = $callback;
return $this;
 }
registerClass ($class_name, $class_impl)
Registers static classes to be used in templates
Parameters
string $class name of template class
string $class_impl the referenced PHP class to register
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException if $class_impl does not refer to an existing class
Definition at line 590 of file smarty_internal_templatebase.php.
 {
// test if exists
if (!class_exists($class_impl)) {
throw new SmartyException("Undefined class '$class_impl' in register template class");
 }
// register the class
 $this->smarty->registered_classes[$class_name] = $class_impl;
return $this;
 }
registerDefaultConfigHandler ($callback)
Registers a default template handler
Parameters
callable $callback class/method name
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException if $callback is not callable
Definition at line 644 of file smarty_internal_templatebase.php.
 {
if (is_callable($callback)) {
 $this->smarty->default_config_handler_func = $callback;
 } else {
throw new SmartyException("Default config handler '$callback' not callable");
 }
return $this;
 }
registerDefaultPluginHandler ($callback)
Registers a default plugin handler
Parameters
callable $callback class/method name
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException if $callback is not callable
Definition at line 608 of file smarty_internal_templatebase.php.
 {
if (is_callable($callback)) {
 $this->smarty->default_plugin_handler_func = $callback;
 } else {
throw new SmartyException("Default plugin handler '$callback' not callable");
 }
return $this;
 }
registerDefaultTemplateHandler ($callback)
Registers a default template handler
Parameters
callable $callback class/method name
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException if $callback is not callable
Definition at line 626 of file smarty_internal_templatebase.php.
 {
if (is_callable($callback)) {
 $this->smarty->default_template_handler_func = $callback;
 } else {
throw new SmartyException("Default template handler '$callback' not callable");
 }
return $this;
 }
registerFilter ($type, $callback)
Registers a filter function
Parameters
string $type filter type
callback $callback
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 662 of file smarty_internal_templatebase.php.
References _get_filter_name().
Referenced by SmartyBC\register_outputfilter(), SmartyBC\register_postfilter(), and SmartyBC\register_prefilter().
 {
 $this->smarty->registered_filters[$type][$this->_get_filter_name($callback)]
                = $callback;
return $this;
 }
registerObject ($object_name, $object_impl, $allowed = array(), $smarty_args = true, $block_methods = array())
Registers object to be used in templates
Parameters
string $object name of template object
object $object_impl the referenced PHP object to register
array $allowed list of allowed methods (empty = all)
boolean $smarty_args smarty argument format, else traditional
array $block_methods list of block-methods
array $block_functs list of methods that are block format
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException if any of the methods in $allowed or $block_methods are invalid
Definition at line 525 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\register_object().
 {
// test if allowed methodes callable
if (!empty($allowed)) {
foreach ((array)$allowed as $method) {
if (!is_callable(array($object_impl, $method))) {
throw new SmartyException("Undefined method '$method' in registered object");
 }
 }
 }
// test if block methodes callable
if (!empty($block_methods)) {
foreach ((array)$block_methods as $method) {
if (!is_callable(array($object_impl, $method))) {
throw new SmartyException("Undefined method '$method' in registered object");
 }
 }
 }
// register the object
 $this->smarty->registered_objects[$object_name] =
 array($object_impl, (array)$allowed, (boolean)$smarty_args,
                (array)$block_methods);
return $this;
 }
registerPlugin ($type, $tag, $callback, $cacheable = true, $cache_attr = null)
Registers plugin to be used in templates
Parameters
string $type plugin type
string $tag name of template tag
callback $callback PHP callback to register
boolean $cacheable if true (default) this fuction is cachable
array $cache_attr caching attributes if any
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Exceptions
SmartyException when the plugin tag is invalid
Definition at line 428 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\__construct(), SmartyBC\register_block(), SmartyBC\register_compiler_function(), SmartyBC\register_function(), and SmartyBC\register_modifier().
 {
if (isset($this->smarty->registered_plugins[$type][$tag]))
                {
throw new SmartyException("Plugin tag \"{$tag}\" already registered");
 } elseif (!is_callable($callback)) {
throw new SmartyException("Plugin \"{$tag}\" not callable");
 } else {
 $this->smarty->registered_plugins[$type][$tag] = array($callback, (bool)$cacheable, (array)$cache_attr);
 }
return $this;
 }
registerResource ($type, $callback)
Registers a resource to fetch a template
Parameters
string $type name of resource type
Smarty_Resource | array $callback or instance of Smarty_Resource, or array of callbacks to handle resource (deprecated)
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 464 of file smarty_internal_templatebase.php.
Referenced by Smarty_Resource\load(), and SmartyBC\register_resource().
 {
 $this->smarty->registered_resources[$type] = $callback instanceof Smarty_Resource
                ? $callback : array($callback, false);
return $this;
 }
replaceCamelcase ($match) private
preg_replace callback to convert camelcase getter/setter to underscore property names
Parameters
string $match match string
Returns
string replacemant
Definition at line 748 of file smarty_internal_templatebase.php.
 {
return "_" .
                strtolower($match[1]);
 }
unloadFilter ($type, $name)
unload a filter of specified type and name
Parameters
string $type filter type
string $name filter name
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 732 of file smarty_internal_templatebase.php.
 {
 $_filter_name = "smarty_{$type}filter_{$name}";
if (isset($this->smarty->registered_filters[$type][$_filter_name]))
                {
 unset ($this->smarty->registered_filters[$type][$_filter_name]);
 }
return $this;
 }
unregisterCacheResource ($type)
Unregisters a cache resource
Parameters
string $type name of cache resource type
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 504 of file smarty_internal_templatebase.php.
 {
if (isset($this->smarty->registered_cache_resources[$type]))
                {
 unset($this->smarty->registered_cache_resources[$type]);
 }
return $this;
 }
unregisterFilter ($type, $callback)
Unregisters a filter function
Parameters
string $type filter type
callback $callback
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 675 of file smarty_internal_templatebase.php.
References _get_filter_name().
Referenced by SmartyBC\unregister_outputfilter(), SmartyBC\unregister_postfilter(), and SmartyBC\unregister_prefilter().
 {
 $name = $this->_get_filter_name($callback);
if (isset($this->smarty->registered_filters[$type][$name]))
                {
 unset($this->smarty->registered_filters[$type][$name]);
 }
return $this;
 }
unregisterObject ($name)
unregister an object
Parameters
string $name object name
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 573 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\unregister_object().
 {
if (isset($this->smarty->registered_objects[$name]))
                {
 unset($this->smarty->registered_objects[$name]);
 }
return $this;
 }
unregisterPlugin ($type, $tag)
Unregister Plugin
Parameters
string $type of plugin
string $tag name of plugin
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 448 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\unregister_block(), SmartyBC\unregister_compiler_function(), SmartyBC\unregister_function(), and SmartyBC\unregister_modifier().
 {
if (isset($this->smarty->registered_plugins[$type][$tag]))
                {
 unset($this->smarty->registered_plugins[$type][$tag]);
 }
return $this;
 }
unregisterResource ($type)
Unregisters a resource
Parameters
string $type name of resource type
Returns
Smarty_Internal_Templatebase current Smarty_Internal_Templatebase (or Smarty or Smarty_Internal_Template) instance for chaining
Definition at line 476 of file smarty_internal_templatebase.php.
Referenced by SmartyBC\unregister_resource().
 {
if (isset($this->smarty->registered_resources[$type]))
                {
 unset($this->smarty->registered_resources[$type]);
 }
return $this;
 }
The documentation for this class was generated from the following file:
smarty_internal_templatebase.php