oSocial: Smarty_Internal_Configfileparser Class Reference
Smarty_Internal_Configfileparser Class Reference
Public Member Functions
__construct ($lex, $compiler)
tokenName ($tokenType)
yy_pop_parser_stack ()
__destruct ()
yy_get_expected_tokens ($token)
yy_is_expected_token ($token)
yy_find_shift_action ($iLookAhead)
yy_find_reduce_action ($stateno, $iLookAhead)
yy_shift ($yyNewState, $yyMajor, $yypMinor)
yy_r0 ()
yy_r1 ()
yy_r4 ()
yy_r5 ()
yy_r6 ()
yy_r7 ()
yy_r8 ()
yy_r9 ()
yy_r10 ()
yy_r11 ()
yy_r12 ()
yy_r13 ()
yy_r14 ()
yy_r15 ()
yy_r16 ()
yy_r17 ()
yy_reduce ($yyruleno)
yy_parse_failed ()
yy_syntax_error ($yymajor, $TOKEN)
yy_accept ()
doParse ($yymajor, $yytokenvalue)
Static Public Member Functions
static & instance ($new_instance=null)
static Trace ($TraceFILE, $zTracePrompt)
static PrintTrace ()
static yy_destructor ($yymajor, $yypminor)
Data Fields
$successful = true
$retvalue = 0
const TPC_OPENB = 1
const TPC_SECTION = 2
const TPC_CLOSEB = 3
const TPC_DOT = 4
const TPC_ID = 5
const TPC_EQUAL = 6
const TPC_FLOAT = 7
const TPC_INT = 8
const TPC_BOOL = 9
const TPC_SINGLE_QUOTED_STRING = 10
const TPC_DOUBLE_QUOTED_STRING = 11
const TPC_TRIPPLE_QUOTES = 12
const TPC_TRIPPLE_TEXT = 13
const TPC_TRIPPLE_QUOTES_END = 14
const TPC_NAKED_STRING = 15
const TPC_OTHER = 16
const TPC_NEWLINE = 17
const TPC_COMMENTSTART = 18
const YY_NO_ACTION = 60
const YY_ACCEPT_ACTION = 59
const YY_ERROR_ACTION = 58
const YY_SZ_ACTTAB = 38
const YY_SHIFT_USE_DFLT = -8
const YY_SHIFT_MAX = 19
const YY_REDUCE_USE_DFLT = -21
const YY_REDUCE_MAX = 10
const YYNOCODE = 29
const YYSTACKDEPTH = 100
const YYNSTATE = 36
const YYNRULE = 22
const YYERRORSYMBOL = 19
const YYERRSYMDT = 'yy0'
const YYFALLBACK = 0
$yyidx
$yyerrcnt
$yystack = array()
$yyTokenName
Static Public Attributes
static $yy_action
static $yy_lookahead
static $yy_shift_ofst
static $yy_reduce_ofst
static $yyExpectedTokens
static $yy_default
static $yyFallback = array()
static $yyTraceFILE
static $yyTracePrompt
static $yyRuleName
static $yyRuleInfo
static $yyReduceMap
Private Member Functions
parse_bool ($str)
set_var (Array $var, Array &$target_array)
add_global_vars (Array $vars)
add_section_vars ($section_name, Array $vars)
Static Private Member Functions
static parse_single_quoted_string ($qstr)
static parse_double_quoted_string ($qstr)
static parse_tripple_double_quoted_string ($qstr)
Private Attributes
$lex
$internalError = false
$_retvalue
Static Private Attributes
static $escapes_single
Detailed Description
Definition at line 89 of file smarty_internal_configfileparser.php.
Constructor & Destructor Documentation
__construct ($lex, $compiler)
Definition at line 99 of file smarty_internal_configfileparser.php.
References $lex.
 {
// set instance object
 self::instance($this);
 $this->lex = $lex;
 $this->smarty = $compiler->smarty;
 $this->compiler = $compiler;
 }
__destruct ()
Definition at line 464 of file smarty_internal_configfileparser.php.
References yy_pop_parser_stack().
 {
while ($this->yystack !== Array()) {
 $this->yy_pop_parser_stack();
 }
if (is_resource(self::$yyTraceFILE)) {
 fclose(self::$yyTraceFILE);
 }
 }
Member Function Documentation
add_global_vars (Array $vars) private
Definition at line 173 of file smarty_internal_configfileparser.php.
References set_var().
Referenced by yy_r1().
 {
if (!isset($this->compiler->config_data['vars'])) {
 $this->compiler->config_data['vars'] =
                Array();
 }
foreach ($vars as $var) {
 $this->set_var($var,
                $this->compiler->config_data);
 }
 }
add_section_vars ($section_name, Array $vars) private
Definition at line 183 of file smarty_internal_configfileparser.php.
References set_var().
Referenced by yy_r4(), and yy_r5().
 {
if (!isset($this->compiler->config_data['sections'][$section_name]['vars']))
                {
 $this->compiler->config_data['sections'][$section_name]['vars'] = Array();
 }
foreach ($vars as $var) {
 $this->set_var($var,
                $this->compiler->config_data['sections'][$section_name]);
 }
 }
doParse ($yymajor, $yytokenvalue)
Definition at line 959 of file smarty_internal_configfileparser.php.
References $yyidx, yy_accept(), yy_destructor(), yy_find_shift_action(), yy_is_expected_token(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), and yy_syntax_error().
 {
 $yyerrorhit = 0; /* True if yymajor has invoked an error */
if ($this->yyidx === null || $this->yyidx < 0) {
 $this->yyidx = 0;
 $this->yyerrcnt = -1;
 $x = new TPC_yyStackEntry;
 $x->stateno = 0;
 $x->major = 0;
 $this->yystack = array();
 array_push($this->yystack, $x);
 }
 $yyendofinput = ($yymajor == 0);
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sInput %s\n",
 self::$yyTracePrompt, $this->yyTokenName[$yymajor]);
 }
do {
 $yyact = $this->yy_find_shift_action($yymajor);
if ($yymajor < self::YYERRORSYMBOL &&
 !$this->yy_is_expected_token($yymajor)
 ) {
// force a syntax error
 $yyact = self::YY_ERROR_ACTION;
 }
if ($yyact < self::YYNSTATE) {
 $this->yy_shift($yyact,
                $yymajor, $yytokenvalue);
 $this->yyerrcnt--;
if ($yyendofinput && $this->yyidx >= 0) {
 $yymajor = 0;
 } else {
 $yymajor = self::YYNOCODE;
 }
 } elseif ($yyact < self::YYNSTATE + self::YYNRULE) {
 $this->yy_reduce($yyact
                - self::YYNSTATE);
 } elseif ($yyact == self::YY_ERROR_ACTION) {
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sSyntax Error!\n",
 self::$yyTracePrompt);
 }
if (self::YYERRORSYMBOL) {
if ($this->yyerrcnt < 0) {
 $this->yy_syntax_error($yymajor,
                $yytokenvalue);
 }
 $yymx = $this->yystack[$this->yyidx]->major;
if ($yymx == self::YYERRORSYMBOL || $yyerrorhit) {
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sDiscard input token %s\n",
 self::$yyTracePrompt, $this->yyTokenName[$yymajor]);
 }
 $this->yy_destructor($yymajor,
                $yytokenvalue);
 $yymajor = self::YYNOCODE;
 } else {
while ($this->yyidx >= 0 &&
 $yymx != self::YYERRORSYMBOL &&
 ($yyact = $this->yy_find_shift_action(self::YYERRORSYMBOL))
                >= self::YYNSTATE
 ) {
 $this->yy_pop_parser_stack();
 }
if ($this->yyidx < 0 || $yymajor == 0) {
 $this->yy_destructor($yymajor,
                $yytokenvalue);
 $this->yy_parse_failed();
 $yymajor = self::YYNOCODE;
 } elseif ($yymx != self::YYERRORSYMBOL) {
 $u2 = 0;
 $this->yy_shift($yyact,
                self::YYERRORSYMBOL, $u2);
 }
 }
 $this->yyerrcnt = 3;
 $yyerrorhit = 1;
 } else {
if ($this->yyerrcnt <= 0) {
 $this->yy_syntax_error($yymajor,
                $yytokenvalue);
 }
 $this->yyerrcnt = 3;
 $this->yy_destructor($yymajor,
                $yytokenvalue);
if ($yyendofinput) {
 $this->yy_parse_failed();
 }
 $yymajor = self::YYNOCODE;
 }
 } else {
 $this->yy_accept();
 $yymajor = self::YYNOCODE;
 }
 } while ($yymajor != self::YYNOCODE && $this->yyidx
                >= 0);
 }
static& instance ($new_instance = null) static
Definition at line 108 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Config_File_Compiler\trigger_config_file_error().
 {
static $instance = null;
if (isset($new_instance) &&
                is_object($new_instance))
 $instance = $new_instance;
return $instance;
 }
parse_bool ($str) private
Definition at line 116 of file smarty_internal_configfileparser.php.
References $str.
Referenced by yy_r12().
 {
if (in_array(strtolower($str),
                array('on', 'yes',
                'true'))) {
 $res = true;
 } else {
 $res = false;
 }
return $res;
 }
static parse_double_quoted_string ($qstr) static private
Definition at line 149 of file smarty_internal_configfileparser.php.
 {
 $inner_str = substr($qstr, 1, strlen($qstr) - 2);
return stripcslashes($inner_str);
 }
static parse_single_quoted_string ($qstr) static private
Definition at line 129 of file smarty_internal_configfileparser.php.
References $str.
 {
 $escaped_string = substr($qstr, 1, strlen($qstr) - 2); //remove outer quotes
 $ss = preg_split('/(\\\\.)/', $escaped_string,
                -1, PREG_SPLIT_DELIM_CAPTURE);
$str = "";
foreach ($ss as $s) {
if (strlen($s) === 2 && $s[0] === '\\') {
if (isset(self::$escapes_single[$s[1]])) {
 $s = self::$escapes_single[$s[1]];
 }
 }
$str .= $s;
 }
return $str;
 }
static parse_tripple_double_quoted_string ($qstr) static private
Definition at line 155 of file smarty_internal_configfileparser.php.
 {
return stripcslashes($qstr);
 }
static PrintTrace () static
Definition at line 358 of file smarty_internal_configfileparser.php.
 {
 self::$yyTraceFILE = fopen('php://output',
                'w');
 self::$yyTracePrompt = '<br>';
 }
set_var (Array $var, Array & $target_array) private
Definition at line 160 of file smarty_internal_configfileparser.php.
Referenced by add_global_vars(), and add_section_vars().
 {
 $key = $var["key"];
 $value = $var["value"];
if ($this->smarty->config_overwrite ||
                !isset($target_array['vars'][$key])) {
 $target_array['vars'][$key] = $value;
 } else {
 settype($target_array['vars'][$key], 'array');
 $target_array['vars'][$key][] = $value;
 }
 }
tokenName ($tokenType)
Definition at line 427 of file smarty_internal_configfileparser.php.
 {
if ($tokenType === 0) {
return 'End of Input';
 }
if ($tokenType > 0 && $tokenType <
                count($this->yyTokenName)) {
return $this->yyTokenName[$tokenType];
 } else {
return "Unknown";
 }
 }
static Trace ($TraceFILE, $zTracePrompt) static
Definition at line 347 of file smarty_internal_configfileparser.php.
 {
if (!$TraceFILE) {
 $zTracePrompt = 0;
 } elseif (!$zTracePrompt) {
 $TraceFILE = 0;
 }
 self::$yyTraceFILE = $TraceFILE;
 self::$yyTracePrompt = $zTracePrompt;
 }
yy_accept ()
Definition at line 942 of file smarty_internal_configfileparser.php.
References $_retvalue, $internalError, and yy_pop_parser_stack().
Referenced by doParse(), and yy_reduce().
 {
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sAccept!\n",
                self::$yyTracePrompt);
 }
while ($this->yyidx >= 0) {
 $stack = $this->yy_pop_parser_stack();
 }
#line 110 "smarty_internal_configfileparser.y"
 $this->successful = !$this->internalError;
 $this->internalError = false;
 $this->retvalue = $this->_retvalue;
//echo $this->retvalue."\n\n";
#line 826 "smarty_internal_configfileparser.php"
 }
static yy_destructor ($yymajor, $yypminor) static
Definition at line 439 of file smarty_internal_configfileparser.php.
Referenced by doParse().
 {
switch ($yymajor) {
default:
break; /* If no destructor action specified: do nothing */
 }
 }
yy_find_reduce_action ($stateno, $iLookAhead)
Definition at line 651 of file smarty_internal_configfileparser.php.
Referenced by yy_get_expected_tokens(), yy_is_expected_token(), and yy_reduce().
 {
/* $stateno = $this->yystack[$this->yyidx]->stateno; */
if (!isset(self::$yy_reduce_ofst[$stateno])) {
return self::$yy_default[$stateno];
 }
 $i = self::$yy_reduce_ofst[$stateno];
if ($i == self::YY_REDUCE_USE_DFLT) {
return self::$yy_default[$stateno];
 }
if ($iLookAhead == self::YYNOCODE) {
return self::YY_NO_ACTION;
 }
 $i += $iLookAhead;
if ($i < 0 || $i >= self::YY_SZ_ACTTAB ||
 self::$yy_lookahead[$i] != $iLookAhead
 ) {
return self::$yy_default[$stateno];
 } else {
return self::$yy_action[$i];
 }
 }
yy_find_shift_action ($iLookAhead)
Definition at line 615 of file smarty_internal_configfileparser.php.
References $yyidx.
Referenced by doParse(), yy_get_expected_tokens(), and yy_is_expected_token().
 {
 $stateno = $this->yystack[$this->yyidx]->stateno;
/* if ($this->yyidx < 0) return self::YY_NO_ACTION;  */
if (!isset(self::$yy_shift_ofst[$stateno])) {
// no shift actions
return self::$yy_default[$stateno];
 }
 $i = self::$yy_shift_ofst[$stateno];
if ($i === self::YY_SHIFT_USE_DFLT) {
return self::$yy_default[$stateno];
 }
if ($iLookAhead == self::YYNOCODE) {
return self::YY_NO_ACTION;
 }
 $i += $iLookAhead;
if ($i < 0 || $i >= self::YY_SZ_ACTTAB ||
 self::$yy_lookahead[$i] != $iLookAhead
 ) {
if (count(self::$yyFallback) && $iLookAhead <
                count(self::$yyFallback)
                && ($iFallback = self::$yyFallback[$iLookAhead]) != 0
 ) {
if (self::$yyTraceFILE) {
 fwrite(self::$yyTraceFILE, self::$yyTracePrompt . "FALLBACK "
                .
 $this->yyTokenName[$iLookAhead] . " => " .
 $this->yyTokenName[$iFallback] . "\n");
 }
return $this->yy_find_shift_action($iFallback);
 }
return self::$yy_default[$stateno];
 } else {
return self::$yy_action[$i];
 }
 }
yy_get_expected_tokens ($token)
Definition at line 474 of file smarty_internal_configfileparser.php.
References $yyidx, $yystack, yy_find_reduce_action(), and yy_find_shift_action().
 {
 $state = $this->yystack[$this->yyidx]->stateno;
 $expected = self::$yyExpectedTokens[$state];
if (in_array($token, self::$yyExpectedTokens[$state],
                true)) {
return $expected;
 }
 $stack = $this->yystack;
$yyidx
                = $this->yyidx;
do {
 $yyact = $this->yy_find_shift_action($token);
if ($yyact >= self::YYNSTATE && $yyact <
                self::YYNSTATE + self::YYNRULE) {
// reduce action
 $done = 0;
do {
if ($done++ == 100) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
// too much recursion prevents proper detection
// so give up
return array_unique($expected);
 }
 $yyruleno = $yyact - self::YYNSTATE;
 $this->yyidx -= self::$yyRuleInfo[$yyruleno]['rhs'];
 $nextstate = $this->yy_find_reduce_action(
 $this->yystack[$this->yyidx]->stateno,
 self::$yyRuleInfo[$yyruleno]['lhs']);
if (isset(self::$yyExpectedTokens[$nextstate])) {
 $expected = array_merge($expected, self::$yyExpectedTokens[$nextstate]);
if (in_array($token,
 self::$yyExpectedTokens[$nextstate], true)
 ) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
return array_unique($expected);
 }
 }
if ($nextstate < self::YYNSTATE) {
// we need to shift a non-terminal
 $this->yyidx++;
 $x = new TPC_yyStackEntry;
 $x->stateno = $nextstate;
 $x->major = self::$yyRuleInfo[$yyruleno]['lhs'];
 $this->yystack[$this->yyidx]
                = $x;
continue 2;
 } elseif ($nextstate == self::YYNSTATE + self::YYNRULE + 1) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
// the last token was just ignored, we can't accept
// by ignoring input, this is in essence ignoring a
// syntax error!
return array_unique($expected);
 } elseif ($nextstate === self::YY_NO_ACTION) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
// input accepted, but not shifted (I guess)
return $expected;
 } else {
 $yyact = $nextstate;
 }
 } while (true);
 }
break;
 } while (true);
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
return array_unique($expected);
 }
yy_is_expected_token ($token)
Definition at line 543 of file smarty_internal_configfileparser.php.
References $yyidx, $yystack, yy_find_reduce_action(), and yy_find_shift_action().
Referenced by doParse().
 {
if ($token === 0) {
return true; // 0 is not part of this
 }
 $state = $this->yystack[$this->yyidx]->stateno;
if (in_array($token, self::$yyExpectedTokens[$state],
                true)) {
return true;
 }
 $stack = $this->yystack;
$yyidx
                = $this->yyidx;
do {
 $yyact = $this->yy_find_shift_action($token);
if ($yyact >= self::YYNSTATE && $yyact <
                self::YYNSTATE + self::YYNRULE) {
// reduce action
 $done = 0;
do {
if ($done++ == 100) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
// too much recursion prevents proper detection
// so give up
return true;
 }
 $yyruleno = $yyact - self::YYNSTATE;
 $this->yyidx -= self::$yyRuleInfo[$yyruleno]['rhs'];
 $nextstate = $this->yy_find_reduce_action(
 $this->yystack[$this->yyidx]->stateno,
 self::$yyRuleInfo[$yyruleno]['lhs']);
if (isset(self::$yyExpectedTokens[$nextstate]) &&
 in_array($token, self::$yyExpectedTokens[$nextstate], true)
 ) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
return true;
 }
if ($nextstate < self::YYNSTATE) {
// we need to shift a non-terminal
 $this->yyidx++;
 $x = new TPC_yyStackEntry;
 $x->stateno = $nextstate;
 $x->major = self::$yyRuleInfo[$yyruleno]['lhs'];
 $this->yystack[$this->yyidx]
                = $x;
continue 2;
 } elseif ($nextstate == self::YYNSTATE + self::YYNRULE + 1) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
if (!$token) {
// end of input: this is valid
return true;
 }
// the last token was just ignored, we can't accept
// by ignoring input, this is in essence ignoring a
// syntax error!
return false;
 } elseif ($nextstate === self::YY_NO_ACTION) {
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
// input accepted, but not shifted (I guess)
return true;
 } else {
 $yyact = $nextstate;
 }
 } while (true);
 }
break;
 } while (true);
 $this->yyidx = $yyidx;
 $this->yystack = $stack;
return true;
 }
yy_parse_failed ()
Definition at line 922 of file smarty_internal_configfileparser.php.
References yy_pop_parser_stack().
Referenced by doParse().
 {
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sFail!\n",
                self::$yyTracePrompt);
 }
while ($this->yyidx >= 0) {
 $this->yy_pop_parser_stack();
 }
 }
yy_pop_parser_stack ()
Definition at line 447 of file smarty_internal_configfileparser.php.
Referenced by __destruct(), doParse(), yy_accept(), yy_parse_failed(), and yy_shift().
 {
if (!count($this->yystack)) {
return;
 }
 $yytos = array_pop($this->yystack);
if (self::$yyTraceFILE && $this->yyidx >=
                0) {
 fwrite(self::$yyTraceFILE,
 self::$yyTracePrompt . 'Popping ' . $this->yyTokenName[$yytos->major]
                .
"\n");
 }
 $yymajor = $yytos->major;
 self::yy_destructor($yymajor, $yytos->minor);
 $this->yyidx--;
return $yymajor;
 }
yy_r0 ()
Definition at line 761 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = null;
 }
yy_r1 ()
Definition at line 768 of file smarty_internal_configfileparser.php.
References add_global_vars().
 {
 $this->add_global_vars($this->yystack[$this->yyidx
                + 0]->minor);
 $this->_retvalue = null;
 }
yy_r10 ()
Definition at line 822 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = (float)$this->yystack[$this->yyidx + 0]->minor;
 }
yy_r11 ()
Definition at line 829 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = (int)$this->yystack[$this->yyidx + 0]->minor;
 }
yy_r12 ()
Definition at line 836 of file smarty_internal_configfileparser.php.
References parse_bool().
 {
 $this->_retvalue = $this->parse_bool($this->yystack[$this->yyidx
                + 0]->minor);
 }
yy_r13 ()
Definition at line 843 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = self::parse_single_quoted_string($this->yystack[$this->yyidx
                + 0]->minor);
 }
yy_r14 ()
Definition at line 850 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = self::parse_double_quoted_string($this->yystack[$this->yyidx
                + 0]->minor);
 }
yy_r15 ()
Definition at line 857 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = self::parse_tripple_double_quoted_string($this->yystack[$this->yyidx
                + -1]->minor);
 }
yy_r16 ()
Definition at line 864 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = '';
 }
yy_r17 ()
Definition at line 871 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = $this->yystack[$this->yyidx + 0]->minor;
 }
yy_r4 ()
Definition at line 776 of file smarty_internal_configfileparser.php.
References add_section_vars().
 {
 $this->add_section_vars($this->yystack[$this->yyidx
                + -3]->minor, $this->yystack[$this->yyidx + 0]->minor);
 $this->_retvalue = null;
 }
yy_r5 ()
Definition at line 784 of file smarty_internal_configfileparser.php.
References add_section_vars().
 {
if ($this->smarty->config_read_hidden) {
 $this->add_section_vars($this->yystack[$this->yyidx
                + -3]->minor, $this->yystack[$this->yyidx + 0]->minor);
 }
 $this->_retvalue = null;
 }
yy_r6 ()
Definition at line 794 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = $this->yystack[$this->yyidx + -1]->minor;
 }
yy_r7 ()
Definition at line 801 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = array_merge($this->yystack[$this->yyidx + -1]->minor,
                Array($this->yystack[$this->yyidx + 0]->minor));
 }
yy_r8 ()
Definition at line 808 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = Array();
 }
yy_r9 ()
Definition at line 815 of file smarty_internal_configfileparser.php.
 {
 $this->_retvalue = Array("key" =>
                $this->yystack[$this->yyidx + -2]->minor, "value"
                => $this->yystack[$this->yyidx + 0]->minor);
 }
yy_reduce ($yyruleno)
Definition at line 880 of file smarty_internal_configfileparser.php.
References $_retvalue, $yyidx, yy_accept(), yy_find_reduce_action(), and yy_shift().
Referenced by doParse().
 {
 $yymsp = $this->yystack[$this->yyidx];
if (self::$yyTraceFILE && $yyruleno >= 0
            && $yyruleno < count(self::$yyRuleName)
 ) {
 fprintf(self::$yyTraceFILE, "%sReduce (%d) [%s].\n",
 self::$yyTracePrompt, $yyruleno,
 self::$yyRuleName[$yyruleno]);
 }
 $this->_retvalue = $yy_lefthand_side = null;
if (array_key_exists($yyruleno, self::$yyReduceMap)) {
// call the action
 $this->_retvalue = null;
 $this->{'yy_r' .
                self::$yyReduceMap[$yyruleno]}();
 $yy_lefthand_side = $this->_retvalue;
 }
 $yygoto = self::$yyRuleInfo[$yyruleno]['lhs'];
 $yysize = self::$yyRuleInfo[$yyruleno]['rhs'];
 $this->yyidx -= $yysize;
for ($i = $yysize; $i; $i--) {
// pop all of the right-hand side parameters
 array_pop($this->yystack);
 }
 $yyact = $this->yy_find_reduce_action($this->yystack[$this->yyidx]->stateno,
                $yygoto);
if ($yyact < self::YYNSTATE) {
if (!self::$yyTraceFILE && $yysize) {
 $this->yyidx++;
 $x = new TPC_yyStackEntry;
 $x->stateno = $yyact;
 $x->major = $yygoto;
 $x->minor = $yy_lefthand_side;
 $this->yystack[$this->yyidx]
                = $x;
 } else {
 $this->yy_shift($yyact,
                $yygoto, $yy_lefthand_side);
 }
 } elseif ($yyact == self::YYNSTATE + self::YYNRULE + 1) {
 $this->yy_accept();
 }
 }
yy_shift ($yyNewState, $yyMajor, $yypMinor)
Definition at line 675 of file smarty_internal_configfileparser.php.
References $yyidx, and yy_pop_parser_stack().
Referenced by doParse(), and yy_reduce().
 {
 $this->yyidx++;
if ($this->yyidx >= self::YYSTACKDEPTH) {
 $this->yyidx--;
if (self::$yyTraceFILE) {
 fprintf(self::$yyTraceFILE, "%sStack Overflow!\n", self::$yyTracePrompt);
 }
while ($this->yyidx >= 0) {
 $this->yy_pop_parser_stack();
 }
#line 125 "smarty_internal_configfileparser.y"
 $this->internalError = true;
 $this->compiler->trigger_config_file_error("Stack overflow in configfile parser");
#line 593 "smarty_internal_configfileparser.php"
 return;
 }
 $yytos = new TPC_yyStackEntry;
 $yytos->stateno = $yyNewState;
 $yytos->major = $yyMajor;
 $yytos->minor = $yypMinor;
 array_push($this->yystack, $yytos);
if (self::$yyTraceFILE && $this->yyidx > 0)
                {
 fprintf(self::$yyTraceFILE, "%sShift %d\n",
                self::$yyTracePrompt,
 $yyNewState);
 fprintf(self::$yyTraceFILE, "%sStack:",
                self::$yyTracePrompt);
for ($i = 1; $i <= $this->yyidx;
                $i++) {
 fprintf(self::$yyTraceFILE, " %s",
 $this->yyTokenName[$this->yystack[$i]->major]);
 }
 fwrite(self::$yyTraceFILE, "\n");
 }
 }
yy_syntax_error ($yymajor, $TOKEN)
Definition at line 932 of file smarty_internal_configfileparser.php.
Referenced by doParse().
 {
#line 118 "smarty_internal_configfileparser.y"
 $this->internalError = true;
 $this->yymajor = $yymajor;
 $this->compiler->trigger_config_file_error();
#line 808 "smarty_internal_configfileparser.php"
 }
Field Documentation
$_retvalue private
Definition at line 878 of file smarty_internal_configfileparser.php.
Referenced by yy_accept(), and yy_reduce().
$escapes_single static private
Initial value:
= Array('\\' => '\\',
'\'' => '\'')
Definition at line 126 of file smarty_internal_configfileparser.php.
$internalError = false private
Definition at line 97 of file smarty_internal_configfileparser.php.
Referenced by yy_accept().
$lex private
Definition at line 96 of file smarty_internal_configfileparser.php.
Referenced by __construct().
$retvalue = 0
Definition at line 95 of file smarty_internal_configfileparser.php.
$successful = true
Definition at line 94 of file smarty_internal_configfileparser.php.
$yy_action static
Initial value:
= array(
 29, 30, 34, 33, 24, 13, 19, 25, 35, 21,
 59, 8, 3, 1, 20, 12, 14, 31, 20, 12,
 15, 17, 23, 18, 27, 26, 4, 5, 6, 32,
 2, 11, 28, 22, 16, 9, 7, 10,
 )
Definition at line 218 of file smarty_internal_configfileparser.php.
$yy_default static
Initial value:
= array(
 44, 37, 41, 40, 58, 58, 58, 36, 39, 44,
 44, 58, 58, 58, 58, 58, 58, 58, 58, 58,
 55, 54, 57, 56, 50, 45, 43, 42, 38, 46,
 47, 52, 51, 49, 48, 53,
 )
Definition at line 328 of file smarty_internal_configfileparser.php.
$yy_lookahead static
Initial value:
= array(
 7, 8, 9, 10, 11, 12, 5, 27, 15, 16,
 20, 21, 23, 23, 17, 18, 13, 14, 17, 18,
 15, 2, 17, 4, 25, 26, 6, 3, 3, 14,
 23, 1, 24, 17, 2, 25, 22, 25,
 )
Definition at line 228 of file smarty_internal_configfileparser.php.
$yy_reduce_ofst static
Initial value:
= array(
 -10, -1, -1, -1, -20, 10, 12, 8, 14, 7,
 -11,
 )
Definition at line 248 of file smarty_internal_configfileparser.php.
$yy_shift_ofst static
Initial value:
= array(
 -8, 1, 1, 1, -7, -3, -3, 30, -8, -8,
 -8, 19, 5, 3, 15, 16, 24, 25, 32, 20,
 )
Definition at line 240 of file smarty_internal_configfileparser.php.
$yyerrcnt
Definition at line 367 of file smarty_internal_configfileparser.php.
$yyExpectedTokens static
Definition at line 254 of file smarty_internal_configfileparser.php.
$yyFallback = array() static
Definition at line 345 of file smarty_internal_configfileparser.php.
$yyidx
Definition at line 366 of file smarty_internal_configfileparser.php.
Referenced by doParse(), yy_find_shift_action(), yy_get_expected_tokens(), yy_is_expected_token(), yy_reduce(), and yy_shift().
$yyReduceMap static
Initial value:
= array(
 0 => 0,
 2 => 0,
 3 => 0,
 19 => 0,
 20 => 0,
 21 => 0,
 1 => 1,
 4 => 4,
 5 => 5,
 6 => 6,
 7 => 7,
 8 => 8,
 9 => 9,
 10 => 10,
 11 => 11,
 12 => 12,
 13 => 13,
 14 => 14,
 15 => 15,
 16 => 16,
 17 => 17,
 18 => 17,
 )
Definition at line 735 of file smarty_internal_configfileparser.php.
$yyRuleInfo static
Initial value:
= array(
 array('lhs' => 20, 'rhs' => 2),
 array('lhs' => 21, 'rhs' => 1),
 array('lhs' => 22, 'rhs' => 2),
 array('lhs' => 22, 'rhs' => 0),
 array('lhs' => 24, 'rhs' => 5),
 array('lhs' => 24, 'rhs' => 6),
 array('lhs' => 23, 'rhs' => 2),
 array('lhs' => 23, 'rhs' => 2),
 array('lhs' => 23, 'rhs' => 0),
 array('lhs' => 26, 'rhs' => 3),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 3),
 array('lhs' => 27, 'rhs' => 2),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 27, 'rhs' => 1),
 array('lhs' => 25, 'rhs' => 1),
 array('lhs' => 25, 'rhs' => 2),
 array('lhs' => 25, 'rhs' => 3),
 )
Definition at line 710 of file smarty_internal_configfileparser.php.
$yyRuleName static
Definition at line 380 of file smarty_internal_configfileparser.php.
$yystack = array()
Definition at line 368 of file smarty_internal_configfileparser.php.
Referenced by yy_get_expected_tokens(), and yy_is_expected_token().
$yyTokenName
Initial value:
= array(
'$', 'OPENB', 'SECTION',
                'CLOSEB',
'DOT', 'ID', 'EQUAL', 'FLOAT',
'INT', 'BOOL',
                'SINGLE_QUOTED_STRING', 'DOUBLE_QUOTED_STRING',
'TRIPPLE_QUOTES', 'TRIPPLE_TEXT',
                'TRIPPLE_QUOTES_END', 'NAKED_STRING',
'OTHER', 'NEWLINE',
                'COMMENTSTART', 'error',
'start', 'global_vars',
                'sections', 'var_list',
'section', 'newline',
                'var', 'value',
 )
Definition at line 370 of file smarty_internal_configfileparser.php.
$yyTraceFILE static
Definition at line 364 of file smarty_internal_configfileparser.php.
$yyTracePrompt static
Definition at line 365 of file smarty_internal_configfileparser.php.
const TPC_BOOL = 9
Definition at line 203 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_7().
const TPC_CLOSEB = 3
Definition at line 197 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_3().
const TPC_COMMENTSTART = 18
Definition at line 212 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_1().
const TPC_DOT = 4
Definition at line 198 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r5_1().
const TPC_DOUBLE_QUOTED_STRING = 11
Definition at line 205 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_6().
const TPC_EQUAL = 6
Definition at line 200 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_4().
const TPC_FLOAT = 7
Definition at line 201 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_2().
const TPC_ID = 5
Definition at line 199 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_7().
const TPC_INT = 8
Definition at line 202 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_3().
const TPC_NAKED_STRING = 15
Definition at line 209 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_8(), Smarty_Internal_Configfilelexer\yy_r2_9(), Smarty_Internal_Configfilelexer\yy_r3_1(), and Smarty_Internal_Configfilelexer\yy_r4_2().
const TPC_NEWLINE = 17
Definition at line 211 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_6(), and Smarty_Internal_Configfilelexer\yy_r4_3().
const TPC_OPENB = 1
Definition at line 195 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_2().
const TPC_OTHER = 16
Definition at line 210 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r1_8().
const TPC_SECTION = 2
Definition at line 196 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r5_2().
const TPC_SINGLE_QUOTED_STRING = 10
Definition at line 204 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_5().
const TPC_TRIPPLE_QUOTES = 12
Definition at line 206 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r2_4().
const TPC_TRIPPLE_QUOTES_END = 14
Definition at line 208 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r6_1().
const TPC_TRIPPLE_TEXT = 13
Definition at line 207 of file smarty_internal_configfileparser.php.
Referenced by Smarty_Internal_Configfilelexer\yy_r6_2().
const YY_ACCEPT_ACTION = 59
Definition at line 214 of file smarty_internal_configfileparser.php.
const YY_ERROR_ACTION = 58
Definition at line 215 of file smarty_internal_configfileparser.php.
const YY_NO_ACTION = 60
Definition at line 213 of file smarty_internal_configfileparser.php.
const YY_REDUCE_MAX = 10
Definition at line 247 of file smarty_internal_configfileparser.php.
const YY_REDUCE_USE_DFLT = -21
Definition at line 246 of file smarty_internal_configfileparser.php.
const YY_SHIFT_MAX = 19
Definition at line 239 of file smarty_internal_configfileparser.php.
const YY_SHIFT_USE_DFLT = -8
Definition at line 238 of file smarty_internal_configfileparser.php.
const YY_SZ_ACTTAB = 38
Definition at line 217 of file smarty_internal_configfileparser.php.
const YYERRORSYMBOL = 19
Definition at line 342 of file smarty_internal_configfileparser.php.
const YYERRSYMDT = 'yy0'
Definition at line 343 of file smarty_internal_configfileparser.php.
const YYFALLBACK = 0
Definition at line 344 of file smarty_internal_configfileparser.php.
const YYNOCODE = 29
Definition at line 338 of file smarty_internal_configfileparser.php.
const YYNRULE = 22
Definition at line 341 of file smarty_internal_configfileparser.php.
const YYNSTATE = 36
Definition at line 340 of file smarty_internal_configfileparser.php.
const YYSTACKDEPTH = 100
Definition at line 339 of file smarty_internal_configfileparser.php.
The documentation for this class was generated from the following file:
smarty_internal_configfileparser.php