oSocial: Smarty_Internal_Templatelexer Class Reference
Smarty_Internal_Templatelexer Class Reference
Public Member Functions
__construct ($data, $compiler)
yylex ()
yypushstate ($state)
yypopstate ()
yybegin ($state)
yylex1 ()
yy_r1_1 ($yy_subpatterns)
yy_r1_2 ($yy_subpatterns)
yy_r1_3 ($yy_subpatterns)
yy_r1_5 ($yy_subpatterns)
yy_r1_6 ($yy_subpatterns)
yy_r1_7 ($yy_subpatterns)
yy_r1_8 ($yy_subpatterns)
yy_r1_9 ($yy_subpatterns)
yy_r1_10 ($yy_subpatterns)
yy_r1_11 ($yy_subpatterns)
yy_r1_13 ($yy_subpatterns)
yy_r1_14 ($yy_subpatterns)
yy_r1_15 ($yy_subpatterns)
yy_r1_16 ($yy_subpatterns)
yy_r1_17 ($yy_subpatterns)
yy_r1_18 ($yy_subpatterns)
yy_r1_19 ($yy_subpatterns)
yy_r1_20 ($yy_subpatterns)
yy_r1_21 ($yy_subpatterns)
yy_r1_22 ($yy_subpatterns)
yy_r1_23 ($yy_subpatterns)
yy_r1_24 ($yy_subpatterns)
yylex2 ()
yy_r2_1 ($yy_subpatterns)
yy_r2_2 ($yy_subpatterns)
yy_r2_3 ($yy_subpatterns)
yy_r2_5 ($yy_subpatterns)
yy_r2_6 ($yy_subpatterns)
yy_r2_7 ($yy_subpatterns)
yy_r2_8 ($yy_subpatterns)
yy_r2_9 ($yy_subpatterns)
yy_r2_10 ($yy_subpatterns)
yy_r2_11 ($yy_subpatterns)
yy_r2_12 ($yy_subpatterns)
yy_r2_13 ($yy_subpatterns)
yy_r2_14 ($yy_subpatterns)
yy_r2_15 ($yy_subpatterns)
yy_r2_16 ($yy_subpatterns)
yy_r2_17 ($yy_subpatterns)
yy_r2_18 ($yy_subpatterns)
yy_r2_19 ($yy_subpatterns)
yy_r2_20 ($yy_subpatterns)
yy_r2_22 ($yy_subpatterns)
yy_r2_24 ($yy_subpatterns)
yy_r2_26 ($yy_subpatterns)
yy_r2_27 ($yy_subpatterns)
yy_r2_28 ($yy_subpatterns)
yy_r2_29 ($yy_subpatterns)
yy_r2_30 ($yy_subpatterns)
yy_r2_31 ($yy_subpatterns)
yy_r2_32 ($yy_subpatterns)
yy_r2_33 ($yy_subpatterns)
yy_r2_34 ($yy_subpatterns)
yy_r2_35 ($yy_subpatterns)
yy_r2_36 ($yy_subpatterns)
yy_r2_37 ($yy_subpatterns)
yy_r2_38 ($yy_subpatterns)
yy_r2_39 ($yy_subpatterns)
yy_r2_40 ($yy_subpatterns)
yy_r2_41 ($yy_subpatterns)
yy_r2_42 ($yy_subpatterns)
yy_r2_43 ($yy_subpatterns)
yy_r2_47 ($yy_subpatterns)
yy_r2_48 ($yy_subpatterns)
yy_r2_49 ($yy_subpatterns)
yy_r2_50 ($yy_subpatterns)
yy_r2_51 ($yy_subpatterns)
yy_r2_52 ($yy_subpatterns)
yy_r2_53 ($yy_subpatterns)
yy_r2_54 ($yy_subpatterns)
yy_r2_55 ($yy_subpatterns)
yy_r2_57 ($yy_subpatterns)
yy_r2_59 ($yy_subpatterns)
yy_r2_60 ($yy_subpatterns)
yy_r2_61 ($yy_subpatterns)
yy_r2_62 ($yy_subpatterns)
yy_r2_63 ($yy_subpatterns)
yy_r2_64 ($yy_subpatterns)
yy_r2_65 ($yy_subpatterns)
yy_r2_66 ($yy_subpatterns)
yy_r2_67 ($yy_subpatterns)
yy_r2_68 ($yy_subpatterns)
yy_r2_69 ($yy_subpatterns)
yy_r2_70 ($yy_subpatterns)
yy_r2_71 ($yy_subpatterns)
yy_r2_72 ($yy_subpatterns)
yy_r2_73 ($yy_subpatterns)
yy_r2_74 ($yy_subpatterns)
yy_r2_75 ($yy_subpatterns)
yy_r2_76 ($yy_subpatterns)
yy_r2_77 ($yy_subpatterns)
yylex3 ()
yy_r3_1 ($yy_subpatterns)
yy_r3_2 ($yy_subpatterns)
yy_r3_3 ($yy_subpatterns)
yy_r3_4 ($yy_subpatterns)
yy_r3_5 ($yy_subpatterns)
yy_r3_6 ($yy_subpatterns)
yy_r3_7 ($yy_subpatterns)
yylex4 ()
yy_r4_1 ($yy_subpatterns)
yy_r4_2 ($yy_subpatterns)
yy_r4_4 ($yy_subpatterns)
yy_r4_5 ($yy_subpatterns)
yy_r4_6 ($yy_subpatterns)
yy_r4_7 ($yy_subpatterns)
yy_r4_8 ($yy_subpatterns)
yy_r4_9 ($yy_subpatterns)
yy_r4_10 ($yy_subpatterns)
yy_r4_11 ($yy_subpatterns)
yy_r4_12 ($yy_subpatterns)
yy_r4_13 ($yy_subpatterns)
yy_r4_17 ($yy_subpatterns)
Data Fields
$data
$counter
$token
$value
$node
$line
$taglineno
$state = 1
$smarty_token_names
const TEXT = 1
const SMARTY = 2
const LITERAL = 3
const DOUBLEQUOTEDSTRING = 4
Private Attributes
$heredoc_id_stack = Array()
$_yy_state = 1
$_yy_stack = array()
Detailed Description
Smarty Internal Plugin Templatelexer
Definition at line 13 of file smarty_internal_templatelexer.php.
Constructor & Destructor Documentation
__construct ($data, $compiler)
Definition at line 77 of file smarty_internal_templatelexer.php.
References $data.
 {
//        $this->data = preg_replace("/(\r\n|\r|\n)/", "\n", $data);
 $this->data = $data;
 $this->counter = 0;
 $this->line = 1;
 $this->smarty = $compiler->smarty;
 $this->compiler = $compiler;
 $this->ldel = preg_quote($this->smarty->left_delimiter, '/');
 $this->ldel_length = strlen($this->smarty->left_delimiter);
 $this->rdel = preg_quote($this->smarty->right_delimiter, '/');
 $this->rdel_length = strlen($this->smarty->right_delimiter);
 $this->smarty_token_names['LDEL'] = $this->smarty->left_delimiter;
 $this->smarty_token_names['RDEL'] = $this->smarty->right_delimiter;
 $this->mbstring_overload = ini_get('mbstring.func_overload')
                & 2;
 }
Member Function Documentation
yy_r1_1 ($yy_subpatterns)
Definition at line 201 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_SMARTYBLOCKCHILD.
 {
 $this->token = Smarty_Internal_Templateparser::TP_SMARTYBLOCKCHILD;
 }
yy_r1_10 ($yy_subpatterns)
Definition at line 258 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_11 ($yy_subpatterns)
Definition at line 270 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELIF, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELIF;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_13 ($yy_subpatterns)
Definition at line 282 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOR, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOR;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_14 ($yy_subpatterns)
Definition at line 294 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOREACH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOREACH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_15 ($yy_subpatterns)
Definition at line 306 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSETFILTER, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSETFILTER;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_16 ($yy_subpatterns)
Definition at line 318 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r1_17 ($yy_subpatterns)
Definition at line 330 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r1_18 ($yy_subpatterns)
Definition at line 338 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r1_19 ($yy_subpatterns)
Definition at line 346 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_FAKEPHPSTARTTAG, Smarty_Internal_Templateparser\TP_PHPSTARTTAG, and Smarty_Internal_Templateparser\TP_XMLTAG.
 {
if (in_array($this->value, Array('<?', '<?=',
                '<?php'))) {
 $this->token = Smarty_Internal_Templateparser::TP_PHPSTARTTAG;
 } elseif ($this->value == '<?xml') {
 $this->token = Smarty_Internal_Templateparser::TP_XMLTAG;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_FAKEPHPSTARTTAG;
 $this->value = substr($this->value, 0, 2);
 }
 }
yy_r1_2 ($yy_subpatterns)
Definition at line 207 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r1_20 ($yy_subpatterns)
Definition at line 359 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_PHPENDTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_PHPENDTAG;
 }
yy_r1_21 ($yy_subpatterns)
Definition at line 365 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r1_22 ($yy_subpatterns)
Definition at line 371 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ASPSTARTTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ASPSTARTTAG;
 }
yy_r1_23 ($yy_subpatterns)
Definition at line 377 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ASPENDTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ASPENDTAG;
 }
yy_r1_24 ($yy_subpatterns)
Definition at line 383 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
if ($this->mbstring_overload) {
 $to = mb_strlen($this->data, 'latin1');
 } else {
 $to = strlen($this->data);
 }
 preg_match("/{$this->ldel}|<\?|\?>|<%|%>/",
                $this->data, $match, PREG_OFFSET_CAPTURE, $this->counter);
if (isset($match[0][1])) {
 $to = $match[0][1];
 }
if ($this->mbstring_overload) {
 $this->value = mb_substr($this->data, $this->counter, $to - $this->counter,
                'latin1');
 } else {
 $this->value = substr($this->data, $this->counter, $to - $this->counter);
 }
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r1_3 ($yy_subpatterns)
Definition at line 213 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_COMMENT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_COMMENT;
 }
yy_r1_5 ($yy_subpatterns)
Definition at line 219 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_STRIPON.
 {
 $this->token = Smarty_Internal_Templateparser::TP_STRIPON;
 }
yy_r1_6 ($yy_subpatterns)
Definition at line 225 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_STRIPON, and Smarty_Internal_Templateparser\TP_TEXT.
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_STRIPON;
 }
 }
yy_r1_7 ($yy_subpatterns)
Definition at line 235 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_STRIPOFF.
 {
 $this->token = Smarty_Internal_Templateparser::TP_STRIPOFF;
 }
yy_r1_8 ($yy_subpatterns)
Definition at line 241 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_STRIPOFF, and Smarty_Internal_Templateparser\TP_TEXT.
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_STRIPOFF;
 }
 }
yy_r1_9 ($yy_subpatterns)
Definition at line 251 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LITERALSTART, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LITERALSTART;
 $this->yypushstate(self::LITERAL);
 }
yy_r2_1 ($yy_subpatterns)
Definition at line 531 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_SINGLEQUOTESTRING.
 {
 $this->token = Smarty_Internal_Templateparser::TP_SINGLEQUOTESTRING;
 }
yy_r2_10 ($yy_subpatterns)
Definition at line 612 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r2_11 ($yy_subpatterns)
Definition at line 620 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_RDEL, and yypopstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_RDEL;
 $this->yypopstate();
 }
yy_r2_12 ($yy_subpatterns)
Definition at line 627 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISIN.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISIN;
 }
yy_r2_13 ($yy_subpatterns)
Definition at line 633 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_AS.
 {
 $this->token = Smarty_Internal_Templateparser::TP_AS;
 }
yy_r2_14 ($yy_subpatterns)
Definition at line 639 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TO.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TO;
 }
yy_r2_15 ($yy_subpatterns)
Definition at line 645 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_STEP.
 {
 $this->token = Smarty_Internal_Templateparser::TP_STEP;
 }
yy_r2_16 ($yy_subpatterns)
Definition at line 651 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_INSTANCEOF.
 {
 $this->token = Smarty_Internal_Templateparser::TP_INSTANCEOF;
 }
yy_r2_17 ($yy_subpatterns)
Definition at line 657 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_IDENTITY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_IDENTITY;
 }
yy_r2_18 ($yy_subpatterns)
Definition at line 663 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_NONEIDENTITY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_NONEIDENTITY;
 }
yy_r2_19 ($yy_subpatterns)
Definition at line 669 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_EQUALS.
 {
 $this->token = Smarty_Internal_Templateparser::TP_EQUALS;
 }
yy_r2_2 ($yy_subpatterns)
Definition at line 537 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r2_20 ($yy_subpatterns)
Definition at line 675 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_NOTEQUALS.
 {
 $this->token = Smarty_Internal_Templateparser::TP_NOTEQUALS;
 }
yy_r2_22 ($yy_subpatterns)
Definition at line 681 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_GREATEREQUAL.
 {
 $this->token = Smarty_Internal_Templateparser::TP_GREATEREQUAL;
 }
yy_r2_24 ($yy_subpatterns)
Definition at line 687 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LESSEQUAL.
 {
 $this->token = Smarty_Internal_Templateparser::TP_LESSEQUAL;
 }
yy_r2_26 ($yy_subpatterns)
Definition at line 693 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_GREATERTHAN.
 {
 $this->token = Smarty_Internal_Templateparser::TP_GREATERTHAN;
 }
yy_r2_27 ($yy_subpatterns)
Definition at line 699 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LESSTHAN.
 {
 $this->token = Smarty_Internal_Templateparser::TP_LESSTHAN;
 }
yy_r2_28 ($yy_subpatterns)
Definition at line 705 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_MOD.
 {
 $this->token = Smarty_Internal_Templateparser::TP_MOD;
 }
yy_r2_29 ($yy_subpatterns)
Definition at line 711 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_NOT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_NOT;
 }
yy_r2_3 ($yy_subpatterns)
Definition at line 549 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELIF, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELIF;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r2_30 ($yy_subpatterns)
Definition at line 717 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LAND.
 {
 $this->token = Smarty_Internal_Templateparser::TP_LAND;
 }
yy_r2_31 ($yy_subpatterns)
Definition at line 723 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LOR.
 {
 $this->token = Smarty_Internal_Templateparser::TP_LOR;
 }
yy_r2_32 ($yy_subpatterns)
Definition at line 729 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LXOR.
 {
 $this->token = Smarty_Internal_Templateparser::TP_LXOR;
 }
yy_r2_33 ($yy_subpatterns)
Definition at line 735 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISODDBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISODDBY;
 }
yy_r2_34 ($yy_subpatterns)
Definition at line 741 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISNOTODDBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISNOTODDBY;
 }
yy_r2_35 ($yy_subpatterns)
Definition at line 747 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISODD.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISODD;
 }
yy_r2_36 ($yy_subpatterns)
Definition at line 753 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISNOTODD.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISNOTODD;
 }
yy_r2_37 ($yy_subpatterns)
Definition at line 759 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISEVENBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISEVENBY;
 }
yy_r2_38 ($yy_subpatterns)
Definition at line 765 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISNOTEVENBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISNOTEVENBY;
 }
yy_r2_39 ($yy_subpatterns)
Definition at line 771 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISEVEN.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISEVEN;
 }
yy_r2_40 ($yy_subpatterns)
Definition at line 777 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISNOTEVEN.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISNOTEVEN;
 }
yy_r2_41 ($yy_subpatterns)
Definition at line 783 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISDIVBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISDIVBY;
 }
yy_r2_42 ($yy_subpatterns)
Definition at line 789 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ISNOTDIVBY.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ISNOTDIVBY;
 }
yy_r2_43 ($yy_subpatterns)
Definition at line 795 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TYPECAST.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TYPECAST;
 }
yy_r2_47 ($yy_subpatterns)
Definition at line 801 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_OPENP.
 {
 $this->token = Smarty_Internal_Templateparser::TP_OPENP;
 }
yy_r2_48 ($yy_subpatterns)
Definition at line 807 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_CLOSEP.
 {
 $this->token = Smarty_Internal_Templateparser::TP_CLOSEP;
 }
yy_r2_49 ($yy_subpatterns)
Definition at line 813 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_OPENB.
 {
 $this->token = Smarty_Internal_Templateparser::TP_OPENB;
 }
yy_r2_5 ($yy_subpatterns)
Definition at line 561 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOR, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOR;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r2_50 ($yy_subpatterns)
Definition at line 819 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_CLOSEB.
 {
 $this->token = Smarty_Internal_Templateparser::TP_CLOSEB;
 }
yy_r2_51 ($yy_subpatterns)
Definition at line 825 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_PTR.
 {
 $this->token = Smarty_Internal_Templateparser::TP_PTR;
 }
yy_r2_52 ($yy_subpatterns)
Definition at line 831 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_APTR.
 {
 $this->token = Smarty_Internal_Templateparser::TP_APTR;
 }
yy_r2_53 ($yy_subpatterns)
Definition at line 837 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_EQUAL.
 {
 $this->token = Smarty_Internal_Templateparser::TP_EQUAL;
 }
yy_r2_54 ($yy_subpatterns)
Definition at line 843 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_INCDEC.
 {
 $this->token = Smarty_Internal_Templateparser::TP_INCDEC;
 }
yy_r2_55 ($yy_subpatterns)
Definition at line 849 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_UNIMATH.
 {
 $this->token = Smarty_Internal_Templateparser::TP_UNIMATH;
 }
yy_r2_57 ($yy_subpatterns)
Definition at line 855 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_MATH.
 {
 $this->token = Smarty_Internal_Templateparser::TP_MATH;
 }
yy_r2_59 ($yy_subpatterns)
Definition at line 861 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_DOLLAR.
 {
 $this->token = Smarty_Internal_Templateparser::TP_DOLLAR;
 }
yy_r2_6 ($yy_subpatterns)
Definition at line 573 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOREACH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOREACH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r2_60 ($yy_subpatterns)
Definition at line 867 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_SEMICOLON.
 {
 $this->token = Smarty_Internal_Templateparser::TP_SEMICOLON;
 }
yy_r2_61 ($yy_subpatterns)
Definition at line 873 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_DOUBLECOLON.
 {
 $this->token = Smarty_Internal_Templateparser::TP_DOUBLECOLON;
 }
yy_r2_62 ($yy_subpatterns)
Definition at line 879 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_COLON.
 {
 $this->token = Smarty_Internal_Templateparser::TP_COLON;
 }
yy_r2_63 ($yy_subpatterns)
Definition at line 885 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_AT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_AT;
 }
yy_r2_64 ($yy_subpatterns)
Definition at line 891 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_HATCH.
 {
 $this->token = Smarty_Internal_Templateparser::TP_HATCH;
 }
yy_r2_65 ($yy_subpatterns)
Definition at line 897 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_QUOTE, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_QUOTE;
 $this->yypushstate(self::DOUBLEQUOTEDSTRING);
 }
yy_r2_66 ($yy_subpatterns)
Definition at line 904 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_BACKTICK, and yypopstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_BACKTICK;
 $this->yypopstate();
 }
yy_r2_67 ($yy_subpatterns)
Definition at line 911 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_VERT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_VERT;
 }
yy_r2_68 ($yy_subpatterns)
Definition at line 917 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_DOT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_DOT;
 }
yy_r2_69 ($yy_subpatterns)
Definition at line 923 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_COMMA.
 {
 $this->token = Smarty_Internal_Templateparser::TP_COMMA;
 }
yy_r2_7 ($yy_subpatterns)
Definition at line 585 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r2_70 ($yy_subpatterns)
Definition at line 929 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ANDSYM.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ANDSYM;
 }
yy_r2_71 ($yy_subpatterns)
Definition at line 935 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_QMARK.
 {
 $this->token = Smarty_Internal_Templateparser::TP_QMARK;
 }
yy_r2_72 ($yy_subpatterns)
Definition at line 941 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_HEX.
 {
 $this->token = Smarty_Internal_Templateparser::TP_HEX;
 }
yy_r2_73 ($yy_subpatterns)
Definition at line 947 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ATTR, and Smarty_Internal_Templateparser\TP_SPACE.
 {
// resolve conflicts with shorttag and right_delimiter starting with '='
if (substr($this->data, $this->counter +
                strlen($this->value) - 1, $this->rdel_length) == $this->smarty->right_delimiter) {
 preg_match("/\s+/", $this->value,
                $match);
 $this->value = $match[0];
 $this->token = Smarty_Internal_Templateparser::TP_SPACE;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_ATTR;
 }
 }
yy_r2_74 ($yy_subpatterns)
Definition at line 960 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ID.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ID;
 }
yy_r2_75 ($yy_subpatterns)
Definition at line 966 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_INTEGER.
 {
 $this->token = Smarty_Internal_Templateparser::TP_INTEGER;
 }
yy_r2_76 ($yy_subpatterns)
Definition at line 972 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_SPACE.
 {
 $this->token = Smarty_Internal_Templateparser::TP_SPACE;
 }
yy_r2_77 ($yy_subpatterns)
Definition at line 978 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r2_8 ($yy_subpatterns)
Definition at line 597 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_RDEL, and yypopstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_RDEL;
 $this->yypopstate();
 }
yy_r2_9 ($yy_subpatterns)
Definition at line 604 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r3_1 ($yy_subpatterns)
Definition at line 1051 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LITERALSTART, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LITERALSTART;
 $this->yypushstate(self::LITERAL);
 }
yy_r3_2 ($yy_subpatterns)
Definition at line 1058 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LITERALEND, and yypopstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LITERALEND;
 $this->yypopstate();
 }
yy_r3_3 ($yy_subpatterns)
Definition at line 1065 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_FAKEPHPSTARTTAG, and Smarty_Internal_Templateparser\TP_PHPSTARTTAG.
 {
if (in_array($this->value, Array('<?', '<?=',
                '<?php'))) {
 $this->token = Smarty_Internal_Templateparser::TP_PHPSTARTTAG;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_FAKEPHPSTARTTAG;
 $this->value = substr($this->value, 0, 2);
 }
 }
yy_r3_4 ($yy_subpatterns)
Definition at line 1076 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_PHPENDTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_PHPENDTAG;
 }
yy_r3_5 ($yy_subpatterns)
Definition at line 1082 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ASPSTARTTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ASPSTARTTAG;
 }
yy_r3_6 ($yy_subpatterns)
Definition at line 1088 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_ASPENDTAG.
 {
 $this->token = Smarty_Internal_Templateparser::TP_ASPENDTAG;
 }
yy_r3_7 ($yy_subpatterns)
Definition at line 1094 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_LITERAL.
 {
if ($this->mbstring_overload) {
 $to = mb_strlen($this->data, 'latin1');
 } else {
 $to = strlen($this->data);
 }
 preg_match("/{$this->ldel}\/?literal{$this->rdel}|<\?|<%|\?>|%>/",
                $this->data, $match, PREG_OFFSET_CAPTURE, $this->counter);
if (isset($match[0][1])) {
 $to = $match[0][1];
 } else {
 $this->compiler->trigger_template_error("missing or misspelled literal closing tag");
 }
if ($this->mbstring_overload) {
 $this->value = mb_substr($this->data, $this->counter, $to - $this->counter,
                'latin1');
 } else {
 $this->value = substr($this->data, $this->counter, $to - $this->counter);
 }
 $this->token = Smarty_Internal_Templateparser::TP_LITERAL;
 }
yy_r4_1 ($yy_subpatterns)
Definition at line 1189 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r4_10 ($yy_subpatterns)
Definition at line 1272 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_BACKTICK, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_BACKTICK;
 $this->value = substr($this->value, 0, -1);
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r4_11 ($yy_subpatterns)
Definition at line 1281 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_DOLLARID.
 {
 $this->token = Smarty_Internal_Templateparser::TP_DOLLARID;
 }
yy_r4_12 ($yy_subpatterns)
Definition at line 1287 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r4_13 ($yy_subpatterns)
Definition at line 1293 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r4_17 ($yy_subpatterns)
Definition at line 1299 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_TEXT.
 {
if ($this->mbstring_overload) {
 $to = mb_strlen($this->data, 'latin1');
 } else {
 $to = strlen($this->data);
 }
if ($this->mbstring_overload) {
 $this->value = mb_substr($this->data, $this->counter, $to - $this->counter,
                'latin1');
 } else {
 $this->value = substr($this->data, $this->counter, $to - $this->counter);
 }
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 }
yy_r4_2 ($yy_subpatterns)
Definition at line 1201 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELIF, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELIF;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r4_4 ($yy_subpatterns)
Definition at line 1213 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOR, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOR;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r4_5 ($yy_subpatterns)
Definition at line 1225 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELFOREACH, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal &&
                trim(substr($this->value, $this->ldel_length, 1)) == '')
                {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDELFOREACH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r4_6 ($yy_subpatterns)
Definition at line 1237 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, Smarty_Internal_Templateparser\TP_TEXT, and yypushstate().
 {
if ($this->smarty->auto_literal) {
 $this->token = Smarty_Internal_Templateparser::TP_TEXT;
 } else {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
 }
yy_r4_7 ($yy_subpatterns)
Definition at line 1249 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDELSLASH, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDELSLASH;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r4_8 ($yy_subpatterns)
Definition at line 1257 of file smarty_internal_templatelexer.php.
References $line, Smarty_Internal_Templateparser\TP_LDEL, and yypushstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_LDEL;
 $this->yypushstate(self::SMARTY);
 $this->taglineno = $this->line;
 }
yy_r4_9 ($yy_subpatterns)
Definition at line 1265 of file smarty_internal_templatelexer.php.
References Smarty_Internal_Templateparser\TP_QUOTE, and yypopstate().
 {
 $this->token = Smarty_Internal_Templateparser::TP_QUOTE;
 $this->yypopstate();
 }
yybegin ($state)
Definition at line 114 of file smarty_internal_templatelexer.php.
References $state.
 {
 $this->_yy_state = $state;
 }
yylex ()
Definition at line 98 of file smarty_internal_templatelexer.php.
Referenced by yylex1(), yylex2(), yylex3(), and yylex4().
 {
return $this->{'yylex'
                . $this->_yy_state}();
 }
yylex1 ()
Definition at line 120 of file smarty_internal_templatelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 1,
 5 => 0,
 6 => 0,
 7 => 0,
 8 => 0,
 9 => 0,
 10 => 0,
 11 => 1,
 13 => 0,
 14 => 0,
 15 => 0,
 16 => 0,
 17 => 0,
 18 => 0,
 19 => 0,
 20 => 0,
 21 => 0,
 22 => 0,
 23 => 0,
 24 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(" . $this->ldel
                . "[$]smarty\\.block\\.child" . $this->rdel . ")|\G(\\{\\})|\G(" . $this->ldel . "\\*([\S\s]*?)\\*" . $this->rdel . ")|\G(" . $this->ldel . "strip"
                . $this->rdel . ")|\G(" . $this->ldel . "\\s{1,}strip\\s{1,}" . $this->rdel . ")|\G(" . $this->ldel . "\/strip"
                . $this->rdel . ")|\G(" . $this->ldel . "\\s{1,}\/strip\\s{1,}" . $this->rdel . ")|\G(" . $this->ldel . "\\s*literal\\s*"
                . $this->rdel . ")|\G(" . $this->ldel . "\\s{1,}\/)|\G(" . $this->ldel . "\\s*(if|elseif|else if|while)\\s+)|\G(" . $this->ldel
                . "\\s*for\\s+)|\G(" . $this->ldel . "\\s*foreach(?![^\s]))|\G(" . $this->ldel . "\\s*setfilter\\s+)|\G(" . $this->ldel . "\\s{1,})|\G(" . $this->ldel . "\/)|\G(" . $this->ldel . ")|\G(<\\?(?:php\\w+|=|[a-zA-Z]+)?)|\G(\\?>)|\G("
                . $this->rdel . ")|\G(<%)|\G(%>)|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state TEXT');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r1_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex2 ()
Definition at line 404 of file smarty_internal_templatelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 1,
 5 => 0,
 6 => 0,
 7 => 0,
 8 => 0,
 9 => 0,
 10 => 0,
 11 => 0,
 12 => 0,
 13 => 0,
 14 => 0,
 15 => 0,
 16 => 0,
 17 => 0,
 18 => 0,
 19 => 0,
 20 => 1,
 22 => 1,
 24 => 1,
 26 => 0,
 27 => 0,
 28 => 0,
 29 => 0,
 30 => 0,
 31 => 0,
 32 => 0,
 33 => 0,
 34 => 0,
 35 => 0,
 36 => 0,
 37 => 0,
 38 => 0,
 39 => 0,
 40 => 0,
 41 => 0,
 42 => 0,
 43 => 3,
 47 => 0,
 48 => 0,
 49 => 0,
 50 => 0,
 51 => 0,
 52 => 0,
 53 => 0,
 54 => 0,
 55 => 1,
 57 => 1,
 59 => 0,
 60 => 0,
 61 => 0,
 62 => 0,
 63 => 0,
 64 => 0,
 65 => 0,
 66 => 0,
 67 => 0,
 68 => 0,
 69 => 0,
 70 => 0,
 71 => 0,
 72 => 0,
 73 => 0,
 74 => 0,
 75 => 0,
 76 => 0,
 77 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G('[^'\\\\]*(?:\\\\.[^'\\\\]*)*')|\G("
                . $this->ldel . "\\s{1,}\/)|\G(" . $this->ldel .
                "\\s*(if|elseif|else if|while)\\s+)|\G(" . $this->ldel .
                "\\s*for\\s+)|\G(" . $this->ldel . "\\s*foreach(?![^\s]))|\G(" . $this->ldel . "\\s{1,})|\G(\\s{1,}" . $this->rdel . ")|\G(" . $this->ldel . "\/)|\G("
                . $this->ldel . ")|\G(" . $this->rdel . ")|\G(\\s+is\\s+in\\s+)|\G(\\s+as\\s+)|\G(\\s+to\\s+)|\G(\\s+step\\s+)|\G(\\s+instanceof\\s+)|\G(\\s*===\\s*)|\G(\\s*!==\\s*)|\G(\\s*==\\s*|\\s+eq\\s+)|\G(\\s*!=\\s*|\\s*<>\\s*|\\s+(ne|neq)\\s+)|\G(\\s*>=\\s*|\\s+(ge|gte)\\s+)|\G(\\s*<=\\s*|\\s+(le|lte)\\s+)|\G(\\s*>\\s*|\\s+gt\\s+)|\G(\\s*<\\s*|\\s+lt\\s+)|\G(\\s+mod\\s+)|\G(!\\s*|not\\s+)|\G(\\s*&&\\s*|\\s*and\\s+)|\G(\\s*\\|\\|\\s*|\\s*or\\s+)|\G(\\s*xor\\s+)|\G(\\s+is\\s+odd\\s+by\\s+)|\G(\\s+is\\s+not\\s+odd\\s+by\\s+)|\G(\\s+is\\s+odd)|\G(\\s+is\\s+not\\s+odd)|\G(\\s+is\\s+even\\s+by\\s+)|\G(\\s+is\\s+not\\s+even\\s+by\\s+)|\G(\\s+is\\s+even)|\G(\\s+is\\s+not\\s+even)|\G(\\s+is\\s+div\\s+by\\s+)|\G(\\s+is\\s+not\\s+div\\s+by\\s+)|\G(\\((int(eger)?|bool(ean)?|float|double|real|string|binary|array|object)\\)\\s*)|\G(\\s*\\(\\s*)|\G(\\s*\\))|\G(\\[\\s*)|\G(\\s*\\])|\G(\\s*->\\s*)|\G(\\s*=>\\s*)|\G(\\s*=\\s*)|\G(\\+\\+|--)|\G(\\s*(\\+|-)\\s*)|\G(\\s*(\\*|\/|%)\\s*)|\G(\\$)|\G(\\s*;)|\G(::)|\G(\\s*:\\s*)|\G(@)|\G(#)|\G(\")|\G(`)|\G(\\|)|\G(\\.)|\G(\\s*,\\s*)|\G(\\s*&\\s*)|\G(\\s*\\?\\s*)|\G(0[xX][0-9a-fA-F]+)|\G(\\s+[0-9]*[a-zA-Z_][a-zA-Z0-9_\-:]*\\s*=\\s*)|\G([0-9]*[a-zA-Z_]\\w*)|\G(\\d+)|\G(\\s+)|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state SMARTY');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r2_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex3 ()
Definition at line 985 of file smarty_internal_templatelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 0,
 3 => 0,
 4 => 0,
 5 => 0,
 6 => 0,
 7 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(" . $this->ldel
                . "\\s*literal\\s*" . $this->rdel . ")|\G(" . $this->ldel . "\\s*\/literal\\s*"
                . $this->rdel . ")|\G(<\\?(?:php\\w+|=|[a-zA-Z]+)?)|\G(\\?>)|\G(<%)|\G(%>)|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state LITERAL');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r3_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yylex4 ()
Definition at line 1117 of file smarty_internal_templatelexer.php.
References yylex().
 {
 $tokenMap = array(
 1 => 0,
 2 => 1,
 4 => 0,
 5 => 0,
 6 => 0,
 7 => 0,
 8 => 0,
 9 => 0,
 10 => 0,
 11 => 0,
 12 => 0,
 13 => 3,
 17 => 0,
 );
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
 $yy_global_pattern = "/\G(" . $this->ldel
                . "\\s{1,}\/)|\G(" . $this->ldel . "\\s*(if|elseif|else if|while)\\s+)|\G(" . $this->ldel
                . "\\s*for\\s+)|\G(" . $this->ldel . "\\s*foreach(?![^\s]))|\G(" . $this->ldel . "\\s{1,})|\G(" . $this->ldel . "\/)|\G(" . $this->ldel . ")|\G(\")|\G(`\\$)|\G(\\$[0-9]*[a-zA-Z_]\\w*)|\G(\\$)|\G(([^\"\\\\]*?)((?:\\\\.[^\"\\\\]*?)*?)(?=("
                . $this->ldel . "|\\$|`\\$|\")))|\G([\S\s])/iS";
do {
if ($this->mbstring_overload ?
                preg_match($yy_global_pattern, mb_substr($this->data, $this->counter, 2000000000, 'latin1'), $yymatches) : preg_match($yy_global_pattern,
                $this->data, $yymatches, null, $this->counter)) {
 $yysubmatches = $yymatches;
 $yymatches = array_filter($yymatches, 'strlen');
                // remove empty sub-patterns
if (!count($yymatches)) {
throw new Exception('Error: lexing failed because a rule matched' .
' an empty string.  Input "' .
                substr($this->data,
 $this->counter, 5) . '... state DOUBLEQUOTEDSTRING');
 }
 next($yymatches); // skip global match
 $this->token = key($yymatches); // token number
if ($tokenMap[$this->token]) {
// extract sub-patterns for passing to lex function
 $yysubmatches = array_slice($yysubmatches, $this->token + 1,
 $tokenMap[$this->token]);
 } else {
 $yysubmatches = array();
 }
 $this->value = current($yymatches); // token value
 $r = $this->{'yy_r4_' . $this->token}($yysubmatches);
if ($r === null) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
// accept this token
return true;
 } elseif ($r === true) {
// we have changed state
// process this token in the new state
return $this->yylex();
 } elseif ($r === false) {
 $this->counter += ($this->mbstring_overload ? mb_strlen($this->value, 'latin1') : strlen($this->value));
 $this->line += substr_count($this->value, "\n");
if ($this->counter >= ($this->mbstring_overload
                ? mb_strlen($this->data, 'latin1') : strlen($this->data)))
                {
return false; // end of input
 }
// skip this token
continue;
 }
 } else {
throw new Exception('Unexpected input at line' . $this->line .
': ' . $this->data[$this->counter]);
 }
break;
 } while (true);
 } // end function
yypopstate ()
Definition at line 109 of file smarty_internal_templatelexer.php.
Referenced by yy_r2_11(), yy_r2_66(), yy_r2_8(), yy_r3_2(), and yy_r4_9().
 {
 $this->_yy_state = array_pop($this->_yy_stack);
 }
yypushstate ($state)
Definition at line 103 of file smarty_internal_templatelexer.php.
References $state.
Referenced by yy_r1_10(), yy_r1_11(), yy_r1_13(), yy_r1_14(), yy_r1_15(), yy_r1_16(), yy_r1_17(), yy_r1_18(), yy_r1_9(), yy_r2_10(), yy_r2_2(), yy_r2_3(), yy_r2_5(), yy_r2_6(), yy_r2_65(), yy_r2_7(), yy_r2_9(), yy_r3_1(), yy_r4_1(), yy_r4_10(), yy_r4_2(), yy_r4_4(), yy_r4_5(), yy_r4_6(), yy_r4_7(), and yy_r4_8().
 {
 array_push($this->_yy_stack, $this->_yy_state);
 $this->_yy_state = $state;
 }
Field Documentation
$_yy_stack = array() private
Definition at line 96 of file smarty_internal_templatelexer.php.
$_yy_state = 1 private
Definition at line 95 of file smarty_internal_templatelexer.php.
$counter
Definition at line 16 of file smarty_internal_templatelexer.php.
$data
Definition at line 15 of file smarty_internal_templatelexer.php.
Referenced by __construct().
$heredoc_id_stack = Array() private
Definition at line 23 of file smarty_internal_templatelexer.php.
$line
Definition at line 20 of file smarty_internal_templatelexer.php.
Referenced by yy_r1_10(), yy_r1_11(), yy_r1_13(), yy_r1_14(), yy_r1_15(), yy_r1_16(), yy_r1_17(), yy_r1_18(), yy_r2_10(), yy_r2_2(), yy_r2_3(), yy_r2_5(), yy_r2_6(), yy_r2_7(), yy_r2_9(), yy_r4_1(), yy_r4_10(), yy_r4_2(), yy_r4_4(), yy_r4_5(), yy_r4_6(), yy_r4_7(), and yy_r4_8().
$node
Definition at line 19 of file smarty_internal_templatelexer.php.
$smarty_token_names
Definition at line 24 of file smarty_internal_templatelexer.php.
$state = 1
Definition at line 22 of file smarty_internal_templatelexer.php.
Referenced by yybegin(), and yypushstate().
$taglineno
Definition at line 21 of file smarty_internal_templatelexer.php.
$token
Definition at line 17 of file smarty_internal_templatelexer.php.
$value
Definition at line 18 of file smarty_internal_templatelexer.php.
const DOUBLEQUOTEDSTRING = 4
Definition at line 1187 of file smarty_internal_templatelexer.php.
const LITERAL = 3
Definition at line 1049 of file smarty_internal_templatelexer.php.
const SMARTY = 2
Definition at line 529 of file smarty_internal_templatelexer.php.
const TEXT = 1
Definition at line 199 of file smarty_internal_templatelexer.php.
The documentation for this class was generated from the following file:
smarty_internal_templatelexer.php