oSocial: Smarty Class Reference
Smarty Class Reference
Public Member Functions
__construct ()
__destruct ()
__clone ()
__get ($name)
__set ($name, $value)
templateExists ($resource_name)
getGlobal ($varname=null)
clearAllCache ($exp_time=null, $type=null)
clearCache ($template_name, $cache_id=null, $compile_id=null, $exp_time=null, $type=null)
enableSecurity ($security_class=null)
disableSecurity ()
setTemplateDir ($template_dir)
addTemplateDir ($template_dir, $key=null)
getTemplateDir ($index=null)
setConfigDir ($config_dir)
addConfigDir ($config_dir, $key=null)
getConfigDir ($index=null)
setPluginsDir ($plugins_dir)
addPluginsDir ($plugins_dir)
getPluginsDir ()
setCompileDir ($compile_dir)
getCompileDir ()
setCacheDir ($cache_dir)
getCacheDir ()
setDefaultModifiers ($modifiers)
addDefaultModifiers ($modifiers)
getDefaultModifiers ()
setAutoloadFilters ($filters, $type=null)
addAutoloadFilters ($filters, $type=null)
getAutoloadFilters ($type=null)
getDebugTemplate ()
setDebugTemplate ($tpl_name)
createTemplate ($template, $cache_id=null, $compile_id=null, $parent=null, $do_clone=true)
loadPlugin ($plugin_name, $check=true)
compileAllTemplates ($extention= '.tpl', $force_compile=false, $time_limit=0, $max_errors=null)
compileAllConfig ($extention= '.conf', $force_compile=false, $time_limit=0, $max_errors=null)
clearCompiledTemplate ($resource_name=null, $compile_id=null, $exp_time=null)
getTags (Smarty_Internal_Template $template)
testInstall (&$errors=null)
Public Member Functions inherited from Smarty_Internal_TemplateBase
fetch ($template=null, $cache_id=null, $compile_id=null, $parent=null, $display=false, $merge_tpl_vars=true, $no_output_filter=false)
display ($template=null, $cache_id=null, $compile_id=null, $parent=null)
isCached ($template=null, $cache_id=null, $compile_id=null, $parent=null)
createData ($parent=null)
registerPlugin ($type, $tag, $callback, $cacheable=true, $cache_attr=null)
unregisterPlugin ($type, $tag)
registerResource ($type, $callback)
unregisterResource ($type)
registerCacheResource ($type, Smarty_CacheResource $callback)
unregisterCacheResource ($type)
registerObject ($object_name, $object_impl, $allowed=array(), $smarty_args=true, $block_methods=array())
getRegisteredObject ($name)
unregisterObject ($name)
registerClass ($class_name, $class_impl)
registerDefaultPluginHandler ($callback)
registerDefaultTemplateHandler ($callback)
registerDefaultConfigHandler ($callback)
registerFilter ($type, $callback)
unregisterFilter ($type, $callback)
_get_filter_name ($function_name)
loadFilter ($type, $name)
unloadFilter ($type, $name)
__call ($name, $args)
Public Member Functions inherited from Smarty_Internal_Data
assign ($tpl_var, $value=null, $nocache=false)
assignGlobal ($varname, $value=null, $nocache=false)
assignByRef ($tpl_var, &$value, $nocache=false)
append ($tpl_var, $value=null, $merge=false, $nocache=false)
appendByRef ($tpl_var, &$value, $merge=false)
getTemplateVars ($varname=null, $_ptr=null, $search_parents=true)
clearAssign ($tpl_var)
clearAllAssign ()
configLoad ($config_file, $sections=null)
getVariable ($variable, $_ptr=null, $search_parents=true, $error_enable=true)
getConfigVariable ($variable, $error_enable=true)
getStreamVariable ($variable)
getConfigVars ($varname=null, $search_parents=true)
clearConfig ($varname=null)
Static Public Member Functions
static mutingErrorHandler ($errno, $errstr, $errfile, $errline, $errcontext)
static muteExpectedErrors ()
static unmuteExpectedErrors ()
Data Fields
const SMARTY_VERSION = 'Smarty-3.1.12'
const SCOPE_LOCAL = 0
const SCOPE_PARENT = 1
const SCOPE_ROOT = 2
const SCOPE_GLOBAL = 3
const CACHING_OFF = 0
const CACHING_LIFETIME_CURRENT = 1
const CACHING_LIFETIME_SAVED = 2
const COMPILECHECK_OFF = 0
const COMPILECHECK_ON = 1
const COMPILECHECK_CACHEMISS = 2
const PHP_PASSTHRU = 0
const PHP_QUOTE = 1
const PHP_REMOVE = 2
const PHP_ALLOW = 3
const FILTER_POST = 'post'
const FILTER_PRE = 'pre'
const FILTER_OUTPUT = 'output'
const FILTER_VARIABLE = 'variable'
const PLUGIN_FUNCTION = 'function'
const PLUGIN_BLOCK = 'block'
const PLUGIN_COMPILER = 'compiler'
const PLUGIN_MODIFIER = 'modifier'
const PLUGIN_MODIFIERCOMPILER = 'modifiercompiler'
$auto_literal = true
$error_unassigned = false
$use_include_path = false
$joined_template_dir = null
$joined_config_dir = null
$default_template_handler_func = null
$default_config_handler_func = null
$default_plugin_handler_func = null
$force_compile = false
$compile_check = true
$use_sub_dirs = false
$allow_ambiguous_resources = false
$caching = false
$merge_compiled_includes = false
$cache_lifetime = 3600
$force_cache = false
$cache_id = null
$compile_id = null
$left_delimiter = "{"
$right_delimiter = "}"
$security_class = 'Smarty_Security'
$security_policy = null
$php_handling = self::PHP_PASSTHRU
$allow_php_templates = false
$direct_access_security = true
$debugging = false
$debugging_ctrl = 'NONE'
$smarty_debug_id = 'SMARTY_DEBUG'
$debug_tpl = null
$error_reporting = null
$get_used_tags = false
$config_overwrite = true
$config_booleanize = true
$config_read_hidden = false
$compile_locking = true
$cache_locking = false
$locking_timeout = 10
$template_functions = array()
$default_resource_type = 'file'
$caching_type = 'file'
$properties = array()
$default_config_type = 'file'
$template_objects = array()
$cache_modified_check = false
$registered_plugins = array()
$plugin_search_order = array('function', 'block', 'compiler', 'class')
$registered_objects = array()
$registered_classes = array()
$registered_filters = array()
$registered_resources = array()
$_resource_handlers = array()
$registered_cache_resources = array()
$_cacheresource_handlers = array()
$autoload_filters = array()
$default_modifiers = array()
$escape_html = false
$start_time = 0
$_file_perms = 0644
$_dir_perms = 0771
$_tag_stack = array()
$smarty
$_current_file = null
$_parserdebug = false
$merged_templates_func = array()
Static Public Attributes
static $global_tpl_vars = array()
static $_previous_error_handler = null
static $_muted_directories = array()
static $_MBSTRING = SMARTY_MBSTRING
static $_CHARSET = SMARTY_RESOURCE_CHAR_SET
static $_DATE_FORMAT = SMARTY_RESOURCE_DATE_FORMAT
static $_UTF8_MODIFIER = 'u'
static $_IS_WINDOWS = false
static $_smarty_vars = array()
Private Attributes
$template_dir = array()
$compile_dir = null
$plugins_dir = array()
$cache_dir = null
$config_dir = array()
Detailed Description
Definition at line 107 of file Smarty.class.php.
Constructor & Destructor Documentation
__construct ()
#@- Initialize new Smarty object
Definition at line 612 of file Smarty.class.php.
References $_CHARSET, Smarty_Internal_Data\assignGlobal(), and setTemplateDir().
 {
// selfpointer needed by some other class methods
 $this->smarty = $this;
if (is_callable('mb_internal_encoding'))
                {
 mb_internal_encoding(Smarty::$_CHARSET);
 }
 $this->start_time = microtime(true);
// set default dirs
 $this->setTemplateDir('.' . DS . 'templates'
                . DS)
 ->setCompileDir('.' . DS . 'templates_c' . DS)
 ->setPluginsDir(SMARTY_PLUGINS_DIR)
 ->setCacheDir('.' . DS . 'cache' . DS)
 ->setConfigDir('.' . DS . 'configs' . DS);
 $this->debug_tpl = 'file:' .
                dirname(__FILE__) . '/debug.tpl';
if (isset($_SERVER['SCRIPT_NAME']))
                {
 $this->assignGlobal('SCRIPT_NAME', $_SERVER['SCRIPT_NAME']);
 }
 }
__destruct ()
Class destructor
Definition at line 637 of file Smarty.class.php.
 {
// intentionally left blank
 }
Member Function Documentation
__clone ()
<<magic>> set selfpointer on cloned object
Definition at line 645 of file Smarty.class.php.
 {
 $this->smarty = $this;
 }
__get ($name)
<<magic>> Generic getter.
Calls the appropriate getter function. Issues an E_USER_NOTICE if no valid getter is found.
Parameters
string $name property name
Returns
mixed
Definition at line 660 of file Smarty.class.php.
 {
 $allowed = array(
'template_dir' => 'getTemplateDir',
'config_dir' => 'getConfigDir',
'plugins_dir' => 'getPluginsDir',
'compile_dir' => 'getCompileDir',
'cache_dir' => 'getCacheDir',
 );
if (isset($allowed[$name])) {
return $this->{$allowed[$name]}();
 } else {
 trigger_error('Undefined property: ' .
                get_class($this) . '::$' . $name, E_USER_NOTICE);
 }
 }
__set ($name, $value)
<<magic>> Generic setter.
Calls the appropriate setter function. Issues an E_USER_NOTICE if no valid setter is found.
Parameters
string $name property name
mixed $value parameter passed to setter
Definition at line 686 of file Smarty.class.php.
 {
 $allowed = array(
'template_dir' => 'setTemplateDir',
'config_dir' => 'setConfigDir',
'plugins_dir' => 'setPluginsDir',
'compile_dir' => 'setCompileDir',
'cache_dir' => 'setCacheDir',
 );
if (isset($allowed[$name])) {
 $this->{$allowed[$name]}($value);
 } else {
 trigger_error('Undefined property: ' .
                get_class($this) . '::$' . $name, E_USER_NOTICE);
 }
 }
addAutoloadFilters ($filters, $type = null)
Add autoload filters
Parameters
array $filters filters to load automatically
string $type "pre", "output", … specify the filter type to set. Defaults to none treating $filters' keys as the appropriate types
Returns
Smarty current Smarty instance for chaining
Definition at line 1121 of file Smarty.class.php.
 {
if ($type !== null) {
if (!empty($this->autoload_filters[$type])) {
 $this->autoload_filters[$type] = array_merge($this->autoload_filters[$type],
                (array)$filters);
 } else {
 $this->autoload_filters[$type] = (array)$filters;
 }
 } else {
foreach ((array)$filters as $key => $value) {
if (!empty($this->autoload_filters[$key])) {
 $this->autoload_filters[$key] = array_merge($this->autoload_filters[$key],
                (array)$value);
 } else {
 $this->autoload_filters[$key] = (array)$value;
 }
 }
 }
return $this;
 }
addConfigDir ($config_dir, $key = null)
Add config directory(s)
Parameters
string | array $config_dir directory(s) of config sources
string key of the array element to assign the config dir to
Returns
Smarty current Smarty instance for chaining
Definition at line 907 of file Smarty.class.php.
References $config_dir.
 {
// make sure we're dealing with an array
 $this->config_dir = (array)$this->config_dir;
if (is_array($config_dir))
                {
foreach ($config_dir
                as $k => $v) {
if (is_int($k)) {
// indexes are not merged but appended
 $this->config_dir[] = rtrim($v, '/\\') .
                DS;
 } else {
// string indexes are overridden
 $this->config_dir[$k] = rtrim($v, '/\\') .
                DS;
 }
 }
 } elseif ($key !== null) {
// override directory at specified index
 $this->config_dir[$key] = rtrim($config_dir,
                '/\\') . DS;
 } else {
// append new directory
 $this->config_dir[] = rtrim($config_dir,
                '/\\') . DS;
 }
 $this->joined_config_dir = join(DIRECTORY_SEPARATOR, $this->config_dir);
return $this;
 }
addDefaultModifiers ($modifiers)
Add default modifiers
Parameters
array | string $modifiers modifier or list of modifiers to add
Returns
Smarty current Smarty instance for chaining
Definition at line 1074 of file Smarty.class.php.
 {
if (is_array($modifiers)) {
 $this->default_modifiers = array_merge($this->default_modifiers, $modifiers);
 } else {
 $this->default_modifiers[] = $modifiers;
 }
return $this;
 }
addPluginsDir ($plugins_dir)
Adds directory of plugin files
Parameters
object $smarty
string $ |array $ plugins folder
Returns
Smarty current Smarty instance for chaining
Definition at line 972 of file Smarty.class.php.
References $plugins_dir.
 {
// make sure we're dealing with an array
 $this->plugins_dir = (array)$this->plugins_dir;
if (is_array($plugins_dir))
                {
foreach ($plugins_dir
                as $k => $v) {
if (is_int($k)) {
// indexes are not merged but appended
 $this->plugins_dir[] = rtrim($v, '/\\') .
                DS;
 } else {
// string indexes are overridden
 $this->plugins_dir[$k] = rtrim($v, '/\\') .
                DS;
 }
 }
 } else {
// append new directory
 $this->plugins_dir[] = rtrim($plugins_dir,
                '/\\') . DS;
 }
 $this->plugins_dir = array_unique($this->plugins_dir);
return $this;
 }
addTemplateDir ($template_dir, $key = null)
Add template directory(s)
Parameters
string | array $template_dir directory(s) of template sources
string $key of the array element to assign the template dir to
Returns
Smarty current Smarty instance for chaining
Exceptions
SmartyException when the given template directory is not valid
Definition at line 842 of file Smarty.class.php.
References $template_dir.
 {
// make sure we're dealing with an array
 $this->template_dir = (array)$this->template_dir;
if (is_array($template_dir))
                {
foreach ($template_dir
                as $k => $v) {
if (is_int($k)) {
// indexes are not merged but appended
 $this->template_dir[] = rtrim($v, '/\\') .
                DS;
 } else {
// string indexes are overridden
 $this->template_dir[$k] = rtrim($v, '/\\')
                . DS;
 }
 }
 } elseif ($key !== null) {
// override directory at specified index
 $this->template_dir[$key] = rtrim($template_dir,
                '/\\') . DS;
 } else {
// append new directory
 $this->template_dir[] = rtrim($template_dir,
                '/\\') . DS;
 }
 $this->joined_template_dir = join(DIRECTORY_SEPARATOR, $this->template_dir);
return $this;
 }
clearAllCache ($exp_time = null, $type = null)
Empty cache folder
Parameters
integer $exp_time expiration time
string $type resource type
Returns
integer number of cache files deleted
Definition at line 751 of file Smarty.class.php.
References Smarty_CacheResource\invalidLoadedCache(), and Smarty_CacheResource\load().
 {
// load cache resource and call clearAll
 $_cache_resource = Smarty_CacheResource::load($this,
                $type);
Smarty_CacheResource::invalidLoadedCache($this);
return $_cache_resource->clearAll($this, $exp_time);
 }
clearCache ($template_name, $cache_id = null, $compile_id = null, $exp_time = null, $type = null)
Empty cache for a specific template
Parameters
string $template_name template name
string $cache_id cache id
string $compile_id compile id
integer $exp_time expiration time
string $type resource type
Returns
integer number of cache files deleted
Definition at line 769 of file Smarty.class.php.
References $cache_id, $compile_id, Smarty_CacheResource\invalidLoadedCache(), and Smarty_CacheResource\load().
Referenced by SmartyBC\clear_all_cache(), and SmartyBC\clear_cache().
 {
// load cache resource and call clear
 $_cache_resource = Smarty_CacheResource::load($this,
                $type);
Smarty_CacheResource::invalidLoadedCache($this);
return $_cache_resource->clear($this, $template_name,
                $cache_id, $compile_id,
                $exp_time);
 }
clearCompiledTemplate ($resource_name = null, $compile_id = null, $exp_time = null)
Delete compiled template file
Parameters
string $resource_name template name
string $compile_id compile id
integer $exp_time expiration time
Returns
integer number of template files deleted
Definition at line 1355 of file Smarty.class.php.
References $compile_id, and Smarty_Internal_Utility\clearCompiledTemplate().
Referenced by SmartyBC\clear_compiled_tpl().
 {
return Smarty_Internal_Utility::clearCompiledTemplate($resource_name,
                $compile_id, $exp_time,
                $this);
 }
compileAllConfig ($extention = '.conf', $force_compile = false, $time_limit = 0, $max_errors = null)
Compile all config files
Parameters
string $extension file extension
bool $force_compile force all to recompile
int $time_limit
int $max_errors
Returns
integer number of template files recompiled
Definition at line 1342 of file Smarty.class.php.
References $force_compile, and Smarty_Internal_Utility\compileAllConfig().
 {
return Smarty_Internal_Utility::compileAllConfig($extention,
                $force_compile,
                $time_limit, $max_errors, $this);
 }
compileAllTemplates ($extention = '.tpl', $force_compile = false, $time_limit = 0, $max_errors = null)
Compile all template files
Parameters
string $extension file extension
bool $force_compile force all to recompile
int $time_limit
int $max_errors
Returns
integer number of template files recompiled
Definition at line 1328 of file Smarty.class.php.
References $force_compile, and Smarty_Internal_Utility\compileAllTemplates().
 {
return Smarty_Internal_Utility::compileAllTemplates($extention,
                $force_compile,
                $time_limit, $max_errors, $this);
 }
createTemplate ($template, $cache_id = null, $compile_id = null, $parent = null, $do_clone = true)
creates a template object
Parameters
string $template the resource handle of the template file
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
object $parent next higher level of Smarty variables
boolean $do_clone flag is Smarty object shall be cloned
Returns
object template object
Definition at line 1194 of file Smarty.class.php.
References $cache_id, $compile_id, Smarty_Internal_Data\$parent, and Smarty_Resource\getUniqueTemplateName().
Referenced by Smarty_Internal_Utility\compileAllTemplates().
 {
if (!empty($cache_id)
                && (is_object($cache_id)
                || is_array($cache_id)))
                {
$parent
                = $cache_id;
$cache_id =
                null;
 }
if (!empty($parent)
                && is_array($parent))
                {
 $data = $parent;
$parent
                = null;
 } else {
 $data = null;
 }
// default to cache_id and compile_id of Smarty object
$cache_id =
                $cache_id === null ?
                $this->cache_id : $cache_id;
$compile_id
                = $compile_id === null ?
                $this->compile_id : $compile_id;
// already in template cache?
if ($this->allow_ambiguous_resources) {
 $_templateId = Smarty_Resource::getUniqueTemplateName($this,
                $template) . $cache_id .
                $compile_id;
 } else {
 $_templateId = $this->joined_template_dir . '#' . $template . $cache_id
                . $compile_id;
 }
if (isset($_templateId[150])) {
 $_templateId = sha1($_templateId);
 }
if ($do_clone) {
if (isset($this->template_objects[$_templateId])) {
// return cached template object
 $tpl = clone $this->template_objects[$_templateId];
 $tpl->smarty = clone $tpl->smarty;
 $tpl->parent = $parent;
 $tpl->tpl_vars = array();
 $tpl->config_vars = array();
 } else {
 $tpl = new $this->template_class($template, clone $this,
                $parent,
                $cache_id, $compile_id);
 }
 } else {
if (isset($this->template_objects[$_templateId])) {
// return cached template object
 $tpl = $this->template_objects[$_templateId];
 $tpl->parent = $parent;
 $tpl->tpl_vars = array();
 $tpl->config_vars = array();
 } else {
 $tpl = new $this->template_class($template, $this, $parent, $cache_id, $compile_id);
 }
 }
// fill data if present
if (!empty($data) && is_array($data)) {
// set up variable values
foreach ($data as $_key => $_val) {
 $tpl->tpl_vars[$_key] = new Smarty_variable($_val);
 }
 }
return $tpl;
 }
disableSecurity ()
Disable security
Returns
Smarty current Smarty instance for chaining
Definition at line 810 of file Smarty.class.php.
 {
 $this->security_policy = null;
return $this;
 }
enableSecurity ($security_class = null)
Loads security class and enables security
Parameters
string | Smarty_Security $security_class if a string is used, it must be class-name
Returns
Smarty current Smarty instance for chaining
Exceptions
SmartyException when an invalid class name is provided
Definition at line 784 of file Smarty.class.php.
References $security_class.
 {
if ($security_class
                instanceof Smarty_Security) {
 $this->security_policy = $security_class;
return $this;
 } elseif (is_object($security_class))
                {
throw new SmartyException("Class '" . get_class($security_class)
                . "' must extend Smarty_Security.");
 }
if ($security_class
                == null) {
$security_class = $this->security_class;
 }
if (!class_exists($security_class))
                {
throw new SmartyException("Security class '$security_class' is not defined");
 } elseif ($security_class
                !== 'Smarty_Security' && !is_subclass_of($security_class,
                'Smarty_Security')) {
throw new SmartyException("Class '$security_class' must extend Smarty_Security.");
 } else {
 $this->security_policy = new $security_class($this);
 }
return $this;
 }
getAutoloadFilters ($type = null)
Get autoload filters
Parameters
string $type type of filter to get autoloads for. Defaults to all autoload filters
Returns
array array('type1' => array('filter1', 'filter2', …)) or array('filter1', 'filter2', …) if $type was specified
Definition at line 1148 of file Smarty.class.php.
References $autoload_filters.
 {
if ($type !== null) {
return isset($this->autoload_filters[$type]) ? $this->autoload_filters[$type]
                : array();
 }
return $this->autoload_filters;
 }
getCacheDir ()
Get cache directory
Returns
string path of cache directory
Definition at line 1051 of file Smarty.class.php.
References $cache_dir.
Referenced by Smarty_Internal_CacheResource_File\clear(), and Smarty_Internal_Utility\testInstall().
 {
return $this->cache_dir;
 }
getCompileDir ()
Get compiled directory
Returns
string path to compiled templates
Definition at line 1026 of file Smarty.class.php.
References $compile_dir.
Referenced by Smarty_Internal_Utility\clearCompiledTemplate(), and Smarty_Internal_Utility\testInstall().
 {
return $this->compile_dir;
 }
getConfigDir ($index = null)
Get config directory
Parameters
mixed index of directory to get, null to get all
Returns
array|string configuration directory
Definition at line 940 of file Smarty.class.php.
References $config_dir.
Referenced by Smarty_Internal_Utility\compileAllConfig(), and Smarty_Internal_Utility\testInstall().
 {
if ($index !== null) {
return isset($this->config_dir[$index]) ? $this->config_dir[$index]
                : null;
 }
return (array)$this->config_dir;
 }
getDebugTemplate ()
return name of debugging template
Returns
string
Definition at line 1162 of file Smarty.class.php.
References $debug_tpl.
 {
return $this->debug_tpl;
 }
getDefaultModifiers ()
Get default modifiers
Returns
array list of default modifiers
Definition at line 1090 of file Smarty.class.php.
References $default_modifiers.
 {
return $this->default_modifiers;
 }
getGlobal ($varname = null)
Returns a single or all global variables
Parameters
object $smarty
string $varname variable name or null
Returns
string variable value or or array of variables
Definition at line 727 of file Smarty.class.php.
 {
if (isset($varname)) {
if (isset(self::$global_tpl_vars[$varname])) {
return self::$global_tpl_vars[$varname]->value;
 } else {
return '';
 }
 } else {
 $_result = array();
foreach (self::$global_tpl_vars AS $key => $var) {
 $_result[$key] = $var->value;
 }
return $_result;
 }
 }
getPluginsDir ()
Get plugin directories
Returns
array list of plugin directories
Definition at line 1001 of file Smarty.class.php.
References $plugins_dir.
Referenced by loadPlugin(), and Smarty_Internal_Utility\testInstall().
 {
return (array)$this->plugins_dir;
 }
getTags (Smarty_Internal_Template $template)
Return array of tag/attributes of all tags used by an template
Parameters
object $templae template object
Returns
array of tag/attributes
Definition at line 1367 of file Smarty.class.php.
References Smarty_Internal_Utility\getTags().
 {
return Smarty_Internal_Utility::getTags($template);
 }
getTemplateDir ($index = null)
Get template directories
Parameters
mixed index of directory to get, null to get all
Returns
array|string list of template directories, or directory of $index
Definition at line 874 of file Smarty.class.php.
References $template_dir.
Referenced by Smarty_Internal_Utility\compileAllTemplates(), and Smarty_Internal_Utility\testInstall().
 {
if ($index !== null) {
return isset($this->template_dir[$index]) ? $this->template_dir[$index]
                : null;
 }
return (array)$this->template_dir;
 }
loadPlugin ($plugin_name, $check = true)
Takes unknown classes and loads plugin files for them class name format: Smarty_PluginType_PluginName plugin filename format: plugintype.pluginname.php
Parameters
string $plugin_name class plugin name to load
bool $check check if already loaded
Returns
string |boolean filepath of loaded file or false
Definition at line 1260 of file Smarty.class.php.
References Smarty_Internal_Get_Include_Path\getIncludePath(), and getPluginsDir().
Referenced by Smarty_CacheResource\load(), and Smarty_Resource\load().
 {
// if function or class exists, exit silently (already loaded)
if ($check && (is_callable($plugin_name) ||
                class_exists($plugin_name, false))) {
return true;
 }
// Plugin name is expected to be: Smarty_[Type]_[Name]
 $_name_parts = explode('_', $plugin_name, 3);
// class name must have three parts to be valid plugin
// count($_name_parts) < 3 === !isset($_name_parts[2])
if (!isset($_name_parts[2]) ||
                strtolower($_name_parts[0]) !== 'smarty') {
throw new SmartyException("plugin {$plugin_name} is not a valid name format");
return false;
 }
// if type is "internal", get plugin from sysplugins
if (strtolower($_name_parts[1]) == 'internal') {
 $file = SMARTY_SYSPLUGINS_DIR . strtolower($plugin_name) . '.php';
if (file_exists($file)) {
 require_once($file);
return $file;
 } else {
return false;
 }
 }
// plugin filename is expected to be: [type].[name].php
 $_plugin_filename = "{$_name_parts[1]}.{$_name_parts[2]}.php";
 $_stream_resolve_include_path = function_exists('stream_resolve_include_path');
// loop through plugin dirs and find the plugin
foreach ($this->getPluginsDir()
                as $_plugin_dir) {
 $names = array(
 $_plugin_dir . $_plugin_filename,
 $_plugin_dir . strtolower($_plugin_filename),
 );
foreach ($names as $file) {
if (file_exists($file)) {
 require_once($file);
return $file;
 }
if ($this->use_include_path &&
                !preg_match('/^([\/\\\\]|[a-zA-Z]:[\/\\\\])/', $_plugin_dir))
                {
// try PHP include_path
if ($_stream_resolve_include_path) {
 $file = stream_resolve_include_path($file);
 } else {
 $file = Smarty_Internal_Get_Include_Path::getIncludePath($file);
 }
if ($file !== false) {
 require_once($file);
return $file;
 }
 }
 }
 }
// no plugin loaded
return false;
 }
static muteExpectedErrors () static
Enable error handler to mute expected messages
Returns
void
Definition at line 1435 of file Smarty.class.php.
References $_previous_error_handler.
 {
/*
            error muting is done because some people implemented custom error_handlers using
            http://php.net/set_error_handler and for some reason did not understand the following paragraph:
                It is important to remember that the standard PHP error handler is completely bypassed for the
                error types specified by error_types unless the callback function returns FALSE.
                error_reporting() settings will have no effect and your error handler will be called regardless -
                however you are still able to read the current value of error_reporting and act appropriately.
                Of particular note is that this value will be 0 if the statement that caused the error was
                prepended by the @ error-control operator.
            Smarty deliberately uses @filemtime() over file_exists() and filemtime() in some places. Reasons include
                - @filemtime() is almost twice as fast as using an additional file_exists()
                - between file_exists() and filemtime() a possible race condition is opened,
                  which does not exist using the simple @filemtime() approach.
        */
 $error_handler = array('Smarty', 'mutingErrorHandler');
 $previous = set_error_handler($error_handler);
// avoid dead loops
if ($previous !== $error_handler) {
Smarty::$_previous_error_handler
                = $previous;
 }
 }
static mutingErrorHandler ($errno, $errstr, $errfile, $errline, $errcontext) static
Error Handler to mute expected messages
integer $errno Error level boolean
Definition at line 1390 of file Smarty.class.php.
References $_muted_directories, and $_previous_error_handler.
 {
 $_is_muted_directory = false;
// add the SMARTY_DIR to the list of muted directories
if (!isset(Smarty::$_muted_directories[SMARTY_DIR]))
                {
 $smarty_dir = realpath(SMARTY_DIR);
Smarty::$_muted_directories[SMARTY_DIR]
                = array(
'file' => $smarty_dir,
'length' => strlen($smarty_dir),
 );
 }
// walk the muted directories and test against $errfile
foreach (Smarty::$_muted_directories
                as $key => &$dir) {
if (!$dir) {
// resolve directory and length for speedy comparisons
 $file = realpath($key);
 $dir = array(
'file' => $file,
'length' => strlen($file),
 );
 }
if (!strncmp($errfile, $dir['file'],
                $dir['length'])) {
 $_is_muted_directory = true;
break;
 }
 }
// pass to next error handler if this error did not occur inside SMARTY_DIR
// or the error was within smarty but masked to be ignored
if (!$_is_muted_directory || ($errno && $errno
                & error_reporting())) {
if (Smarty::$_previous_error_handler)
                {
return call_user_func(Smarty::$_previous_error_handler,
                $errno, $errstr, $errfile, $errline, $errcontext);
 } else {
return false;
 }
 }
 }
setAutoloadFilters ($filters, $type = null)
Set autoload filters
Parameters
array $filters filters to load automatically
string $type "pre", "output", … specify the filter type to set. Defaults to none treating $filters' keys as the appropriate types
Returns
Smarty current Smarty instance for chaining
Definition at line 1103 of file Smarty.class.php.
 {
if ($type !== null) {
 $this->autoload_filters[$type] = (array)$filters;
 } else {
 $this->autoload_filters = (array)$filters;
 }
return $this;
 }
setCacheDir ($cache_dir)
Set cache directory
Parameters
string $cache_dir directory to store cached templates in
Returns
Smarty current Smarty instance for chaining
Definition at line 1037 of file Smarty.class.php.
References $_muted_directories, and $cache_dir.
 {
 $this->cache_dir = rtrim($cache_dir,
                '/\\') . DS;
if (!isset(Smarty::$_muted_directories[$this->cache_dir]))
                {
Smarty::$_muted_directories[$this->cache_dir] =
                null;
 }
return $this;
 }
setCompileDir ($compile_dir)
Set compile directory
Parameters
string $compile_dir directory to store compiled templates in
Returns
Smarty current Smarty instance for chaining
Definition at line 1012 of file Smarty.class.php.
References $_muted_directories, and $compile_dir.
 {
 $this->compile_dir = rtrim($compile_dir,
                '/\\') . DS;
if (!isset(Smarty::$_muted_directories[$this->compile_dir]))
                {
Smarty::$_muted_directories[$this->compile_dir] =
                null;
 }
return $this;
 }
setConfigDir ($config_dir)
Set config directory
Parameters
string | array $template_dir directory(s) of configuration sources
Returns
Smarty current Smarty instance for chaining
Definition at line 889 of file Smarty.class.php.
References $config_dir.
 {
 $this->config_dir = array();
foreach ((array)$config_dir
                as $k => $v) {
 $this->config_dir[$k] = rtrim($v, '/\\') .
                DS;
 }
 $this->joined_config_dir = join(DIRECTORY_SEPARATOR, $this->config_dir);
return $this;
 }
setDebugTemplate ($tpl_name)
set the debug template
Parameters
string $tpl_name
Returns
Smarty current Smarty instance for chaining
Exceptions
SmartyException if file is not readable
Definition at line 1174 of file Smarty.class.php.
 {
if (!is_readable($tpl_name)) {
throw new SmartyException("Unknown file '{$tpl_name}'");
 }
 $this->debug_tpl = $tpl_name;
return $this;
 }
setDefaultModifiers ($modifiers)
Set default modifiers
Parameters
array | string $modifiers modifier or list of modifiers to set
Returns
Smarty current Smarty instance for chaining
Definition at line 1062 of file Smarty.class.php.
 {
 $this->default_modifiers = (array)$modifiers;
return $this;
 }
setPluginsDir ($plugins_dir)
Set plugins directory
Parameters
string | array $plugins_dir directory(s) of plugins
Returns
Smarty current Smarty instance for chaining
Definition at line 955 of file Smarty.class.php.
References $plugins_dir.
 {
 $this->plugins_dir = array();
foreach ((array)$plugins_dir
                as $k => $v) {
 $this->plugins_dir[$k] = rtrim($v, '/\\') .
                DS;
 }
return $this;
 }
setTemplateDir ($template_dir)
Set template directory
Parameters
string | array $template_dir directory(s) of template sources
Returns
Smarty current Smarty instance for chaining
Definition at line 823 of file Smarty.class.php.
References $template_dir.
Referenced by __construct().
 {
 $this->template_dir = array();
foreach ((array)$template_dir
                as $k => $v) {
 $this->template_dir[$k] = rtrim($v, '/\\')
                . DS;
 }
 $this->joined_template_dir = join(DIRECTORY_SEPARATOR, $this->template_dir);
return $this;
 }
templateExists ($resource_name)
Check if a template resource exists
Parameters
string $resource_name template name
Returns
boolean status
Definition at line 709 of file Smarty.class.php.
References $template_objects.
Referenced by SmartyBC\template_exists().
 {
// create template object
 $save = $this->template_objects;
 $tpl = new $this->template_class($resource_name, $this);
// check if it does exists
 $result = $tpl->source->exists;
 $this->template_objects = $save;
return $result;
 }
testInstall (& $errors = null)
Run installation test
Parameters
array $errors Array to write errors into, rather than outputting them
Returns
boolean true if setup is fine, false if something is wrong
Definition at line 1378 of file Smarty.class.php.
References Smarty_Internal_Utility\testInstall().
 {
return Smarty_Internal_Utility::testInstall($this,
                $errors);
 }
static unmuteExpectedErrors () static
Disable error handler muting expected messages
Returns
void
Definition at line 1467 of file Smarty.class.php.
 {
 restore_error_handler();
 }
Field Documentation
$_cacheresource_handlers = array()
Definition at line 543 of file Smarty.class.php.
$_CHARSET = SMARTY_RESOURCE_CHAR_SET static
The character set to adhere to (e.g. "UTF-8")
Definition at line 183 of file Smarty.class.php.
Referenced by __construct(), Smarty_Internal_Compile_Private_Print_Expression\compile(), smarty_modifier_capitalize(), smarty_modifier_debug_print_var(), smarty_modifier_escape(), smarty_modifier_truncate(), smarty_modifiercompiler_count_characters(), smarty_modifiercompiler_escape(), smarty_modifiercompiler_from_charset(), smarty_modifiercompiler_lower(), smarty_modifiercompiler_to_charset(), smarty_modifiercompiler_unescape(), smarty_modifiercompiler_upper(), and smarty_variablefilter_htmlspecialchars().
$_current_file = null
Definition at line 593 of file Smarty.class.php.
$_DATE_FORMAT = SMARTY_RESOURCE_DATE_FORMAT static
The date format to be used internally (accepts date() and strftime())
Definition at line 188 of file Smarty.class.php.
Referenced by smarty_modifier_date_format().
$_dir_perms = 0771
Definition at line 578 of file Smarty.class.php.
$_file_perms = 0644
Definition at line 573 of file Smarty.class.php.
$_IS_WINDOWS = false static
Flag denoting if operating system is windows
Definition at line 197 of file Smarty.class.php.
Referenced by Smarty_Internal_Write_File\writeFile().
$_MBSTRING = SMARTY_MBSTRING static
Flag denoting if Multibyte String functions are available
Definition at line 179 of file Smarty.class.php.
Referenced by smarty_block_textformat(), smarty_modifier_capitalize(), smarty_modifier_debug_print_var(), smarty_modifier_escape(), smarty_modifier_replace(), smarty_modifier_truncate(), smarty_modifiercompiler_count_words(), smarty_modifiercompiler_escape(), smarty_modifiercompiler_from_charset(), smarty_modifiercompiler_lower(), smarty_modifiercompiler_to_charset(), smarty_modifiercompiler_unescape(), smarty_modifiercompiler_upper(), and smarty_modifiercompiler_wordwrap().
$_muted_directories = array() static
contains directories outside of SMARTY_DIR that are to be muted by muteExpectedErrors()
Definition at line 175 of file Smarty.class.php.
Referenced by mutingErrorHandler(), setCacheDir(), and setCompileDir().
$_parserdebug = false
Definition at line 598 of file Smarty.class.php.
$_previous_error_handler = null static
error handler returned by set_error_hanlder() in Smarty::muteExpectedErrors()
Definition at line 171 of file Smarty.class.php.
Referenced by muteExpectedErrors(), and mutingErrorHandler().
$_resource_handlers = array()
Definition at line 533 of file Smarty.class.php.
$_smarty_vars = array() static
Definition at line 563 of file Smarty.class.php.
$_tag_stack = array()
Definition at line 583 of file Smarty.class.php.
$_UTF8_MODIFIER = 'u' static
Flag denoting if PCRE should run in UTF-8 mode
Definition at line 192 of file Smarty.class.php.
Referenced by smarty_block_textformat(), smarty_function_html_checkboxes_output(), smarty_function_html_radios_output(), smarty_modifier_capitalize(), smarty_modifier_spacify(), smarty_modifier_truncate(), smarty_modifiercompiler_count_characters(), smarty_modifiercompiler_count_sentences(), smarty_modifiercompiler_count_words(), and smarty_modifiercompiler_strip().
$allow_ambiguous_resources = false
Definition at line 287 of file Smarty.class.php.
$allow_php_templates = false
Definition at line 361 of file Smarty.class.php.
$auto_literal = true
Definition at line 207 of file Smarty.class.php.
$autoload_filters = array()
Definition at line 548 of file Smarty.class.php.
Referenced by getAutoloadFilters().
$cache_dir = null private
Definition at line 262 of file Smarty.class.php.
Referenced by getCacheDir(), and setCacheDir().
$cache_id = null
Definition at line 314 of file Smarty.class.php.
Referenced by SmartyBC\clear_cache(), clearCache(), createTemplate(), and SmartyBC\is_cached().
$cache_lifetime = 3600
Definition at line 302 of file Smarty.class.php.
$cache_locking = false
Definition at line 450 of file Smarty.class.php.
$cache_modified_check = false
Definition at line 498 of file Smarty.class.php.
$caching = false
Definition at line 292 of file Smarty.class.php.
$caching_type = 'file'
Definition at line 478 of file Smarty.class.php.
$compile_check = true
Definition at line 277 of file Smarty.class.php.
$compile_dir = null private
Definition at line 252 of file Smarty.class.php.
Referenced by getCompileDir(), and setCompileDir().
$compile_id = null
Definition at line 321 of file Smarty.class.php.
Referenced by SmartyBC\clear_cache(), SmartyBC\clear_compiled_tpl(), clearCache(), clearCompiledTemplate(), createTemplate(), and SmartyBC\is_cached().
$compile_locking = true
Definition at line 445 of file Smarty.class.php.
$config_booleanize = true
Definition at line 428 of file Smarty.class.php.
$config_dir = array() private
Definition at line 267 of file Smarty.class.php.
Referenced by addConfigDir(), getConfigDir(), and setConfigDir().
$config_overwrite = true
Definition at line 423 of file Smarty.class.php.
$config_read_hidden = false
Definition at line 433 of file Smarty.class.php.
$debug_tpl = null
Definition at line 403 of file Smarty.class.php.
Referenced by getDebugTemplate().
$debugging = false
Definition at line 380 of file Smarty.class.php.
$debugging_ctrl = 'NONE'
Definition at line 389 of file Smarty.class.php.
$default_config_handler_func = null
Definition at line 242 of file Smarty.class.php.
$default_config_type = 'file'
Definition at line 488 of file Smarty.class.php.
$default_modifiers = array()
Definition at line 553 of file Smarty.class.php.
Referenced by getDefaultModifiers().
$default_plugin_handler_func = null
Definition at line 247 of file Smarty.class.php.
$default_resource_type = 'file'
Definition at line 470 of file Smarty.class.php.
$default_template_handler_func = null
Definition at line 237 of file Smarty.class.php.
$direct_access_security = true
Should compiled-templates be prevented from being called directly?
{
Definition at line 371 of file Smarty.class.php.
$error_reporting = null
Definition at line 408 of file Smarty.class.php.
$error_unassigned = false
Definition at line 212 of file Smarty.class.php.
$escape_html = false
Definition at line 558 of file Smarty.class.php.
$force_cache = false
Definition at line 307 of file Smarty.class.php.
$force_compile = false
Definition at line 272 of file Smarty.class.php.
Referenced by compileAllConfig(), and compileAllTemplates().
$get_used_tags = false
Definition at line 413 of file Smarty.class.php.
$global_tpl_vars = array() static
#@- assigned global tpl vars
Definition at line 166 of file Smarty.class.php.
Referenced by Smarty_Internal_Data\assignGlobal(), Smarty_Internal_TemplateBase\fetch(), Smarty_Internal_Debug\get_debug_vars(), Smarty_Internal_Template\getSubTemplate(), Smarty_Internal_Data\getTemplateVars(), Smarty_Internal_Data\getVariable(), and Smarty_Internal_Template\setupInlineSubTemplate().
$joined_config_dir = null
Definition at line 232 of file Smarty.class.php.
$joined_template_dir = null
Definition at line 227 of file Smarty.class.php.
$left_delimiter = "{"
Definition at line 326 of file Smarty.class.php.
$locking_timeout = 10
Definition at line 455 of file Smarty.class.php.
$merge_compiled_includes = false
Definition at line 297 of file Smarty.class.php.
$merged_templates_func = array()
Definition at line 604 of file Smarty.class.php.
$php_handling = self::PHP_PASSTHRU
Definition at line 355 of file Smarty.class.php.
$plugin_search_order = array('function', 'block', 'compiler', 'class')
Definition at line 508 of file Smarty.class.php.
$plugins_dir = array() private
Definition at line 257 of file Smarty.class.php.
Referenced by addPluginsDir(), getPluginsDir(), and setPluginsDir().
$properties = array()
Definition at line 483 of file Smarty.class.php.
$registered_cache_resources = array()
Definition at line 538 of file Smarty.class.php.
$registered_classes = array()
Definition at line 518 of file Smarty.class.php.
$registered_filters = array()
Definition at line 523 of file Smarty.class.php.
$registered_objects = array()
Definition at line 513 of file Smarty.class.php.
$registered_plugins = array()
Definition at line 503 of file Smarty.class.php.
$registered_resources = array()
Definition at line 528 of file Smarty.class.php.
$right_delimiter = "}"
Definition at line 331 of file Smarty.class.php.
$security_class = 'Smarty_Security'
Definition at line 343 of file Smarty.class.php.
Referenced by enableSecurity().
$security_policy = null
Definition at line 349 of file Smarty.class.php.
$smarty
Definition at line 588 of file Smarty.class.php.
$smarty_debug_id = 'SMARTY_DEBUG'
Definition at line 398 of file Smarty.class.php.
$start_time = 0
Definition at line 568 of file Smarty.class.php.
$template_dir = array() private
Definition at line 222 of file Smarty.class.php.
Referenced by addTemplateDir(), getTemplateDir(), and setTemplateDir().
$template_functions = array()
Definition at line 463 of file Smarty.class.php.
$template_objects = array()
Definition at line 493 of file Smarty.class.php.
Referenced by templateExists().
$use_include_path = false
Definition at line 217 of file Smarty.class.php.
$use_sub_dirs = false
Definition at line 282 of file Smarty.class.php.
const CACHING_LIFETIME_CURRENT = 1
Definition at line 130 of file Smarty.class.php.
Referenced by Smarty_Internal_Template\__construct(), Smarty_Template_Cached\__construct(), Smarty_Internal_Compile_Include\compile(), Smarty_Internal_TemplateBase\fetch(), and Smarty_Internal_Template\writeCachedContent().
const CACHING_LIFETIME_SAVED = 2
Definition at line 131 of file Smarty.class.php.
Referenced by Smarty_Template_Cached\__construct(), Smarty_Internal_TemplateBase\fetch(), and Smarty_Internal_Template\writeCachedContent().
const CACHING_OFF = 0
define caching modes
Definition at line 129 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Include\compile().
const COMPILECHECK_CACHEMISS = 2
Definition at line 137 of file Smarty.class.php.
const COMPILECHECK_OFF = 0
define compile check modes
Definition at line 135 of file Smarty.class.php.
const COMPILECHECK_ON = 1
Definition at line 136 of file Smarty.class.php.
const FILTER_OUTPUT = 'output'
Definition at line 150 of file Smarty.class.php.
const FILTER_POST = 'post'
filter types
Definition at line 148 of file Smarty.class.php.
const FILTER_PRE = 'pre'
Definition at line 149 of file Smarty.class.php.
const FILTER_VARIABLE = 'variable'
Definition at line 151 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Private_Print_Expression\compile(), and Smarty_Internal_Compile_Private_Print_Expression\compile_output_filter().
const PHP_ALLOW = 3
Definition at line 144 of file Smarty.class.php.
Referenced by Smarty_Internal_Templateparser\yy_r10(), Smarty_Internal_Templateparser\yy_r7(), Smarty_Internal_Templateparser\yy_r8(), and Smarty_Internal_Templateparser\yy_r9().
const PHP_PASSTHRU = 0
modes for handling of "<?php ... ?>" tags in templates.
Definition at line 141 of file Smarty.class.php.
Referenced by Smarty_Internal_Templateparser\yy_r10(), Smarty_Internal_Templateparser\yy_r7(), Smarty_Internal_Templateparser\yy_r8(), and Smarty_Internal_Templateparser\yy_r9().
const PHP_QUOTE = 1
Definition at line 142 of file Smarty.class.php.
Referenced by Smarty_Internal_Templateparser\yy_r10(), Smarty_Internal_Templateparser\yy_r7(), Smarty_Internal_Templateparser\yy_r8(), and Smarty_Internal_Templateparser\yy_r9().
const PHP_REMOVE = 2
Definition at line 143 of file Smarty.class.php.
Referenced by Smarty_Internal_Templateparser\yy_r10(), Smarty_Internal_Templateparser\yy_r7(), Smarty_Internal_Templateparser\yy_r8(), and Smarty_Internal_Templateparser\yy_r9().
const PLUGIN_BLOCK = 'block'
Definition at line 156 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Private_Registered_Block\compile(), and Smarty_Internal_TemplateCompilerBase\compileTag().
const PLUGIN_COMPILER = 'compiler'
Definition at line 157 of file Smarty.class.php.
Referenced by Smarty_Internal_TemplateCompilerBase\compileTag().
const PLUGIN_FUNCTION = 'function'
plugin types
Definition at line 155 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Private_Registered_Function\compile(), and Smarty_Internal_TemplateCompilerBase\compileTag().
const PLUGIN_MODIFIER = 'modifier'
Definition at line 158 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Private_Modifier\compile().
const PLUGIN_MODIFIERCOMPILER = 'modifiercompiler'
Definition at line 159 of file Smarty.class.php.
const SCOPE_GLOBAL = 3
Definition at line 125 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Assign\compile(), Smarty_Internal_Compile_Include\compile(), Smarty_Internal_Template\getSubTemplate(), and Smarty_Internal_Template\setupInlineSubTemplate().
const SCOPE_LOCAL = 0
define variable scopes
Definition at line 122 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Assign\compile(), Smarty_Internal_Compile_Include\compile(), Smarty_Internal_Template\getSubTemplate(), and Smarty_Internal_Template\setupInlineSubTemplate().
const SCOPE_PARENT = 1
Definition at line 123 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Assign\compile(), Smarty_Internal_Compile_Include\compile(), Smarty_Internal_Template\getSubTemplate(), and Smarty_Internal_Template\setupInlineSubTemplate().
const SCOPE_ROOT = 2
Definition at line 124 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Assign\compile(), and Smarty_Internal_Compile_Include\compile().
const SMARTY_VERSION = 'Smarty-3.1.12'
#@+ constant definitions smarty version
Definition at line 117 of file Smarty.class.php.
Referenced by Smarty_Internal_Compile_Private_Special_Variable\compile(), Smarty_Internal_TemplateCompilerBase\compileTemplate(), Smarty_Internal_Template\createTemplateCodeFrame(), and smarty_function_fetch().
The documentation for this class was generated from the following file:
Smarty.class.php