oSocial: errorHandler Class Reference
errorHandler Class Reference
Public Member Functions
__construct ()
queryError ()
isNullError ()
isNotArrayError ()
isNotRequiredVariableType ()
queryMultipleResults ()
errorMSG ($string=null)
successMSG ($string=null)
Private Member Functions
getCaller ($what=NULL)
Private Attributes
$db = null
$core = null
Detailed Description
Hiba kezelő osztály
Definition at line 13 of file class.errorHandler.php.
Constructor & Destructor Documentation
__construct ()
Szükséges osztályok betöltése
Definition at line 33 of file class.errorHandler.php.
References $dbInstance, and database\getInstance().
 {
if (is_null($this->db)) {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 }
if (is_null($this->core)) {
 $this->core = new coreFunctions();
 }
 }
Member Function Documentation
errorMSG ($string = null)
Parameters
null $string A HIBA ÜZENET
Definition at line 133 of file class.errorHandler.php.
Referenced by isNotArrayError(), isNotRequiredVariableType(), isNullError(), queryError(), and queryMultipleResults().
 {
 $string = $this->core->cleanVar($string);
 ?>
    <div class="msg error">
        <p><strong><?php echo gettext('ERROR')
                ?>: </strong> <?php echo $string ?></p>
    </div>
    <?php
 }
getCaller ($what = NULL) private
Created and shared by Paul Gobée at http://stackoverflow.com/a/12463381/1012431
Gets the caller of the function where this function is called from
Parameters
string what to return? (Leave empty to get all, or specify: "class", "function", "line", "class", etc.) - options see: http://php.net/manual/en/function.debug-backtrace.php
Returns
mixed
Definition at line 52 of file class.errorHandler.php.
Referenced by isNotArrayError(), isNotRequiredVariableType(), isNullError(), queryError(), and queryMultipleResults().
 {
 $trace = debug_backtrace();
 $previousCall = $trace[2]; // 0 is this call, 1 is call in previous function, 2 is caller of that function
if (isset($what)) {
return $previousCall[$what];
 } else {
return $previousCall;
 }
 }
isNotArrayError ()
Az adatbázis hibához hasonlóan specifikus hibát jelenít meg
Definition at line 100 of file class.errorHandler.php.
References errorMSG(), and getCaller().
 {
 $caller = $this->getCaller();
 $errorInfo = $this->db->errorInfo();
 $msg = gettext('ERROR_REQUIRED_NOT_ARRAY') .
                '->' . $caller['class'] . '->' . $caller['function'];
 $this->errorMSG($msg);
 }
isNotRequiredVariableType ()
Az adatbázis hibához hasonlóan specifikus hibát jelenít meg
Definition at line 111 of file class.errorHandler.php.
References errorMSG(), and getCaller().
 {
 $caller = $this->getCaller();
 $errorInfo = $this->db->errorInfo();
 $msg = gettext('ERROR_NOT_EXPECTED_VAR_TYPE')
                . '->' . $caller['class']
                . '->' . $caller['function'];
 $this->errorMSG($msg);
 }
isNullError ()
Az adatbázis hibához hasonlóan specifikus hibát jelenít meg
Definition at line 89 of file class.errorHandler.php.
References errorMSG(), and getCaller().
 {
 $caller = $this->getCaller();
 $errorInfo = $this->db->errorInfo();
 $msg = gettext('ERROR_REQUIRED_IS_NULL') .
                'NULL hiba->' . $caller['class']
                . '->' . $caller['function'];
 $this->errorMSG($msg);
 }
queryError ()
Adatbázis hiba megjelenítés! Az errorMSG() több infóval szolgál a megjelenítés miatt
Definition at line 68 of file class.errorHandler.php.
References errorMSG(), and getCaller().
 {
 $caller = $this->getCaller();
 $errorInfo = $this->db->errorInfo();
 $msg = gettext('ERROR_QUERY_FAILED');
if (isset($caller['class']))
                {
 $msg .= '->' . $caller['class'];
 }
if (isset($caller['function']))
                {
 $msg .= '->' . $caller['function'];
 }
 $msg .= ': ' . $errorInfo[2];
 $this->errorMSG($msg);
 }
queryMultipleResults ()
Az adatbázis hibához hasonlóan specifikus hibát jelenít meg
Definition at line 122 of file class.errorHandler.php.
References errorMSG(), and getCaller().
 {
 $caller = $this->getCaller();
 $errorInfo = $this->db->errorInfo();
 $msg = gettext('ERROR_MULTIPLE_QUERY_RESULTS')
                . '->' . $caller['class']
                . '->' . $caller['function'];
 $this->errorMSG($msg);
 }
successMSG ($string = null)
Parameters
string $string A HIBA ÜZENET
Definition at line 146 of file class.errorHandler.php.
 {
 $string = $this->core->clean_var($string);
 ?>
    <div class="msg success">
        <p><strong><?php echo gettext('SUCCESS')
                ?>: </strong> <?php echo $string ?></p>
    </div>
    <?php
 }
Field Documentation
$core = null private
Definition at line 28 of file class.errorHandler.php.
$db = null private
Definition at line 21 of file class.errorHandler.php.
The documentation for this class was generated from the following file:
class.errorHandler.php