oSocial: userProfile Class Reference
userProfile Class Reference
Public Member Functions
__construct ($userID=null)
renderUserProfile ($uid=null)
renderCurrentUserProfile ()
Private Member Functions
setUserID ($userID=null)
getUserData ($uid=null)
Private Attributes
$db = null
$core = null
$error = null
$var = null
$avatar = null
$siteLang = null
$userID = null
Detailed Description
Definition at line 13 of file class.userProfile.php.
Constructor & Destructor Documentation
__construct ($userID = null)
Definition at line 48 of file class.userProfile.php.
References $dbInstance, and database\getInstance().
 {
if (is_null($this->db)) {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 }
if (is_null($this->core)) {
 $this->core = new coreFunctions();
 }
if (is_null($this->error)) {
 $this->error = new errorHandler();
 }
if (is_null($this->var)) {
 $this->var = new varGetter();
 }
if (is_null($this->avatar)) {
 $this->avatar = new profilePicture();
 }
 $this->siteLang = $this->var->getSiteLang();
 }
Member Function Documentation
getUserData ($uid = null) private
Definition at line 95 of file class.userProfile.php.
References $siteLang, and $userID.
Referenced by renderUserProfile().
 {
if (is_null($uid)) {
 $uid = $this->userID;
 }
 $genderLang = 'name_' . $this->siteLang;
 $query = "SELECT user_base.id AS uid, firstName, lastName, dateOfBirth, $genderLang AS gender, userName AS email  FROM user_base
        LEFT JOIN user_details ON user_details.uid=user_base.id
        LEFT JOIN _gender ON user_details.gender=_gender.id
        WHERE user_base.id='$uid'";
if ($result = $this->db->query($query)) {
if ($result->rowCount() == 1) {
return $result->fetch();
 } else {
 $this->error->queryMultipleResults();
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 }
renderCurrentUserProfile ()
Definition at line 182 of file class.userProfile.php.
References renderUserProfile().
Referenced by overseer\control().
 {
return $this->renderUserProfile($this->var->getUserID());
 }
renderUserProfile ($uid = null)
Definition at line 127 of file class.userProfile.php.
References getUserData().
Referenced by overseer\control(), and renderCurrentUserProfile().
 {
 $data = $this->getUserData($uid);
if (is_array($data)) {
 $currentUser = $this->var->getUserID();
//var_dump($data);
 $r = null;
 $r .= '<table class="profileTable">';
 $r .= ' <tbody>';
if ($uid != $currentUser) {
 $r .= '     <tr class="userActions">';
 $r .= '         <td colspan="2">';
 $r .= 'kapcsolat';
 $r .= '         </td>';
 $r .= '     </tr>';
 }
 $r .= '     <tr>';
 $r .= '         <td>';
 $r .= '             <img src="' .
                $this->avatar->getBigProfilePic($data['email']) . '" />';
 $r .= '         </td>';
 $r .= '         <td>';
 $r .= '             <ul>';
//Csak az adat megjelenítés végett van így, normális esetben tételenként, nyelvi változóval együtt kerül megjelenítésre
foreach ($data as $key => $value) {
 $r .= '<li>';
 $r .= $key . ': ' . $value;
 $r .= '</li>';
 }
 $r .= '             </ul>';
 $r .= '         </td>';
 $r .= '     </tr>';
 $r .= ' </tbody>';
 $r .= '</table>';
return $r;
 } else {
 $this->error->isNotArrayError();
return false;
 }
 }
setUserID ($userID = null) private
Ellenőrizzük, hogy a uid egyáltalán szám -e
Parameters
null $userID
Returns
bool|int
Definition at line 80 of file class.userProfile.php.
References $userID.
 {
$userID = $this->core->cleanVar($userID);
if (is_numeric($userID))
                {
return $this->userID;
 } else {
 $this->error->isNotRequiredVariableType();
return false;
 }
 }
Field Documentation
$avatar = null private
Definition at line 39 of file class.userProfile.php.
$core = null private
Definition at line 25 of file class.userProfile.php.
$db = null private
Definition at line 19 of file class.userProfile.php.
$error = null private
Definition at line 31 of file class.userProfile.php.
$siteLang = null private
Szükséges osztályok betöltése
Definition at line 45 of file class.userProfile.php.
Referenced by getUserData().
$userID = null private
Definition at line 46 of file class.userProfile.php.
Referenced by getUserData(), and setUserID().
$var = null private
Definition at line 37 of file class.userProfile.php.
The documentation for this class was generated from the following file:
class.userProfile.php