oSocial: Smarty_Internal_Template Class Reference
Smarty_Internal_Template Class Reference
Public Member Functions
__construct ($template_resource, $smarty, $_parent=null, $_cache_id=null, $_compile_id=null, $_caching=null, $_cache_lifetime=null)
mustCompile ()
compileTemplateSource ()
writeCachedContent ($content)
getSubTemplate ($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $parent_scope)
setupInlineSubTemplate ($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $parent_scope, $hash)
createTemplateCodeFrame ($content= '', $cache=false)
decodeProperties ($properties, $cache=false)
createLocalArrayVariable ($tpl_var, $nocache=false, $scope=Smarty::SCOPE_LOCAL)
& getScope ($scope)
getScopePointer ($scope)
_count ($value)
capture_error ()
clearCache ($exp_time=null)
__set ($property_name, $value)
__get ($property_name)
__destruct ()
Public Member Functions inherited from Smarty_Internal_TemplateBase
fetch ($template=null, $cache_id=null, $compile_id=null, $parent=null, $display=false, $merge_tpl_vars=true, $no_output_filter=false)
display ($template=null, $cache_id=null, $compile_id=null, $parent=null)
isCached ($template=null, $cache_id=null, $compile_id=null, $parent=null)
createData ($parent=null)
registerPlugin ($type, $tag, $callback, $cacheable=true, $cache_attr=null)
unregisterPlugin ($type, $tag)
registerResource ($type, $callback)
unregisterResource ($type)
registerCacheResource ($type, Smarty_CacheResource $callback)
unregisterCacheResource ($type)
registerObject ($object_name, $object_impl, $allowed=array(), $smarty_args=true, $block_methods=array())
getRegisteredObject ($name)
unregisterObject ($name)
registerClass ($class_name, $class_impl)
registerDefaultPluginHandler ($callback)
registerDefaultTemplateHandler ($callback)
registerDefaultConfigHandler ($callback)
registerFilter ($type, $callback)
unregisterFilter ($type, $callback)
_get_filter_name ($function_name)
loadFilter ($type, $name)
unloadFilter ($type, $name)
__call ($name, $args)
Public Member Functions inherited from Smarty_Internal_Data
assign ($tpl_var, $value=null, $nocache=false)
assignGlobal ($varname, $value=null, $nocache=false)
assignByRef ($tpl_var, &$value, $nocache=false)
append ($tpl_var, $value=null, $merge=false, $nocache=false)
appendByRef ($tpl_var, &$value, $merge=false)
getTemplateVars ($varname=null, $_ptr=null, $search_parents=true)
clearAssign ($tpl_var)
clearAllAssign ()
configLoad ($config_file, $sections=null)
getVariable ($variable, $_ptr=null, $search_parents=true, $error_enable=true)
getConfigVariable ($variable, $error_enable=true)
getStreamVariable ($variable)
getConfigVars ($varname=null, $search_parents=true)
clearConfig ($varname=null)
Data Fields
$cache_id = null
$compile_id = null
$caching = null
$cache_lifetime = null
$template_resource = null
$mustCompile = null
$has_nocache_code = false
$properties
$required_plugins = array('compiled' => array(), 'nocache' => array())
$smarty = null
$block_data = array()
$variable_filters = array()
$used_tags = array()
$allow_relative_path = false
$_capture_stack = array(0 => array())
Detailed Description
Definition at line 22 of file smarty_internal_template.php.
Constructor & Destructor Documentation
__construct ($template_resource, $smarty, $_parent = null, $_cache_id = null, $_compile_id = null, $_caching = null, $_cache_lifetime = null)
Create template data object
Some of the global Smarty settings copied to template scope It load the required template resources and cacher plugins
Parameters
string $template_resource template resource string
Smarty $smarty Smarty instance
Smarty_Internal_Template $_parent back pointer to parent object with variables or null
mixed $_cache_id cache id or null
mixed $_compile_id compile id or null
bool $_caching use caching?
int $_cache_lifetime cache life-time in seconds
Definition at line 117 of file smarty_internal_template.php.
References $smarty, $template_resource, and Smarty\CACHING_LIFETIME_CURRENT.
 {
 $this->smarty = & $smarty;
// Smarty parameter
 $this->cache_id = $_cache_id === null ? $this->smarty->cache_id : $_cache_id;
 $this->compile_id = $_compile_id === null ? $this->smarty->compile_id :
                $_compile_id;
 $this->caching = $_caching === null ? $this->smarty->caching : $_caching;
if ($this->caching === true)
 $this->caching = Smarty::CACHING_LIFETIME_CURRENT;
 $this->cache_lifetime = $_cache_lifetime === null ? $this->smarty->cache_lifetime
                : $_cache_lifetime;
 $this->parent = $_parent;
// Template resource
 $this->template_resource = $template_resource;
// copy block data of template inheritance
if ($this->parent instanceof Smarty_Internal_Template)
                {
 $this->block_data = $this->parent->block_data;
 }
 }
__destruct ()
Template data object destrutor
Definition at line 684 of file smarty_internal_template.php.
 {
if ($this->smarty->cache_locking &&
                isset($this->cached) && $this->cached->is_locked) {
 $this->cached->handler->releaseLock($this->smarty, $this->cached);
 }
 }
Member Function Documentation
__get ($property_name)
get Smarty property in template context
Parameters
string $property_name property name
Definition at line 630 of file smarty_internal_template.php.
 {
switch ($property_name) {
case 'source':
if (strlen($this->template_resource) == 0) {
throw new SmartyException('Missing template name');
 }
 $this->source = Smarty_Resource::source($this);
// cache template object under a unique ID
// do not cache eval resources
if ($this->source->type != 'eval') {
if ($this->smarty->allow_ambiguous_resources) {
 $_templateId = $this->source->unique_resource . $this->cache_id . $this->compile_id;
 } else {
 $_templateId = $this->smarty->joined_template_dir . '#'
                . $this->template_resource . $this->cache_id . $this->compile_id;
 }
if (isset($_templateId[150])) {
 $_templateId = sha1($_templateId);
 }
 $this->smarty->template_objects[$_templateId] = $this;
 }
return $this->source;
case 'compiled':
 $this->compiled = $this->source->getCompiled($this);
return $this->compiled;
case 'cached':
if (!class_exists('Smarty_Template_Cached'))
                {
 include SMARTY_SYSPLUGINS_DIR . 'smarty_cacheresource.php';
 }
 $this->cached = new Smarty_Template_Cached($this);
return $this->cached;
case 'compiler':
 $this->smarty->loadPlugin($this->source->compiler_class);
 $this->compiler = new $this->source->compiler_class($this->source->template_lexer_class,
                $this->source->template_parser_class, $this->smarty);
return $this->compiler;
// FIXME: routing of template -> smarty attributes
default:
if (property_exists($this->smarty, $property_name)) {
return $this->smarty->$property_name;
 }
 }
throw new SmartyException("template property '$property_name' does not exist.");
 }
__set ($property_name, $value)
set Smarty property in template context
Parameters
string $property_name property name
mixed $value value
Definition at line 604 of file smarty_internal_template.php.
 {
switch ($property_name) {
case 'source':
case 'compiled':
case 'cached':
case 'compiler':
 $this->$property_name = $value;
return;
// FIXME: routing of template -> smarty attributes
default:
if (property_exists($this->smarty, $property_name)) {
 $this->smarty->$property_name = $value;
return;
 }
 }
throw new SmartyException("invalid template property '$property_name'.");
 }
_count ($value)
[util function] counts an array, arrayaccess/traversable or PDOStatement object
Parameters
mixed $value
Returns
int the count for arrays and objects that implement countable, 1 for other objects that don't, and 0 for empty elements
Definition at line 553 of file smarty_internal_template.php.
 {
if (is_array($value) === true || $value instanceof Countable) {
return count($value);
 } elseif ($value instanceof IteratorAggregate) {
// Note: getIterator() returns a Traversable, not an Iterator
// thus rewind() and valid() methods may not be present
return iterator_count($value->getIterator());
 } elseif ($value instanceof Iterator) {
return iterator_count($value);
 } elseif ($value instanceof PDOStatement) {
return $value->rowCount();
 } elseif ($value instanceof Traversable) {
return iterator_count($value);
 } elseif ($value instanceof ArrayAccess) {
if ($value->offsetExists(0)) {
return 1;
 }
 } elseif (is_object($value)) {
return count($value);
 }
return 0;
 }
capture_error ()
runtime error not matching capture tags
Definition at line 581 of file smarty_internal_template.php.
 {
throw new SmartyException("Not matching {capture} open/close in \"{$this->template_resource}\"");
 }
clearCache ($exp_time = null)
Empty cache for this template
Parameters
integer $exp_time expiration time
Returns
integer number of cache files deleted
Definition at line 592 of file smarty_internal_template.php.
 {
Smarty_CacheResource::invalidLoadedCache($this->smarty);
return $this->cached->handler->clear($this->smarty,
                $this->template_name, $this->cache_id, $this->compile_id, $exp_time);
 }
compileTemplateSource ()
Compiles the template
If the template is not evaluated the compiled template is saved on disk
Definition at line 165 of file smarty_internal_template.php.
References Smarty_Internal_Debug\end_compile(), Smarty_Internal_Debug\start_compile(), and Smarty_Internal_Write_File\writeFile().
Referenced by Smarty_Internal_Utility\getTags().
 {
if (!$this->source->recompiled) {
 $this->properties['file_dependency'] =
                array();
if ($this->source->components) {
// uses real resource for file dependency
 $source = end($this->source->components);
 $this->properties['file_dependency'][$this->source->uid]
                = array($this->source->filepath, $this->source->timestamp, $source->type);
 } else {
 $this->properties['file_dependency'][$this->source->uid]
                = array($this->source->filepath, $this->source->timestamp, $this->source->type);
 }
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::start_compile($this);
 }
// compile locking
if ($this->smarty->compile_locking &&
                !$this->source->recompiled) {
if ($saved_timestamp = $this->compiled->timestamp)
                {
 touch($this->compiled->filepath);
 }
 }
// call compiler
try {
 $code = $this->compiler->compileTemplate($this);
 } catch (Exception
                $e) {
// restore old timestamp in case of error
if ($this->smarty->compile_locking &&
                !$this->source->recompiled && $saved_timestamp) {
 touch($this->compiled->filepath, $saved_timestamp);
 }
throw $e;
 }
// compiling succeded
if (!$this->source->recompiled && $this->compiler->write_compiled_code)
                {
// write compiled template
 $_filepath = $this->compiled->filepath;
if ($_filepath === false)
throw new SmartyException('getCompiledFilepath() did not return a destination to save the compiled template to');
Smarty_Internal_Write_File::writeFile($_filepath,
                $code, $this->smarty);
 $this->compiled->exists = true;
 $this->compiled->isCompiled = true;
 }
if ($this->smarty->debugging) {
Smarty_Internal_Debug::end_compile($this);
 }
// release compiler object to free memory
 unset($this->compiler);
 }
createLocalArrayVariable ($tpl_var, $nocache = false, $scope = Smarty::SCOPE_LOCAL)
Template code runtime function to create a local Smarty variable for array assignments
Parameters
string $tpl_var tempate variable name
bool $nocache cache mode of variable
int $scope scope of variable
Definition at line 489 of file smarty_internal_template.php.
 {
if (!isset($this->tpl_vars[$tpl_var])) {
 $this->tpl_vars[$tpl_var] = new Smarty_variable(array(),
                $nocache, $scope);
 } else {
 $this->tpl_vars[$tpl_var] = clone $this->tpl_vars[$tpl_var];
if ($scope != Smarty::SCOPE_LOCAL)
                {
 $this->tpl_vars[$tpl_var]->scope = $scope;
 }
if (!(is_array($this->tpl_vars[$tpl_var]->value) ||
                $this->tpl_vars[$tpl_var]->value instanceof ArrayAccess))
                {
 settype($this->tpl_vars[$tpl_var]->value, 'array');
 }
 }
 }
createTemplateCodeFrame ($content = '', $cache = false)
Create code frame for compiled and cached templates
Parameters
string $content optional template content
bool $cache flag for cache file
Returns
string
Definition at line 338 of file smarty_internal_template.php.
References $has_nocache_code, and Smarty\SMARTY_VERSION.
Referenced by Smarty_Internal_TemplateCompilerBase\compileTemplate(), and writeCachedContent().
 {
 $plugins_string = '';
// include code for plugins
if (!$cache) {
if (!empty($this->required_plugins['compiled'])) {
 $plugins_string = '<?php ';
foreach ($this->required_plugins['compiled'] as $tmp) {
foreach ($tmp as $data) {
 $file = addslashes($data['file']);
if (is_Array($data['function']))
                {
 $plugins_string .= "if (!is_callable(array('{$data['function'][0]}','{$data['function'][1]}'))) include '{$file}';\n";
 } else {
 $plugins_string .= "if (!is_callable('{$data['function']}')) include '{$file}';\n";
 }
 }
 }
 $plugins_string .= '?>';
 }
if (!empty($this->required_plugins['nocache'])) {
 $this->has_nocache_code = true;
 $plugins_string .= "<?php echo '/*%%SmartyNocache:{$this->properties['nocache_hash']}%%*/<?php \$_smarty = \$_smarty_tpl->smarty; ";
foreach ($this->required_plugins['nocache'] as $tmp) {
foreach ($tmp as $data) {
 $file = addslashes($data['file']);
if (is_Array($data['function']))
                {
 $plugins_string .= addslashes("if (!is_callable(array('{$data['function'][0]}','{$data['function'][1]}'))) include '{$file}';\n");
 } else {
 $plugins_string .= addslashes("if (!is_callable('{$data['function']}')) include '{$file}';\n");
 }
 }
 }
 $plugins_string .= "?>/*/%%SmartyNocache:{$this->properties['nocache_hash']}%%*/';?>\n";
 }
 }
// build property code
 $this->properties['has_nocache_code'] = $this->has_nocache_code;
 $output = '';
if (!$this->source->recompiled) {
 $output = "<?php /*%%SmartyHeaderCode:{$this->properties['nocache_hash']}%%*/";
if ($this->smarty->direct_access_security) {
 $output .= "if(!defined('SMARTY_DIR')) exit('no direct access allowed');\n";
 }
 }
if ($cache) {
// remove compiled code of{function} definition
 unset($this->properties['function']);
if (!empty($this->smarty->template_functions)) {
// copy code of {function} tags called in nocache mode
foreach ($this->smarty->template_functions as $name
                => $function_data) {
if (isset($function_data['called_nocache']))
                {
foreach ($function_data['called_functions']
                as $func_name) {
 $this->smarty->template_functions[$func_name]['called_nocache']
                = true;
 }
 }
 }
foreach ($this->smarty->template_functions as $name
                => $function_data) {
if (isset($function_data['called_nocache']))
                {
 unset($function_data['called_nocache'],
                $function_data['called_functions'], $this->smarty->template_functions[$name]['called_nocache']);
 $this->properties['function'][$name] =
                $function_data;
 }
 }
 }
 }
 $this->properties['version'] = Smarty::SMARTY_VERSION;
if (!isset($this->properties['unifunc'])) {
 $this->properties['unifunc'] = 'content_' . str_replace('.', '_', uniqid('', true));
 }
if (!$this->source->recompiled) {
 $output .= "\$_valid = \$_smarty_tpl->decodeProperties("
                . var_export($this->properties, true) . ','
                . ($cache ? 'true' : 'false')
                . "); /*/%%SmartyHeaderCode%%*/?>\n";
 $output .= '<?php if ($_valid && !is_callable(\''
                . $this->properties['unifunc'] . '\')) {function ' . $this->properties['unifunc'] . '($_smarty_tpl) {?>';
        }
        $output .= $plugins_string;
        $output .= $content;
        if (!$this->source->recompiled) {
            $output .= '<?php }} ?>';
        }
        return $output;
    }
decodeProperties ($properties, $cache = false)
This function is executed automatically when a compiled or cached template file is included
Decode saved properties from compiled template and cache files
Check if compiled or cache file is valid
Parameters
array $properties special template properties
bool $cache flag if called from cache file
Returns
bool flag if compiled or cache file is valid
Definition at line 428 of file smarty_internal_template.php.
 {
 $this->has_nocache_code = $properties['has_nocache_code'];
 $this->properties['nocache_hash'] = $properties['nocache_hash'];
if (isset($properties['cache_lifetime'])) {
 $this->properties['cache_lifetime'] = $properties['cache_lifetime'];
 }
if (isset($properties['file_dependency'])) {
 $this->properties['file_dependency'] =
                array_merge($this->properties['file_dependency'], $properties['file_dependency']);
 }
if (!empty($properties['function'])) {
 $this->properties['function'] =
                array_merge($this->properties['function'], $properties['function']);
 $this->smarty->template_functions = array_merge($this->smarty->template_functions,
                $properties['function']);
 }
 $this->properties['version'] = (isset($properties['version'])) ? $properties['version'] : '';
 $this->properties['unifunc'] = $properties['unifunc'];
// check file dependencies at compiled code
 $is_valid = true;
if ($this->properties['version']
                != Smarty::SMARTY_VERSION)
                {
 $is_valid = false;
 } else if (((!$cache
                && $this->smarty->compile_check && empty($this->compiled->_properties) &&
                !$this->compiled->isCompiled) || $cache && ($this->smarty->compile_check === true || $this->smarty->compile_check === Smarty::COMPILECHECK_ON))
                && !empty($this->properties['file_dependency'])) {
foreach ($this->properties['file_dependency'] as $_file_to_check) {
if ($_file_to_check[2] == 'file'
                || $_file_to_check[2] == 'php') {
if ($this->source->filepath == $_file_to_check[0]
                && isset($this->source->timestamp)) {
// do not recheck current template
 $mtime = $this->source->timestamp;
 } else {
// file and php types can be checked without loading the respective resource handlers
 $mtime = @filemtime($_file_to_check[0]);
 }
 } elseif ($_file_to_check[2] == 'string') {
continue;
 } else {
 $source = Smarty_Resource::source(null,
                $this->smarty, $_file_to_check[0]);
 $mtime = $source->timestamp;
 }
if (!$mtime || $mtime > $_file_to_check[1]) {
 $is_valid = false;
break;
 }
 }
 }
if ($cache) {
 $this->cached->valid = $is_valid;
 } else {
 $this->mustCompile
                = !$is_valid;
 }
// store data in reusable Smarty_Template_Compiled
if (!$cache) {
 $this->compiled->_properties = $properties;
 }
return $is_valid;
 }
& getScope ($scope)
Template code runtime function to get pointer to template variable array of requested scope
Parameters
int $scope requested variable scope
Returns
array array of template variables
Definition at line 510 of file smarty_internal_template.php.
 {
if ($scope == Smarty::SCOPE_PARENT
                && !empty($this->parent)) {
return $this->parent->tpl_vars;
 } elseif ($scope == Smarty::SCOPE_ROOT
                && !empty($this->parent)) {
 $ptr = $this->parent;
while (!empty($ptr->parent)) {
 $ptr = $ptr->parent;
 }
return $ptr->tpl_vars;
 } elseif ($scope == Smarty::SCOPE_GLOBAL)
                {
return Smarty::$global_tpl_vars;
 }
 $null = null;
return $null;
 }
getScopePointer ($scope)
Get parent or root of template parent chain
Parameters
int $scope pqrent or root scope
Returns
mixed object
Definition at line 533 of file smarty_internal_template.php.
Referenced by getSubTemplate(), and setupInlineSubTemplate().
 {
if ($scope == Smarty::SCOPE_PARENT
                && !empty($this->parent)) {
return $this->parent;
 } elseif ($scope == Smarty::SCOPE_ROOT
                && !empty($this->parent)) {
 $ptr = $this->parent;
while (!empty($ptr->parent)) {
 $ptr = $ptr->parent;
 }
return $ptr;
 }
return null;
 }
getSubTemplate ($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $parent_scope)
Template code runtime function to get subtemplate content
Parameters
string $template the resource handle of the template file
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
integer $caching cache mode
integer $cache_lifetime life time of cache data
array $vars optional variables to assign
int $parent_scope scope in which {include} should execute
Returns
string template content
Definition at line 246 of file smarty_internal_template.php.
References $cache_id, $cache_lifetime, $caching, $compile_id, Smarty_Internal_Data\$config_vars, Smarty\$global_tpl_vars, Smarty_Internal_Data\$tpl_vars, getScopePointer(), Smarty_Resource\getUniqueTemplateName(), Smarty\SCOPE_GLOBAL, Smarty\SCOPE_LOCAL, and Smarty\SCOPE_PARENT.
 {
// already in template cache?
if ($this->smarty->allow_ambiguous_resources) {
 $_templateId = Smarty_Resource::getUniqueTemplateName($this->smarty,
                $template) . $cache_id
                . $compile_id;
 } else {
 $_templateId = $this->smarty->joined_template_dir . '#'
                . $template . $cache_id
                . $compile_id;
 }
if (isset($_templateId[150])) {
 $_templateId = sha1($_templateId);
 }
if (isset($this->smarty->template_objects[$_templateId]))
                {
// clone cached template object because of possible recursive call
 $tpl = clone $this->smarty->template_objects[$_templateId];
 $tpl->parent = $this;
 $tpl->caching = $caching;
 $tpl->cache_lifetime = $cache_lifetime;
 } else {
 $tpl = new $this->smarty->template_class($template,
                $this->smarty, $this, $cache_id,
                $compile_id,
                $caching,
                $cache_lifetime);
 }
// get variables from calling scope
if ($parent_scope == Smarty::SCOPE_LOCAL)
                {
 $tpl->tpl_vars = $this->tpl_vars;
 $tpl->tpl_vars['smarty'] = clone $this->tpl_vars['smarty'];
 } elseif ($parent_scope == Smarty::SCOPE_PARENT)
                {
 $tpl->tpl_vars = & $this->tpl_vars;
 } elseif ($parent_scope == Smarty::SCOPE_GLOBAL)
                {
 $tpl->tpl_vars = & Smarty::$global_tpl_vars;
 } elseif (($scope_ptr = $this->getScopePointer($parent_scope))
                == null) {
 $tpl->tpl_vars = & $this->tpl_vars;
 } else {
 $tpl->tpl_vars = & $scope_ptr->tpl_vars;
 }
 $tpl->config_vars = $this->config_vars;
if (!empty($data)) {
// set up variable values
foreach ($data as $_key => $_val) {
 $tpl->tpl_vars[$_key] = new Smarty_variable($_val);
 }
 }
return $tpl->fetch(null, null, null, null, false, false, true);
 }
mustCompile ()
Returns if the current template must be compiled by the Smarty compiler
It does compare the timestamps of template source and the compiled templates and checks the force compile configuration
Returns
boolean true if the template must be compiled
Definition at line 143 of file smarty_internal_template.php.
References $mustCompile.
 {
if (!$this->source->exists) {
if ($this->parent instanceof Smarty_Internal_Template)
                {
 $parent_resource = " in '$this->parent->template_resource}'";
 } else {
 $parent_resource = '';
 }
throw new SmartyException("Unable to load template {$this->source->type} '{$this->source->name}'{$parent_resource}");
 }
if ($this->mustCompile
                === null) {
 $this->mustCompile
                = (!$this->source->uncompiled && ($this->smarty->force_compile || $this->source->recompiled
                || $this->compiled->timestamp === false ||
 ($this->smarty->compile_check && $this->compiled->timestamp <
                $this->source->timestamp)));
 }
return $this->mustCompile;
 }
setupInlineSubTemplate ($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $parent_scope, $hash)
Template code runtime function to set up an inline subtemplate
Parameters
string $template the resource handle of the template file
mixed $cache_id cache id to be used with this template
mixed $compile_id compile id to be used with this template
integer $caching cache mode
integer $cache_lifetime life time of cache data
array $vars optional variables to assign
int $parent_scope scope in which {include} should execute
string $hash nocache hash code
Returns
string template content
Definition at line 303 of file smarty_internal_template.php.
References $cache_id, $cache_lifetime, $caching, $compile_id, Smarty_Internal_Data\$config_vars, Smarty\$global_tpl_vars, Smarty_Internal_Data\$tpl_vars, getScopePointer(), Smarty\SCOPE_GLOBAL, Smarty\SCOPE_LOCAL, and Smarty\SCOPE_PARENT.
 {
 $tpl = new $this->smarty->template_class($template,
                $this->smarty, $this, $cache_id,
                $compile_id,
                $caching,
                $cache_lifetime);
 $tpl->properties['nocache_hash'] = $hash;
// get variables from calling scope
if ($parent_scope == Smarty::SCOPE_LOCAL)
                {
 $tpl->tpl_vars = $this->tpl_vars;
 $tpl->tpl_vars['smarty'] = clone $this->tpl_vars['smarty'];
 } elseif ($parent_scope == Smarty::SCOPE_PARENT)
                {
 $tpl->tpl_vars = & $this->tpl_vars;
 } elseif ($parent_scope == Smarty::SCOPE_GLOBAL)
                {
 $tpl->tpl_vars = & Smarty::$global_tpl_vars;
 } elseif (($scope_ptr = $this->getScopePointer($parent_scope))
                == null) {
 $tpl->tpl_vars = & $this->tpl_vars;
 } else {
 $tpl->tpl_vars = & $scope_ptr->tpl_vars;
 }
 $tpl->config_vars = $this->config_vars;
if (!empty($data)) {
// set up variable values
foreach ($data as $_key => $_val) {
 $tpl->tpl_vars[$_key] = new Smarty_variable($_val);
 }
 }
return $tpl;
 }
writeCachedContent ($content)
Writes the cached template output
Returns
bool
Definition at line 218 of file smarty_internal_template.php.
References $cache_lifetime, Smarty\CACHING_LIFETIME_CURRENT, Smarty\CACHING_LIFETIME_SAVED, and createTemplateCodeFrame().
 {
if ($this->source->recompiled || !($this->caching
                == Smarty::CACHING_LIFETIME_CURRENT
                || $this->caching == Smarty::CACHING_LIFETIME_SAVED))
                {
// don't write cache file
return false;
 }
 $this->properties['cache_lifetime'] = $this->cache_lifetime;
 $this->properties['unifunc'] = 'content_' . str_replace('.', '_', uniqid('', true));
 $content = $this->createTemplateCodeFrame($content,
                true);
 $_smarty_tpl = $this;
 eval("?>" . $content);
 $this->cached->valid = true;
 $this->cached->processed = true;
return $this->cached->write($this, $content);
 }
Field Documentation
$_capture_stack = array(0 => array())
Definition at line 101 of file smarty_internal_template.php.
$allow_relative_path = false
Definition at line 96 of file smarty_internal_template.php.
$block_data = array()
Definition at line 81 of file smarty_internal_template.php.
$cache_id = null
Definition at line 29 of file smarty_internal_template.php.
Referenced by getSubTemplate(), and setupInlineSubTemplate().
$cache_lifetime = null
Definition at line 44 of file smarty_internal_template.php.
Referenced by getSubTemplate(), setupInlineSubTemplate(), and writeCachedContent().
$caching = null
Definition at line 39 of file smarty_internal_template.php.
Referenced by getSubTemplate(), and setupInlineSubTemplate().
$compile_id = null
Definition at line 34 of file smarty_internal_template.php.
Referenced by getSubTemplate(), and setupInlineSubTemplate().
$has_nocache_code = false
Definition at line 59 of file smarty_internal_template.php.
Referenced by createTemplateCodeFrame().
$mustCompile = null
Definition at line 54 of file smarty_internal_template.php.
Referenced by mustCompile().
$properties
Initial value:
= array('file_dependency' => array(),
'nocache_hash' => '',
'function' => array())
Definition at line 64 of file smarty_internal_template.php.
$required_plugins = array('compiled' => array(), 'nocache' => array())
Definition at line 71 of file smarty_internal_template.php.
$smarty = null
Definition at line 76 of file smarty_internal_template.php.
Referenced by __construct().
$template_resource = null
Definition at line 49 of file smarty_internal_template.php.
Referenced by __construct().
$used_tags = array()
Definition at line 91 of file smarty_internal_template.php.
$variable_filters = array()
Definition at line 86 of file smarty_internal_template.php.
The documentation for this class was generated from the following file:
smarty_internal_template.php