oSocial: Smarty_Internal_Debug Class Reference
Smarty_Internal_Debug Class Reference
Static Public Member Functions
static start_compile ($template)
static end_compile ($template)
static start_render ($template)
static end_render ($template)
static start_cache ($template)
static end_cache ($template)
static display_debug ($obj)
static get_debug_vars ($obj)
Static Public Attributes
static $template_data = array()
Static Private Member Functions
static get_key ($template)
Additional Inherited Members
Public Member Functions inherited from Smarty_Internal_Data
assign ($tpl_var, $value=null, $nocache=false)
assignGlobal ($varname, $value=null, $nocache=false)
assignByRef ($tpl_var, &$value, $nocache=false)
append ($tpl_var, $value=null, $merge=false, $nocache=false)
appendByRef ($tpl_var, &$value, $merge=false)
getTemplateVars ($varname=null, $_ptr=null, $search_parents=true)
clearAssign ($tpl_var)
clearAllAssign ()
configLoad ($config_file, $sections=null)
getVariable ($variable, $_ptr=null, $search_parents=true, $error_enable=true)
getConfigVariable ($variable, $error_enable=true)
getStreamVariable ($variable)
getConfigVars ($varname=null, $search_parents=true)
clearConfig ($varname=null)
Data Fields inherited from Smarty_Internal_Data
$template_class = 'Smarty_Internal_Template'
$tpl_vars = array()
$parent = null
$config_vars = array()
Detailed Description
Definition at line 18 of file smarty_internal_debug.php.
Member Function Documentation
static display_debug ($obj) static
Opens a window for the Smarty Debugging Consol and display the data
Parameters
Smarty_Internal_Template | Smarty $obj object to debug
Definition at line 99 of file smarty_internal_debug.php.
Referenced by Smarty_Internal_TemplateBase\fetch().
 {
// prepare information of assigned variables
 $ptr = self::get_debug_vars($obj);
if ($obj instanceof Smarty)
                {
 $smarty = clone $obj;
 } else {
 $smarty = clone $obj->smarty;
 }
 $_assigned_vars = $ptr->tpl_vars;
 ksort($_assigned_vars);
 $_config_vars = $ptr->config_vars;
 ksort($_config_vars);
 $smarty->registered_filters = array();
 $smarty->autoload_filters = array();
 $smarty->default_modifiers = array();
 $smarty->force_compile = false;
 $smarty->left_delimiter = '{';
 $smarty->right_delimiter = '}';
 $smarty->debugging = false;
 $smarty->force_compile = false;
 $_template = new Smarty_Internal_Template($smarty->debug_tpl,
                $smarty);
 $_template->caching = false;
 $_template->disableSecurity();
 $_template->cache_id = null;
 $_template->compile_id = null;
if ($obj instanceof Smarty_Internal_Template)
                {
 $_template->assign('template_name', $obj->source->type
                . ':' . $obj->source->name);
 }
if ($obj instanceof Smarty) {
 $_template->assign('template_data',
                self::$template_data);
 } else {
 $_template->assign('template_data', null);
 }
 $_template->assign('assigned_vars',
                $_assigned_vars);
 $_template->assign('config_vars',
                $_config_vars);
 $_template->assign('execution_time',
                microtime(true) - $smarty->start_time);
 echo $_template->fetch();
 }
static end_cache ($template) static
End logging of cache time
Parameters
object $template cached template
Definition at line 88 of file smarty_internal_debug.php.
Referenced by Smarty_Template_Cached\__construct(), and Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['cache_time'] +=
                microtime(true) - self::$template_data[$key]['start_time'];
 }
static end_compile ($template) static
End logging of compile time
Parameters
object $template
Definition at line 44 of file smarty_internal_debug.php.
Referenced by Smarty_Internal_Template\compileTemplateSource(), and Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['compile_time'] +=
                microtime(true) - self::$template_data[$key]['start_time'];
 }
static end_render ($template) static
End logging of compile time
Parameters
object $template
Definition at line 66 of file smarty_internal_debug.php.
Referenced by Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['render_time'] +=
                microtime(true) - self::$template_data[$key]['start_time'];
 }
static get_debug_vars ($obj) static
Recursively gets variables from all template/data scopes
Parameters
Smarty_Internal_Template | Smarty_Data $obj object to debug
Returns
StdClass
Definition at line 145 of file smarty_internal_debug.php.
References Smarty_Internal_Data\$config_vars, Smarty\$global_tpl_vars, Smarty_Internal_Data\$parent, and Smarty_Internal_Data\$tpl_vars.
 {
$config_vars
                = $obj->config_vars;
$tpl_vars
                = array();
foreach ($obj->tpl_vars as $key => $var) {
$tpl_vars[$key]
                = clone $var;
if ($obj instanceof Smarty_Internal_Template)
                {
$tpl_vars[$key]->scope
                = $obj->source->type . ':' . $obj->source->name;
 } elseif ($obj instanceof Smarty_Data)
                {
$tpl_vars[$key]->scope
                = 'Data object';
 } else {
$tpl_vars[$key]->scope
                = 'Smarty root';
 }
 }
if (isset($obj->parent)) {
$parent
                = self::get_debug_vars($obj->parent);
$tpl_vars
                = array_merge($parent->tpl_vars,
                $tpl_vars);
$config_vars
                = array_merge($parent->config_vars,
                $config_vars);
 } else {
foreach (Smarty::$global_tpl_vars
                as $name => $var) {
if (!array_key_exists($name, $tpl_vars))
                {
 $clone = clone $var;
 $clone->scope = 'Global';
$tpl_vars[$name]
                = $clone;
 }
 }
 }
return (object)array('tpl_vars' =>
                $tpl_vars, 'config_vars' => $config_vars);
 }
static get_key ($template) static private
Return key into $template_data for template
Parameters
object $template template object
Returns
string key into $template_data
Definition at line 182 of file smarty_internal_debug.php.
 {
static $_is_stringy = array('string'
                => true, 'eval' => true);
// calculate Uid if not already done
if ($template->source->uid == '') {
 $template->source->filepath;
 }
 $key = $template->source->uid;
if (isset(self::$template_data[$key])) {
return $key;
 } else {
if (isset($_is_stringy[$template->source->type])) {
 self::$template_data[$key]['name'] = '\'' . substr($template->source->name, 0, 25) . '...\'';
 } else {
 self::$template_data[$key]['name'] =
                $template->source->filepath;
 }
 self::$template_data[$key]['compile_time'] =
                0;
 self::$template_data[$key]['render_time'] = 0;
 self::$template_data[$key]['cache_time'] = 0;
return $key;
 }
 }
static start_cache ($template) static
Start logging of cache time
Parameters
object $template cached template
Definition at line 77 of file smarty_internal_debug.php.
Referenced by Smarty_Template_Cached\__construct(), and Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['start_time'] =
                microtime(true);
 }
static start_compile ($template) static
Start logging of compile time
Parameters
object $template
Definition at line 33 of file smarty_internal_debug.php.
Referenced by Smarty_Internal_Template\compileTemplateSource(), and Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['start_time'] =
                microtime(true);
 }
static start_render ($template) static
Start logging of render time
Parameters
object $template
Definition at line 55 of file smarty_internal_debug.php.
Referenced by Smarty_Internal_TemplateBase\fetch().
 {
 $key = self::get_key($template);
 self::$template_data[$key]['start_time'] =
                microtime(true);
 }
Field Documentation
$template_data = array() static
Definition at line 26 of file smarty_internal_debug.php.
The documentation for this class was generated from the following file:
smarty_internal_debug.php