oSocial: homeStream Class Reference
homeStream Class Reference
Public Member Functions
__construct ()
getGlobalMessages ()
renderWaitingMessage ()
Private Member Functions
getWaiting ()
getNewMessages ()
Private Attributes
$db = null
$core = null
$error = null
$var = null
$messenger = null
Detailed Description
Definition at line 10 of file class.homeStream.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 18 of file class.homeStream.php.
References $dbInstance, and database\getInstance().
 {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 $this->core = new coreFunctions();
 $this->error = new errorHandler();
 $this->var = new varGetter();
 $this->messenger = new messenger();
 }
Member Function Documentation
getGlobalMessages ()
Definition at line 55 of file class.homeStream.php.
References messenger\renderTable().
 {
 $query = "SELECT *, (SELECT CONCAT(firstName, ' ', lastName) FROM user_details WHERE user_details.uid=messages.sender) AS name FROM messages WHERE recipient='-1' ORDER BY sentOn DESC";
if ($result = $this->db->query($query)) {
 $data = null;
while ($row = $result->fetch()) {
 $data[] = $row;
 }
return $this->messenger->renderTable($data);
 } else {
 $this->error->queryError();
return false;
 }
 }
getNewMessages () private
Returns
bool|string
Definition at line 78 of file class.homeStream.php.
Referenced by renderWaitingMessage().
 {
 $uid = $this->var->getUserID();
 $query = "SELECT * FROM messages WHERE recipient='$uid' AND sentOn>=(SELECT eventOn FROM _log WHERE _log.uid=messages.recipient ORDER BY eventOn DESC LIMIT 1)";
if ($result = $this->db->query($query)) {
 $count = $result->rowCount();
 $msg = gettext('YOU_HAVE_%C%_NEW_MESSAGES');
 $msg = str_replace('%C%', '<strong>' . $count . '</strong>',
                $msg);
return '<p>' . $msg . '</p>';
 } else {
 $this->error->queryError();
return false;
 }
 }
getWaiting () private
Beszerzi a várólistán lévő emberek számát
Returns
bool
Definition at line 35 of file class.homeStream.php.
Referenced by renderWaitingMessage().
 {
 $uid = $this->var->getUserID();
 $query = "SELECT COUNT(id) AS counter FROM user_connection WHERE target='$uid' AND state='0'";
if ($result = $this->db->query($query)) {
 $r = $result->fetch();
 $r = $r['counter'];
return $r;
 } else {
 $this->error->queryError();
return false;
 }
 }
renderWaitingMessage ()
Definition at line 99 of file class.homeStream.php.
References getNewMessages(), and getWaiting().
 {
 $counter = $this->getWaiting();
 $r = null;
if ($counter != 0) {
 $r .= '<p>';
 $r .= '<strong>' . $counter . '</strong> ' . gettext('WAITING_FOR_APPROVAL');
 $r .= '</p>';
 }
 $r .= $this->getNewMessages();
return $r;
 }
Field Documentation
$core = null private
Definition at line 13 of file class.homeStream.php.
$db = null private
Definition at line 12 of file class.homeStream.php.
$error = null private
Definition at line 14 of file class.homeStream.php.
$messenger = null private
Definition at line 16 of file class.homeStream.php.
$var = null private
Definition at line 15 of file class.homeStream.php.
The documentation for this class was generated from the following file:
class.homeStream.php