oSocial: auth Class Reference
auth Class Reference
Public Member Functions
__construct ()
spicer ($passToSpice=null)
checkLoginSource ($source= 'session')
loginForm ()
registerForm ()
doLogin ()
doRegister ()
destroyEverything ()
Private Member Functions
checkLogin ($user=null, $pass=null)
Private Attributes
$db = null
$core = null
$error = null
$form = null
$getter = null
$log = null
Detailed Description
User: galiczmiklos Date: 2013.01.14. Time: 12:31
Definition at line 7 of file class.auth.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 16 of file class.auth.php.
References $dbInstance, and database\getInstance().
 {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 $this->core = new coreFunctions();
 $this->error = new errorHandler();
 $this->form = new form();
 $this->getter = new varGetter();
 $this->log = new activityLog();
 }
Member Function Documentation
checkLogin ($user = null, $pass = null) private
A megadott felhasználói adatokat ellenőri le, hogy léteznek -e, helyesek -e és aktív -e a megadott felhasználó
Parameters
string $user Felhasználó
string $pass Jelszó
Returns
bool
Definition at line 36 of file class.auth.php.
References $user.
Referenced by checkLoginSource().
 {
$user = $this->core->cleanVar($user);
 $pass = $this->core->cleanVar($pass);
 $query = "SELECT user_base.id AS id FROM user_base LEFT JOIN user_details ON user_details.uid=user_base.id WHERE `userName`='$user' AND `userPass`='$pass' AND userActive='1'";
if ($result = $this->db->query($query)) {
if ($result->rowCount() == 1) {
return true;
 } else {
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 }
checkLoginSource ($source = 'session')
Bejelentkezési adatok forrás szerinti ellenőrzése Ez egy rövidített változat... az eredeti a TASKNET -ben lelhető fel.
Parameters
string $source session
Returns
bool
Definition at line 70 of file class.auth.php.
References $_SESSION, $user, checkLogin(), and spicer().
Referenced by overseer\control(), and doLogin().
 {
if (!is_null($source)) {
 $source = $this->core->cleanVar($source);
switch ($source) {
case 'session':
if (isset($_SESSION['user']) AND isset($_SESSION['pass'])) {
$user = $this->core->cleanVar($_SESSION['user']);
 $pass = $this->core->cleanVar($_SESSION['pass']);
 } else {
return false;
 }
break;
case 'post':
if (isset($_POST['text-user'])
                AND isset($_POST['pass-pass'])) {
$user = $this->core->cleanVar($_POST['text-user']);
 $pass = $this->spicer($this->core->cleanVar($_POST['pass-pass']));
 } else {
return false;
 }
break;
default:
return false;
break;
 }
if ($this->checkLogin($user, $pass)) {
return true;
 } else {
return false;
 }
 } else {
return false;
 }
 }
destroyEverything ()
Definition at line 259 of file class.auth.php.
References $_SESSION.
Referenced by overseer\control().
 {
 $this->log->logLogout();
if (isset($_SESSION['user'])) {
$_SESSION['user'] = null;
 }
if (isset($_SESSION['pass'])) {
$_SESSION['pass'] = null;
 }
 session_unset(); //session kiürítése
return true;
 }
doLogin ()
Definition at line 166 of file class.auth.php.
References $_SESSION, $valid, checkLoginSource(), and spicer().
Referenced by overseer\doLogin().
 {
$valid = $this->checkLoginSource('post');
if ($valid)
                {
$_SESSION['user'] = $_POST['text-user'];
$_SESSION['pass'] = $this->spicer($_POST['pass-pass']);
$_SESSION['logged'] = true;
 unset($_POST);
 $this->log->logLogin();
return true;
 } else {
 $this->error->errorMSG('Érvénytelen felhasználónév vagy jelszó!');
 unset($_POST);
return false;
 }
 }
doRegister ()
Regisztráció
Returns
bool
Definition at line 192 of file class.auth.php.
References form\checkForErrors(), spicer(), and form\validator().
Referenced by overseer\doLogin().
 {
 $data = $this->form->validator();
//var_dump($data);
//ha az űrlapban nincs validálási hoba
if (!$this->form->checkForErrors($data)) {
if ($data['pass1'] == $data['pass2']) {
//szedjük össze  a szükséges adatokat
 $spicedPass = $this->spicer($data['pass1']);
 $userName = $data['email'];
 $firstName = $data['firstName'];
 $lastName = $data['lastName'];
 $gender = $data['gender'];
 $dateOfBirth = $data['dateOfBirth'];
//illesszük be az alap táblába
 $insertBase = "INSERT INTO user_base(`userName`,`userPass`) VALUES ('$userName','$spicedPass')";
if ($this->db->query($insertBase)) {
//kérjük le a felhasználó azonosítót... nem feltétlenül szükséges, de az esetleges azonosító elcsúszások kezelését megoldják
 $queryUserID = "SELECT `id` FROM `user_base` WHERE `userName`='$userName' AND `userPass`='$spicedPass'";
if ($result = $this->db->query($queryUserID)) {
 $uid = $result->fetch();
 $uid = $uid['id'];
// illeszük be a részleteket
 $insertDetails = "INSERT INTO user_details (`uid`, `firstName`, `lastName`, `gender`, `dateOfBirth`, `regDate`)
                        VALUES ('$uid','$firstName','$lastName','$gender','$dateOfBirth', NOW() )";
if ($this->db->query($insertDetails)) {
//ha minden jó
return true;
 } else {
 $this->error->queryError();
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 } else {
 $this->error->queryError();
return false;
 }
 } else {
 $this->error->errorMSG(gettext('ERROR_PASSWORDS_DONT_MATCH'));
return false;
 }
 } else {
 $this->error->errorMSG(gettext('ERROR_INVALID_DATA'));
return false;
 }
 }
loginForm ()
Definition at line 112 of file class.auth.php.
References $form, and form\generateForm().
Referenced by overseer\doLogin().
 {
$form = array(
 array('type' => 'text', 'name' =>
                'user', 'value' =>
                '', 'placeH' =>
                gettext('PLACEHOLDER_USERNAME')),
 array('type' => 'pass', 'name' =>
                'pass', 'value' =>
                '', 'placeH' =>
                gettext('PLACEHOLDER_PASSWORD'))
 );
return $this->form->generateForm(gettext('FORM_LOGIN_HEADER'), 'login',
                $form);
 }
registerForm ()
Definition at line 122 of file class.auth.php.
References $form, and form\generateForm().
Referenced by overseer\doLogin().
 {
 $genderSelect = $this->getter->formatGendersForSelect();
$form = array(
 array('type' => 'text', 'name' =>
                'firstName', 'value' => '',
                'placeH' => gettext('PLACEHOLDER_FIRSTNAME')),
 array('type' => 'text', 'name' =>
                'lastName', 'value' => '',
                'placeH' => gettext('PLACEHOLDER_LASTNAME')),
 array('type' => 'email', 'name' =>
                'email', 'value' =>
                '', 'placeH' =>
                gettext('PLACEHOLDER_EMAIL')),
 array('type' => 'pass', 'name' =>
                'pass1', 'value' =>
                '', 'placeH' =>
                gettext('PLACEHOLDER_PASSWORD')),
 array('type' => 'pass', 'name' =>
                'pass2', 'value' =>
                '', 'placeH' =>
                gettext('PLACEHOLDER_PASSWORD')),
 array('type' => 'select', 'name' =>
                'gender', 'value'
                => $genderSelect, 'placeH' => gettext('PLACEHOLDER_SELECT_GENDER')),
 array('type' => 'date', 'name' =>
                'dateOfBirth', 'value' => '',
                'placeH' => gettext('PLACEHOLDER_DATE_OF_BIRTH'))
 );
 $r = $this->form->generateForm(gettext('FORM_REGISTER_HEADER'), 'register',
                $form);
 $r .= '
        <script type="text/javascript">
        $().ready(function() {
            $("#pass2").keyup(function() {
                if ($("#pass1").val() != $("#pass2").val()) {
                    $("#pass2").addClass("formError");
                } else {
                    $("#pass2").removeClass("formError");
                }
            });
        });
        $(function() {
                $( "#dateOfBirth" ).datepicker({
                  showAnim: "fold",
                  firstDay: 1,
                  dateFormat: "yy-mm-dd",
                  altFormat: "yy-mm-dd" });
            });
        </script>
        ';
return $r;
 }
spicer ($passToSpice = null)
Definition at line 57 of file class.auth.php.
Referenced by checkLoginSource(), doLogin(), and doRegister().
 {
return md5('salt' . sha1('salt'
                . $passToSpice . 'salt') . 'salt');
 }
Field Documentation
$core = null private
Definition at line 10 of file class.auth.php.
$db = null private
Definition at line 9 of file class.auth.php.
$error = null private
Definition at line 11 of file class.auth.php.
$form = null private
Definition at line 12 of file class.auth.php.
Referenced by loginForm(), and registerForm().
$getter = null private
Definition at line 13 of file class.auth.php.
$log = null private
Definition at line 14 of file class.auth.php.
The documentation for this class was generated from the following file:
class.auth.php