oSocial: offerFriend Class Reference
offerFriend Class Reference
Public Member Functions
__construct ()
renderFriendList ($uid=null)
renderUserList ()
Private Member Functions
getConnections ($uid=null)
renderTable ($data=null)
getUserList ()
Private Attributes
$db = null
$core = null
$error = null
$var = null
$avatar = null
Detailed Description
Barát listák és ajánlások
Definition at line 13 of file class.offerFriend.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 21 of file class.offerFriend.php.
References $dbInstance, and database\getInstance().
 {
$dbInstance = database::getInstance();
 $this->db = $dbInstance->getConnection();
 $this->core = new coreFunctions();
 $this->error = new errorHandler();
 $this->var = new varGetter();
 $this->avatar = new profilePicture();
 }
Member Function Documentation
getConnections ($uid = null) private
Beszerzi az adott felhasználó kapcsolatait Ha nincs $uid megadva akkor a $_SESSION felhasználó alapján tölti be az adatokat
Parameters
null $uid
Returns
array|bool|null
Definition at line 38 of file class.offerFriend.php.
Referenced by renderFriendList().
 {
if (is_null($uid)) {
 $uid = $this->var->getUserID();
 }
if (is_numeric($uid)) {
// TODO: limitálni a lekért oszlopokat
 $query = "
            SELECT *,
            (SELECT userName FROM user_base WHERE user_base.id=user_connection.init) AS initUser,
            (SELECT firstName FROM user_details WHERE user_details.id=user_connection.init) AS initFirstName,
            (SELECT lastName FROM user_details WHERE user_details.id=user_connection.init) AS initLastName
             FROM user_connection
            LEFT JOIN user_details ON user_details.uid=user_connection.target
            LEFT JOIN user_base ON user_connection.target=user_base.id
            WHERE (init='$uid' AND state!='0') OR target='$uid'
            ORDER BY state, userName
            ";
if ($result = $this->db->query($query)) {
 $r = null;
while ($row = $result->fetch()) {
 $r[] = $row;
 }
return $r;
 } else {
 $this->error->queryError();
return false;
 }
 } else {
 $this->error->isNotRequiredVariableType();
return false;
 }
 }
getUserList () private
Teljes felhasználói lista amely megjeleníti a $_SESSION felhasználóhoz képest a kapcsolati legetőségeket
Returns
array|bool|null
Definition at line 304 of file class.offerFriend.php.
Referenced by renderUserList().
 {
 $uid = $this->var->getUserID();
// a sok felhasználó miatt korlátozva lett 40 véletlenszerű megjelenítésre... amúgy sem biztonságos, ha mindenki hozzáfér a teljes adatbázishoz
 $query = "
        SELECT *, (
        SELECT state
        FROM user_connection
        WHERE init='$uid' AND target=user_base.id) AS state,
        user_details.uid AS target
        FROM user_base
        LEFT JOIN user_details ON user_details.uid=user_base.id
        WHERE user_base.id!='$uid'
        ORDER BY RAND(), firstName
        LIMIT 40
        ";
if ($result = $this->db->query($query)) {
 $r = null;
while ($row = $result->fetch()) {
 $r[] = $row;
 }
return $r;
 } else {
 $this->error->queryError();
return false;
 }
 }
renderFriendList ($uid = null)
Kapcsolataim oldalhoz megjelenítendő adatok
Parameters
null $uid
Returns
bool|null|string
Definition at line 228 of file class.offerFriend.php.
References getConnections(), and renderTable().
 {
if (is_null($uid)) {
 $uid = $this->var->getUserID();
 }
if (is_numeric($uid)) {
 $data = $this->getConnections($uid);
if (is_array($data)) {
 $neutral = null;
 $friends = null;
 $blocked = null;
 $r = null;
foreach ($data as $row) {
switch ($row['state']) {
case '-1':
 $blocked[] = $row;
break;
case '0':
 $neutral[] = $row;
break;
case '1':
 $friends[] = $row;
break;
default:
break;
 }
 }
if (is_array($neutral)) {
 $r .= '<h2>';
 $r .= gettext('WAITING');
 $r .= '</h2>';
 $r .= $this->renderTable($neutral);
 }
if (is_array($friends)) {
 $r .= '<h2>';
 $r .= gettext('FRIENDS');
 $r .= '</h2>';
 $r .= $this->renderTable($friends);
 }
if (is_array($blocked)) {
 $r .= '<h2>';
 $r .= gettext('BLOCKED');
 $r .= '</h2>';
 $r .= $this->renderTable($blocked);
 }
return $r;
 } elseif (is_null($data)) {
return '<p>' . gettext('YOU_HAVE_NO_FRIENDS')
                . '</p>';
 } else {
 $this->error->isNotRequiredVariableType();
return false;
 }
 } else {
 $this->error->isNotRequiredVariableType();
return false;
 }
 }
renderTable ($data = null) private
Táblázat megjelenítő
Parameters
null $data
bool $personal
Returns
bool|string
Definition at line 87 of file class.offerFriend.php.
Referenced by renderFriendList().
 {
if (is_array($data)) {
 $uid = $this->var->getUserID();
 $r = null;
 $r .= '<table class="connectionTable">';
 $r .= ' <thead>';
 $r .= '     <tr>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_NAME');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_EMAIL');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '     </tr>';
 $r .= ' </thead>';
 $r .= ' <tfoot>';
 $r .= '     <tr>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_NAME');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_EMAIL');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '     </tr>';
 $r .= ' </tfoot>';
 $r .= ' <tbody>';
foreach ($data as $row) {
if ($row['init'] == $uid) {
 $initer = true;
 } else {
 $initer = false;
 }
if ($row['target'] == $uid) {
 $targeted = true;
 } else {
 $targeted = false;
 }
 $r .= '     <tr>';
 $r .= '         <td>';
if (!$initer) {
 $url = $row['initUser'];
 } else {
 $url = $row['userName'];
 }
 $r .= '<img src="' . $this->avatar->getSmallProfilePic($url)
                . '" />';
 $r .= '         </td>';
 $r .= '         <td>';
if (!$initer) {
 $r .= $row['initFirstName'] . '&nbsp;' . $row['initLastName'];
 } else {
 $r .= $row['firstName'] . '&nbsp;' . $row['lastName'];
 }
 $r .= '         </td>';
 $r .= '         <td>';
if (!$initer) {
 $r .= $row['initUser'];
 } else {
 $r .= $row['userName'];
 }
 $r .= '         </td>';
 $r .= '         <td>';
switch ($row['state']) {
case '-1':
 $r .= '<a href="/connect/' .
                $row['target'] . '.html">';
 $r .= gettext('FRIEND');
 $r .= '</a>';
break;
case '1':
 $r .= '<a href="/block/' . $row['target'] . '.html">';
 $r .= gettext('BLOCK');
 $r .= '</a>';
break;
default:
if (!$initer) {
 $r .= '<a href="/connect/' .
                $row['init'] . '.html">';
 $r .= gettext('FRIEND');
 $r .= '</a>';
 $r .= '&nbsp;';
 $r .= '<a href="/block/' . $row['init'] . '.html">';
 $r .= gettext('BLOCK');
 $r .= '</a>';
 } else {
 $r .= '<a href="/connect/' .
                $row['target'] . '.html">';
 $r .= gettext('FRIEND');
 $r .= '</a>';
 $r .= '&nbsp;';
 $r .= '<a href="/block/' . $row['target'] . '.html">';
 $r .= gettext('BLOCK');
 $r .= '</a>';
 }
break;
 }
 $r .= '         </td>';
 $r .= '     </tr>';
 }
 $r .= ' </tbody>';
 $r .= '</table>';
return $r;
 } else {
 $this->error->isNotArrayError();
return false;
 }
 }
renderUserList ()
Definition at line 341 of file class.offerFriend.php.
References getUserList().
 {
 $data = $this->getUserList();
if (is_array($data)) {
 $uid = $this->var->getUserID();
 $r = null;
 $r .= '<table class="connectionTable">';
 $r .= ' <thead>';
 $r .= '     <tr>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_NAME');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_EMAIL');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '     </tr>';
 $r .= ' </thead>';
 $r .= ' <tfoot>';
 $r .= '     <tr>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_NAME');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= gettext('LIST_EMAIL');
 $r .= '         </th>';
 $r .= '         <th>';
 $r .= '         </th>';
 $r .= '     </tr>';
 $r .= ' </tfoot>';
 $r .= ' <tbody>';
foreach ($data as $row) {
 $r .= '     <tr>';
 $r .= '         <td>';
 $url = $row['userName'];
 $r .= '<img src="' . $this->avatar->getSmallProfilePic($url)
                . '" />';
 $r .= '         </td>';
 $r .= '         <td>';
 $r .= $row['firstName'] . '&nbsp;' . $row['lastName'];
 $r .= '         </td>';
 $r .= '         <td>';
 $r .= $row['userName'];
 $r .= '         </td>';
 $r .= '         <td>';
switch ($row['state']) {
case '-1':
 $r .= '<a href="/connect/' .
                $row['target'] . '.html">';
 $r .= gettext('FRIEND');
 $r .= '</a>';
break;
case '1':
 $r .= '<a href="/block/' . $row['target'] . '.html">';
 $r .= gettext('BLOCK');
 $r .= '</a>';
break;
default:
 $r .= '<a href="/connect/' .
                $row['target'] . '.html">';
 $r .= gettext('FRIEND');
 $r .= '</a>';
 $r .= '&nbsp;';
 $r .= '<a href="/block/' . $row['target'] . '.html">';
 $r .= gettext('BLOCK');
 $r .= '</a>';
break;
 }
 $r .= '         </td>';
 $r .= '     </tr>';
 }
 $r .= ' </tbody>';
 $r .= '</table>';
return $r;
 } else {
 $this->error->isNotArrayError();
return false;
 }
 }
Field Documentation
$avatar = null private
Definition at line 19 of file class.offerFriend.php.
$core = null private
Definition at line 16 of file class.offerFriend.php.
$db = null private
Definition at line 15 of file class.offerFriend.php.
$error = null private
Definition at line 17 of file class.offerFriend.php.
$var = null private
Definition at line 18 of file class.offerFriend.php.
The documentation for this class was generated from the following file:
class.offerFriend.php