oSocial: Smarty_CacheResource_KeyValueStore Class Reference
Smarty_CacheResource_KeyValueStore Class Reference
Public Member Functions
populate (Smarty_Template_Cached $cached, Smarty_Internal_Template $_template)
populateTimestamp (Smarty_Template_Cached $cached)
process (Smarty_Internal_Template $_template, Smarty_Template_Cached $cached=null)
writeCachedContent (Smarty_Internal_Template $_template, $content)
clearAll (Smarty $smarty, $exp_time=null)
clear (Smarty $smarty, $resource_name, $cache_id, $compile_id, $exp_time)
hasLock (Smarty $smarty, Smarty_Template_Cached $cached)
acquireLock (Smarty $smarty, Smarty_Template_Cached $cached)
releaseLock (Smarty $smarty, Smarty_Template_Cached $cached)
Public Member Functions inherited from Smarty_CacheResource
populate (Smarty_Template_Cached $cached, Smarty_Internal_Template $_template)
populateTimestamp (Smarty_Template_Cached $cached)
process (Smarty_Internal_Template $_template, Smarty_Template_Cached $cached=null)
writeCachedContent (Smarty_Internal_Template $_template, $content)
getCachedContent (Smarty_Internal_Template $_template)
clearAll (Smarty $smarty, $exp_time=null)
clear (Smarty $smarty, $resource_name, $cache_id, $compile_id, $exp_time)
locked (Smarty $smarty, Smarty_Template_Cached $cached)
hasLock (Smarty $smarty, Smarty_Template_Cached $cached)
acquireLock (Smarty $smarty, Smarty_Template_Cached $cached)
releaseLock (Smarty $smarty, Smarty_Template_Cached $cached)
Protected Member Functions
getTemplateUid (Smarty $smarty, $resource_name, $cache_id, $compile_id)
sanitize ($string)
fetch ($cid, $resource_name=null, $cache_id=null, $compile_id=null, &$content=null, &$timestamp=null, $resource_uid=null)
addMetaTimestamp (&$content)
getMetaTimestamp (&$content)
invalidate ($cid=null, $resource_name=null, $cache_id=null, $compile_id=null, $resource_uid=null)
getLatestInvalidationTimestamp ($cid, $resource_name=null, $cache_id=null, $compile_id=null, $resource_uid=null)
listInvalidationKeys ($cid, $resource_name=null, $cache_id=null, $compile_id=null, $resource_uid=null)
read (array $keys)
write (array $keys, $expire=null)
delete (array $keys)
purge ()
Protected Attributes
$contents = array()
$timestamps = array()
Additional Inherited Members
Static Public Member Functions inherited from Smarty_CacheResource
static load (Smarty $smarty, $type=null)
static invalidLoadedCache (Smarty $smarty)
Static Public Attributes inherited from Smarty_CacheResource
static $resources = array()
Static Protected Attributes inherited from Smarty_CacheResource
static $sysplugins
Detailed Description
Definition at line 34 of file smarty_cacheresource_keyvaluestore.php.
Member Function Documentation
acquireLock (Smarty $smarty, Smarty_Template_Cached $cached)
Lock cache for this template
Parameters
Smarty $smarty Smarty object
Smarty_Template_Cached $cached cached object
Definition at line 404 of file smarty_cacheresource_keyvaluestore.php.
References write().
 {
 $cached->is_locked = true;
 $key = 'LOCK#' . $cached->filepath;
 $this->write(array($key
                => time()), $smarty->locking_timeout);
 }
addMetaTimestamp (& $content) protected
Add current microtime to the beginning of $cache_content
{
Definition at line 248 of file smarty_cacheresource_keyvaluestore.php.
Referenced by writeCachedContent().
 {
 $mt = explode(" ", microtime());
 $ts = pack("NN", $mt[1], (int)($mt[0] * 100000000));
 $content = $ts . $content;
 }
clear (Smarty $smarty, $resource_name, $cache_id, $compile_id, $exp_time)
Empty cache for a specific template
{
Definition at line 155 of file smarty_cacheresource_keyvaluestore.php.
References getTemplateUid(), invalidate(), and sanitize().
 {
 $uid = $this->getTemplateUid($smarty,
                $resource_name, $cache_id, $compile_id);
 $cid = $uid . '#' . $this->sanitize($resource_name)
                . '#' . $this->sanitize($cache_id)
                . '#' . $this->sanitize($compile_id);
 $this->delete(array($cid));
 $this->invalidate($cid,
                $resource_name, $cache_id, $compile_id, $uid);
return -1;
 }
clearAll (Smarty $smarty, $exp_time = null)
Empty cache
{
Definition at line 132 of file smarty_cacheresource_keyvaluestore.php.
References invalidate(), and purge().
 {
if (!$this->purge())
                {
 $this->invalidate(null);
 }
return -1;
 }
delete (array $keys) abstract protected
Remove values from cache
Parameters
array $keys list of keys to delete
Returns
boolean true on success, false on failure
fetch ($cid, $resource_name = null, $cache_id = null, $compile_id = null, & $content = null, & $timestamp = null, $resource_uid = null) protected
Fetch and prepare a cache object.
Parameters
string $cid CacheID to fetch
string $resource_name template name
string $cache_id cache id
string $compile_id compile id
string $content cached content
integer &$timestamp cached timestamp (epoch)
string $resource_uid resource's uid
Returns
boolean success
Definition at line 224 of file smarty_cacheresource_keyvaluestore.php.
References getLatestInvalidationTimestamp(), getMetaTimestamp(), and read().
Referenced by populateTimestamp(), and process().
 {
 $t = $this->read(array($cid));
 $content = !empty($t[$cid]) ? $t[$cid] : null;
 $timestamp = null;
if ($content && ($timestamp = $this->getMetaTimestamp($content)))
                {
 $invalidated = $this->getLatestInvalidationTimestamp($cid,
                $resource_name, $cache_id, $compile_id, $resource_uid);
if ($invalidated > $timestamp) {
 $timestamp = null;
 $content = null;
 }
 }
return !!$content;
 }
getLatestInvalidationTimestamp ($cid, $resource_name = null, $cache_id = null, $compile_id = null, $resource_uid = null) protected
Determine the latest timestamp known to the invalidation chain
Parameters
string $cid CacheID to determine latest invalidation timestamp of
string $resource_name template name
string $cache_id cache id
string $compile_id compile id
string $resource_uid source's filepath
Returns
float the microtime the CacheID was invalidated
Definition at line 312 of file smarty_cacheresource_keyvaluestore.php.
References listInvalidationKeys(), and read().
Referenced by fetch().
 {
// abort if there is no CacheID
if (false && !$cid)
                {
return 0;
 }
// abort if there are no InvalidationKeys to check
if (!($_cid = $this->listInvalidationKeys($cid,
                $resource_name, $cache_id, $compile_id, $resource_uid))) {
return 0;
 }
// there are no InValidationKeys
if (!($values = $this->read($_cid)))
                {
return 0;
 }
// make sure we're dealing with floats
 $values = array_map('floatval', $values);
return max($values);
 }
getMetaTimestamp (& $content) protected
Extract the timestamp the $content was cached
Parameters
string &$content the cached content
Returns
float the microtime the content was cached
Definition at line 261 of file smarty_cacheresource_keyvaluestore.php.
Referenced by fetch().
 {
 $s = unpack("N", substr($content, 0, 4));
 $m = unpack("N", substr($content, 4, 4));
 $content = substr($content, 8);
return $s[1] + ($m[1] / 100000000);
 }
getTemplateUid (Smarty $smarty, $resource_name, $cache_id, $compile_id) protected
Get template's unique ID
Parameters
Smarty $smarty Smarty object
string $resource_name template name
string $cache_id cache id
string $compile_id compile id
Returns
string filepath of cache file
Definition at line 173 of file smarty_cacheresource_keyvaluestore.php.
Referenced by clear().
 {
 $uid = '';
if (isset($resource_name)) {
 $tpl = new $smarty->template_class($resource_name,
                $smarty);
if ($tpl->source->exists) {
 $uid = $tpl->source->uid;
 }
// remove from template cache
if ($smarty->allow_ambiguous_resources) {
 $_templateId = $tpl->source->unique_resource . $tpl->cache_id . $tpl->compile_id;
 } else {
 $_templateId = $smarty->joined_template_dir . '#' . $resource_name . $tpl->cache_id . $tpl->compile_id;
 }
if (isset($_templateId[150])) {
 $_templateId = sha1($_templateId);
 }
 unset($smarty->template_objects[$_templateId]);
 }
return $uid;
 }
hasLock (Smarty $smarty, Smarty_Template_Cached $cached)
Check is cache is locked for this template
Parameters
Smarty $smarty Smarty object
Smarty_Template_Cached $cached cached object
Returns
booelan true or false if cache is locked
Definition at line 391 of file smarty_cacheresource_keyvaluestore.php.
References read().
 {
 $key = 'LOCK#' . $cached->filepath;
 $data = $this->read(array($key));
return $data && time() - $data[$key] <
                $smarty->locking_timeout;
 }
invalidate ($cid = null, $resource_name = null, $cache_id = null, $compile_id = null, $resource_uid = null) protected
Invalidate CacheID
Parameters
string $cid CacheID
string $resource_name template name
string $cache_id cache id
string $compile_id compile id
string $resource_uid source's uid
Returns
void
Definition at line 279 of file smarty_cacheresource_keyvaluestore.php.
References sanitize(), and write().
Referenced by clear(), and clearAll().
 {
 $now = microtime(true);
 $key = null;
// invalidate everything
if (!$resource_name && !$cache_id &&
                !$compile_id) {
 $key = 'IVK#ALL';
 } // invalidate all caches by template
else if ($resource_name
                && !$cache_id && !$compile_id) {
 $key = 'IVK#TEMPLATE#' . $resource_uid . '#' . $this->sanitize($resource_name);
 } // invalidate all caches by cache group
else if (!$resource_name
                && $cache_id && !$compile_id) {
 $key = 'IVK#CACHE#' . $this->sanitize($cache_id);
 } // invalidate all caches by compile id
else if (!$resource_name
                && !$cache_id && $compile_id) {
 $key = 'IVK#COMPILE#' . $this->sanitize($compile_id);
 } // invalidate by combination
else {
 $key = 'IVK#CID#' . $cid;
 }
 $this->write(array($key
                => $now));
 }
listInvalidationKeys ($cid, $resource_name = null, $cache_id = null, $compile_id = null, $resource_uid = null) protected
Translate a CacheID into the list of applicable InvalidationKeys.
Splits "some|chain|into|an|array" into array('clearAll#', 'some', 'some|chain', 'some|chain|into', ...)
Parameters
string $cid CacheID to translate
string $resource_name template name
string $cache_id cache id
string $compile_id compile id
string $resource_uid source's filepath
Returns
array list of InvalidationKeys $invalidationKeyPrefix to prepend to each InvalidationKey
Definition at line 345 of file smarty_cacheresource_keyvaluestore.php.
References sanitize().
Referenced by getLatestInvalidationTimestamp().
 {
 $t = array('IVK#ALL');
 $_name = $_compile = '#';
if ($resource_name) {
 $_name .= $resource_uid . '#' . $this->sanitize($resource_name);
 $t[] = 'IVK#TEMPLATE' . $_name;
 }
if ($compile_id) {
 $_compile .= $this->sanitize($compile_id);
 $t[] = 'IVK#COMPILE' . $_compile;
 }
 $_name .= '#';
// some poeple smoke bad weed
 $cid = trim($cache_id, '|');
if (!$cid) {
return $t;
 }
 $i = 0;
while (true) {
// determine next delimiter position
 $i = strpos($cid, '|', $i);
// add complete CacheID if there are no more delimiters
if ($i === false) {
 $t[] = 'IVK#CACHE#' . $cid;
 $t[] = 'IVK#CID' . $_name . $cid . $_compile;
 $t[] = 'IVK#CID' . $_name . $_compile;
break;
 }
 $part = substr($cid, 0, $i);
// add slice to list
 $t[] = 'IVK#CACHE#' . $part;
 $t[] = 'IVK#CID' . $_name . $part . $_compile;
// skip past delimiter position
 $i++;
 }
return $t;
 }
populate (Smarty_Template_Cached $cached, Smarty_Internal_Template $_template)
populate Cached Object with meta data from Resource
Parameters
Smarty_Template_Cached $cached cached object
Smarty_Internal_Template $_template template object
Returns
void
Definition at line 55 of file smarty_cacheresource_keyvaluestore.php.
References populateTimestamp(), and sanitize().
 {
 $cached->filepath = $_template->source->uid
 . '#' . $this->sanitize($cached->source->name)
 . '#' . $this->sanitize($cached->cache_id)
 . '#' . $this->sanitize($cached->compile_id);
 $this->populateTimestamp($cached);
 }
populateTimestamp (Smarty_Template_Cached $cached)
populate Cached Object with timestamp and exists from Resource
Parameters
Smarty_Template_Cached $cached cached object
Returns
void
Definition at line 71 of file smarty_cacheresource_keyvaluestore.php.
References fetch().
Referenced by populate().
 {
if (!$this->fetch($cached->filepath,
                $cached->source->name, $cached->cache_id, $cached->compile_id, $content, $timestamp,
                $cached->source->uid)) {
return;
 }
 $cached->content = $content;
 $cached->timestamp = (int)$timestamp;
 $cached->exists = $cached->timestamp;
 }
process (Smarty_Internal_Template $_template, Smarty_Template_Cached $cached = null)
Read the cached template and process the header
Parameters
Smarty_Internal_Template $_template template object
Smarty_Template_Cached $cached cached object
Returns
booelan true or false if the cached content does not exist
Definition at line 88 of file smarty_cacheresource_keyvaluestore.php.
References fetch().
 {
if (!$cached) {
 $cached = $_template->cached;
 }
 $content = $cached->content ? $cached->content : null;
 $timestamp = $cached->timestamp ? $cached->timestamp : null;
if ($content === null || !$timestamp) {
if (!$this->fetch($_template->cached->filepath,
                $_template->source->name, $_template->cache_id, $_template->compile_id, $content,
                $timestamp, $_template->source->uid)) {
return false;
 }
 }
if (isset($content)) {
 $_smarty_tpl = $_template;
 eval("?>" . $content);
return true;
 }
return false;
 }
purge () protected
Remove all values from cache
Returns
boolean true on success, false on failure
Definition at line 454 of file smarty_cacheresource_keyvaluestore.php.
Referenced by clearAll().
 {
return false;
 }
read (array $keys) abstract protected
Read values for a set of keys from cache
Parameters
array $keys list of keys to fetch
Returns
array list of values with the given keys used as indexes
Referenced by fetch(), getLatestInvalidationTimestamp(), and hasLock().
releaseLock (Smarty $smarty, Smarty_Template_Cached $cached)
Unlock cache for this template
Parameters
Smarty $smarty Smarty object
Smarty_Template_Cached $cached cached object
Definition at line 417 of file smarty_cacheresource_keyvaluestore.php.
 {
 $cached->is_locked = false;
 $key = 'LOCK#' . $cached->filepath;
 $this->delete(array($key));
 }
sanitize ($string) protected
Sanitize CacheID components
Parameters
string $string CacheID component to sanitize
Returns
string sanitized CacheID component
Definition at line 202 of file smarty_cacheresource_keyvaluestore.php.
Referenced by clear(), invalidate(), listInvalidationKeys(), and populate().
 {
// some poeple smoke bad weed
 $string = trim($string, '|');
if (!$string) {
return null;
 }
return preg_replace('#[^\w\|]+#S',
                '_', $string);
 }
write (array $keys, $expire = null) abstract protected
Save values for a set of keys to cache
Parameters
array $keys list of values to save
int $expire expiration time
Returns
boolean true on success, false on failure
Referenced by acquireLock(), invalidate(), and writeCachedContent().
writeCachedContent (Smarty_Internal_Template $_template, $content)
Write the rendered template output to cache
Parameters
Smarty_Internal_Template $_template template object
string $content content to cache
Returns
boolean success
Definition at line 115 of file smarty_cacheresource_keyvaluestore.php.
References addMetaTimestamp(), and write().
 {
 $this->addMetaTimestamp($content);
return $this->write(array($_template->cached->filepath
                => $content), $_template->properties['cache_lifetime']);
 }
Field Documentation
$contents = array() protected
Definition at line 41 of file smarty_cacheresource_keyvaluestore.php.
$timestamps = array() protected
Definition at line 46 of file smarty_cacheresource_keyvaluestore.php.
The documentation for this class was generated from the following file:
smarty_cacheresource_keyvaluestore.php